// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `generated/dto/**`: the operation input and output types.
//!
//! Responsible for: the module-per-operation layout, the flat alias module, the shared
//! enumeration and shape vocabulary, and the public-field-count baseline that ADR-0004 P9
//! ratchets against.
//! NOT responsible for: encoding or decoding anything (P5 owns the codecs), the `Operation` trait
//! (P1-07), or the s3s compatibility conversions (P9).
//! Upstream: [`rustfs_gateway_model::ir`]. Downstream: `rustfs-gateway-types`, which mounts these files with
//! `#[path]`, and every operation family above it.
//!
//! # The one rule that shapes this emitter
//!
//! ADR-0004 P1: an Input or Output is a plain struct with public fields and `Default`, and never
//! `#[non_exhaustive]`. The attribute is measured to reject `..Default::default()` as well as
//! whole-struct literals (E0639), so applying it here would break every downstream construction
//! site at once with no mechanical fix. Everything else follows from that: scalar fields are
//! `Option` so that `Default` is always derivable without inventing a wire value that would be
//! invalid, string enumerations are `Cow` newtypes so that a new AWS value stays a minor bump
//! (P4), and only structural unions carry `#[non_exhaustive]` (P5).

pub mod naming;
pub mod registry;
pub mod render;
pub mod shared;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use rustfs_gateway_model::ir::{Binding, Field, OperationIr};

use registry::Registry;

/// The Apache-2.0 header every generated Rust file opens with.
pub const LICENSE: &str = "\
// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask codegen`. Do not edit: change `model/overlays/` and regenerate.
";

/// What one dto run produced, for the codegen report and for the P9 ratchet.
#[derive(Debug, Default)]
pub struct DtoReport {
    /// Input, Output and nested shape structs emitted.
    pub structs: usize,
    /// Input builders emitted; one per operation (ADR-0004 P7).
    pub builders: usize,
    /// String enumerations emitted as `Cow` newtypes (P4).
    pub string_enums: usize,
    /// Structural unions emitted as real `enum`s with `#[non_exhaustive]` (P5).
    pub structural_enums: usize,
    /// Public field count per generated struct, the P9 ratchet baseline.
    pub field_counts: BTreeMap<String, usize>,
}

/// Renders every dto artefact.
///
/// # Errors
///
/// Fails when the IR cannot be turned into a single coherent type vocabulary — two operations
/// disagreeing about one nested shape, or two enumeration values colliding on one constant name.
/// Both need an overlay decision rather than a generator guess.
pub fn emit(operations: &[OperationIr], generated_dir: &Path) -> Result<(Vec<(PathBuf, String)>, DtoReport), String> {
    let mut ordered: Vec<&OperationIr> = operations.iter().collect();
    ordered.sort_by(|a, b| a.operation.cmp(&b.operation));

    let registry = Registry::collect(&ordered)?;
    let mut report = DtoReport::default();
    let mut files: Vec<(PathBuf, String)> = Vec::new();
    let ops_dir = generated_dir.join("dto").join("ops");

    for ir in &ordered {
        files.push((
            ops_dir.join(format!("{}.rs", naming::module_name(&ir.operation))),
            render::operation(ir, &registry, &mut report),
        ));
    }
    for (name, body) in shared::enums(&registry, &mut report) {
        files.push((ops_dir.join("enums").join(name), body));
    }
    for (name, body) in shared::shapes(&registry, &mut report) {
        files.push((ops_dir.join("shapes").join(name), body));
    }
    files.push((ops_dir.join("mod.rs"), render::ops_mod(&ordered)));
    files.push((generated_dir.join("dto").join("flat.rs"), render::flat(&ordered, &registry)));
    files.push((generated_dir.join("dto").join("field_counts.txt"), field_counts(&report)));
    Ok((files, report))
}

/// The ADR-0004 P9 baseline: `<TypeName> <public field count>`, one per line, sorted by name.
///
/// A struct that loses a public field is the one genuinely breaking change this layout still
/// admits, and this file is what a ratchet check diffs against.
fn field_counts(report: &DtoReport) -> String {
    let mut out = String::new();
    for (name, count) in &report.field_counts {
        out.push_str(&format!("{name} {count}\n"));
    }
    out
}

/// One field's rustdoc line: wire name, binding, optionality, wire default.
///
/// Deliberately mechanical. AWS documentation prose is never copied into generated output
/// (ADR-0001), so the only English here is written in this file.
#[must_use]
pub fn field_doc(field: &Field) -> String {
    let mut doc = match (&field.binding, field.wire_name.as_deref()) {
        (Binding::PrefixHeaders, Some(prefix)) => format!("Every header under `{prefix}`."),
        (Binding::Payload, _) => "The message body.".to_owned(),
        (Binding::StatusCode, _) => "The response status code.".to_owned(),
        (binding, Some(wire)) if !wire.is_empty() => format!("Wire `{wire}`, bound as {}.", binding.kind_str()),
        (binding, _) => format!("Bound as {}.", binding.kind_str()),
    };
    doc.push_str(if field.required { " Required." } else { " Optional." });
    if let Some(default) = &field.default {
        doc.push_str(&format!(" Wire default `{}`.", super::json_scalar(default)));
    }
    if registry::is_redacted(field) {
        doc.push_str(" Secret: `Debug` prints a placeholder.");
    }
    doc
}

/// Renders one `pub` field, doc comment included.
#[must_use]
pub fn field_decl(field: &Field) -> String {
    format!(
        "    /// {}\n    pub {}: {},\n",
        field_doc(field),
        naming::field_name(&field.name),
        Registry::field_type(field)
    )
}

/// The derive list for a generated struct.
///
/// `Default` is unconditional (P1). `Clone` drops out when a streaming body is reachable, and
/// `Debug` drops out when a secret field is present, in which case the caller emits an
/// implementation that redacts it. `PartialEq` is never derived: AGENTS.md forbids `==` on key
/// material, and an Input can carry an SSE-C key.
#[must_use]
pub fn derives(clonable: bool, has_secret: bool) -> String {
    let mut list = Vec::new();
    if !has_secret {
        list.push("Debug");
    }
    if clonable {
        list.push("Clone");
    }
    list.push("Default");
    format!("#[derive({})]\n", list.join(", "))
}

/// A hand-written `Debug` that prints a placeholder for every secret field.
///
/// `redact` keeps "absent" and "present but secret" distinguishable — a diagnostic that cannot
/// tell those apart is the reason somebody would delete the redaction again.
#[must_use]
pub fn debug_impl(type_name: &str, fields: &[Field]) -> String {
    let mut out = format!("impl std::fmt::Debug for {type_name} {{\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        fn redact<T>(value: &Option<T>) -> Option<&'static str> {\n");
    out.push_str("            value.as_ref().map(|_| \"<redacted>\")\n        }\n\n");
    out.push_str(&format!("        f.debug_struct(\"{type_name}\")\n"));
    for field in fields {
        let name = naming::field_name(&field.name);
        if registry::is_redacted(field) {
            out.push_str(&format!("            .field(\"{name}\", &redact(&self.{name}))\n"));
        } else {
            out.push_str(&format!("            .field(\"{name}\", &self.{name})\n"));
        }
    }
    out.push_str("            .finish()\n    }\n}\n");
    out
}

/// A `&'static [&'static str]` literal of model member names.
#[must_use]
pub fn name_list(names: &[String], indent: usize) -> String {
    let quoted: Vec<String> = names.iter().map(|n| format!("\"{n}\"")).collect();
    slice_literal(&quoted, indent)
}

/// rustfmt's `array_width` for this repository: 60% of the configured `max_width` of 130.
///
/// The emitted text has to be what rustfmt would produce, because `cargo fmt` follows the
/// `#[path]` modules into `generated/` and any disagreement would make `cargo xtask spec verify`
/// fail the moment somebody formats. `dto_is_already_formatted` in the test suite is the guard
/// that catches a drift in this number.
const ARRAY_WIDTH: usize = 78;

/// rustfmt's `max_width` for this repository.
const MAX_WIDTH: usize = 130;

/// A slice literal, laid out the way rustfmt would lay it out.
#[must_use]
pub fn slice_literal(items: &[String], indent: usize) -> String {
    let single = format!("&[{}]", items.join(", "));
    if single.len() <= ARRAY_WIDTH {
        return single;
    }
    let pad = " ".repeat(indent + 4);
    let body: String = items.iter().map(|item| format!("{pad}{item},\n")).collect();
    format!("&[\n{body}{}]", " ".repeat(indent))
}

/// A `pub use` with a brace group, laid out the way rustfmt would lay it out.
///
/// Names are sorted, because rustfmt sorts them; the group stays on one line while it fits inside
/// `max_width`, and is otherwise filled greedily at one indent level, which is rustfmt's default
/// `imports_layout = "Mixed"`.
#[must_use]
pub fn use_group(path: &str, names: &[String]) -> String {
    let mut sorted: Vec<String> = names.to_vec();
    sorted.sort();
    let single = format!("pub use {path}::{{{}}};", sorted.join(", "));
    if single.len() <= MAX_WIDTH {
        return format!("{single}\n");
    }
    let mut lines: Vec<String> = Vec::new();
    let mut current = String::new();
    for name in &sorted {
        let candidate = if current.is_empty() {
            format!("    {name},")
        } else {
            format!("{current} {name},")
        };
        if !current.is_empty() && candidate.len() > MAX_WIDTH {
            lines.push(std::mem::take(&mut current));
            current = format!("    {name},");
        } else {
            current = candidate;
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    format!("pub use {path}::{{\n{}\n}};\n", lines.join("\n"))
}
