// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `generated/dto/**`: the operation input and output types.
//!
//! Responsible for: the module-per-operation layout, the flat alias module, the shared
//! enumeration and shape vocabulary, and the public-field-count baseline that ADR-0004 P9
//! ratchets against.
//! NOT responsible for: encoding or decoding anything (P5 owns the codecs), the `Operation` trait
//! (P1-07), or the s3s compatibility conversions (P9).
//! Upstream: [`rustfs_gateway_model::ir`]. Downstream: `rustfs-gateway-types`, which mounts these files with
//! `#[path]`, and every operation family above it.
//!
//! # The one rule that shapes this emitter
//!
//! ADR-0004 P1: an Input or Output is a plain struct with public fields and `Default`, and never
//! `#[non_exhaustive]`. The attribute is measured to reject `..Default::default()` as well as
//! whole-struct literals (E0639), so applying it here would break every downstream construction
//! site at once with no mechanical fix.
//!
//! P1 also decides the wrapper: a **required** member is bare (`pub bucket: BucketName`) and an
//! **optional** one is `Option<T>`, so requiredness is expressed by the type rather than lied
//! about by an `Option` that can never be `None`. Making every member `Option` was the earlier
//! reading, and it forced every consumer to unwrap a value the wire contract guarantees. The cost
//! of the bare form is that each scalar reachable from a required member needs a `Default`, which
//! is a wire-invalid placeholder (P10) rather than a plausible value, plus a `check_required` on
//! each generated struct that keeps one off the decode path.
//! [`registry::Registry::required_gap`] is the P2 gate: a required member whose type genuinely has
//! no `Default` fails the run instead of being quietly wrapped back up in an `Option`.
//!
//! The rest follows: string enumerations are `Cow` newtypes so that a new AWS value stays a minor
//! bump (P4), and only structural unions carry `#[non_exhaustive]` (P5).

pub mod naming;
pub mod registry;
pub mod render;
pub mod shared;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use rustfs_gateway_model::ir::{Binding, Field, OperationIr};

use registry::Registry;

/// The Apache-2.0 header every generated Rust file opens with.
pub const LICENSE: &str = "\
// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask codegen`. Do not edit: change `model/overlays/` and regenerate.
";

/// What one dto run produced, for the codegen report and for the P9 ratchet.
#[derive(Debug, Default)]
pub struct DtoReport {
    /// Input, Output and nested shape structs emitted.
    pub structs: usize,
    /// Input builders emitted; one per operation (ADR-0004 P7).
    pub builders: usize,
    /// String enumerations emitted as `Cow` newtypes (P4).
    pub string_enums: usize,
    /// Structural unions emitted as real `enum`s with `#[non_exhaustive]` (P5).
    pub structural_enums: usize,
    /// Public field count per generated struct, the P9 ratchet baseline.
    pub field_counts: BTreeMap<String, usize>,
}

/// Renders every dto artefact.
///
/// # Errors
///
/// Fails when the IR cannot be turned into a single coherent type vocabulary — two operations
/// disagreeing about one nested shape, or two enumeration values colliding on one constant name.
/// Both need an overlay decision rather than a generator guess.
pub fn emit(operations: &[OperationIr], generated_dir: &Path) -> Result<(Vec<(PathBuf, String)>, DtoReport), String> {
    let mut ordered: Vec<&OperationIr> = operations.iter().collect();
    ordered.sort_by(|a, b| a.operation.cmp(&b.operation));

    let registry = Registry::collect(&ordered)?;
    check_required_members_have_defaults(&ordered, &registry)?;
    let mut report = DtoReport::default();
    let mut files: Vec<(PathBuf, String)> = Vec::new();
    let ops_dir = generated_dir.join("dto").join("ops");

    for ir in &ordered {
        files.push((
            ops_dir.join(format!("{}.rs", naming::module_name(&ir.operation))),
            render::operation(ir, &registry, &mut report),
        ));
    }
    for (name, body) in shared::enums(&registry, &mut report) {
        files.push((ops_dir.join("enums").join(name), body));
    }
    for (name, body) in shared::shapes(&registry, &mut report) {
        files.push((ops_dir.join("shapes").join(name), body));
    }
    files.push((ops_dir.join("mod.rs"), render::ops_mod(&ordered)));
    files.push((generated_dir.join("dto").join("flat.rs"), render::flat(&ordered, &registry)));
    files.push((generated_dir.join("dto").join("field_counts.txt"), field_counts(&report)));
    Ok((files, report))
}

/// The ADR-0004 P2 gate, run before a single line is rendered.
///
/// A required member is generated bare, which is only sound while its type has a `Default`. When
/// the model introduces one that has none, the generator must not paper over it — wrapping it in
/// an `Option` would put the type back to lying about the wire contract, and inventing a `Default`
/// for a union or a body stream would put a fabricated wire value into safe code. So the run
/// fails, names the member and the reason, and a human writes the ADR.
fn check_required_members_have_defaults(operations: &[&OperationIr], registry: &Registry) -> Result<(), String> {
    let mut offences: Vec<String> = Vec::new();
    for ir in operations {
        let sides = [("input", ir.input.as_slice()), ("output", ir.output.as_slice())];
        for (side, fields) in sides {
            for field in fields {
                if let Some(reason) = required_gap(registry, field) {
                    offences.push(format!("{}.{side}.{}: {reason}", ir.operation, field.name));
                }
            }
        }
    }
    for shape in registry.shapes.values() {
        for field in &shape.fields {
            if let Some(reason) = required_gap(registry, field) {
                offences.push(format!("shape {}.{}: {reason}", shape.name, field.name));
            }
        }
    }
    if offences.is_empty() {
        return Ok(());
    }
    Err(format!(
        "dto: {} required member(s) have no representable `Default`, so they can be neither bare nor \
         `#[derive(Default)]`-able (ADR-0004 P2):\n  {}\n\n\
         This is the hard failure P2 asks for. Either the overlays mark the member optional, or a human \
         records the decision in an ADR — the generator must not choose.",
        offences.len(),
        offences.join("\n  ")
    ))
}

fn required_gap(registry: &Registry, field: &Field) -> Option<&'static str> {
    if !field.required || Registry::is_container(&field.ty) {
        return None;
    }
    registry.required_gap(&field.ty)
}

/// The ADR-0004 P9 baseline: `<TypeName> <public field count>`, one per line, sorted by name.
///
/// A struct that loses a public field is the one genuinely breaking change this layout still
/// admits, and this file is what a ratchet check diffs against.
fn field_counts(report: &DtoReport) -> String {
    let mut out = String::new();
    for (name, count) in &report.field_counts {
        out.push_str(&format!("{name} {count}\n"));
    }
    out
}

/// One field's rustdoc line: wire name, binding, optionality, wire default.
///
/// Deliberately mechanical. AWS documentation prose is never copied into generated output
/// (ADR-0001), so the only English here is written in this file.
#[must_use]
pub fn field_doc(field: &Field) -> String {
    let mut doc = match (&field.binding, field.wire_name.as_deref()) {
        (Binding::PrefixHeaders, Some(prefix)) => format!("Every header under `{prefix}`."),
        (Binding::Payload, _) => "The message body.".to_owned(),
        (Binding::StatusCode, _) => "The response status code.".to_owned(),
        (binding, Some(wire)) if !wire.is_empty() => format!("Wire `{wire}`, bound as {}.", binding.kind_str()),
        (binding, _) => format!("Bound as {}.", binding.kind_str()),
    };
    doc.push_str(if field.required { " Required." } else { " Optional." });
    if let Some(default) = &field.default {
        doc.push_str(&format!(" Wire default `{}`.", super::json_scalar(default)));
    }
    if registry::is_redacted(field) {
        doc.push_str(" Secret: `Debug` prints a placeholder.");
    }
    doc
}

/// Renders one `pub` field, doc comment included.
#[must_use]
pub fn field_decl(field: &Field) -> String {
    format!(
        "    /// {}\n    pub {}: {},\n",
        field_doc(field),
        naming::field_name(&field.name),
        Registry::field_type(field)
    )
}

/// The derive list for a generated struct.
///
/// `Default` is unconditional (P1). `Clone` drops out when a streaming body is reachable, and
/// `Debug` drops out when a secret field is present, in which case the caller emits an
/// implementation that redacts it. `PartialEq` is never derived: AGENTS.md forbids `==` on key
/// material, and an Input can carry an SSE-C key.
#[must_use]
pub fn derives(clonable: bool, has_secret: bool) -> String {
    let mut list = Vec::new();
    if !has_secret {
        list.push("Debug");
    }
    if clonable {
        list.push("Clone");
    }
    list.push("Default");
    format!("#[derive({})]\n", list.join(", "))
}

/// A hand-written `Debug` that prints a placeholder for every secret field.
///
/// `redact` keeps "absent" and "present but secret" distinguishable — a diagnostic that cannot
/// tell those apart is the reason somebody would delete the redaction again.
#[must_use]
pub fn debug_impl(type_name: &str, fields: &[Field]) -> String {
    let optional_secret = fields
        .iter()
        .any(|f| registry::is_redacted(f) && !f.required && !Registry::is_container(&f.ty));
    let mut out = format!("impl std::fmt::Debug for {type_name} {{\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    if optional_secret {
        out.push_str("        fn redact<T>(value: &Option<T>) -> Option<&'static str> {\n");
        out.push_str("            value.as_ref().map(|_| \"<redacted>\")\n        }\n\n");
    }
    out.push_str(&format!("        f.debug_struct(\"{type_name}\")\n"));
    for field in fields {
        let name = naming::field_name(&field.name);
        let bare = field.required || Registry::is_container(&field.ty);
        match (registry::is_redacted(field), bare) {
            // A bare secret is always present, so there is nothing to keep distinguishable and the
            // placeholder can be written straight in.
            (true, true) => out.push_str(&format!("            .field(\"{name}\", &\"<redacted>\")\n")),
            (true, false) => out.push_str(&format!("            .field(\"{name}\", &redact(&self.{name}))\n")),
            (false, _) => out.push_str(&format!("            .field(\"{name}\", &self.{name})\n")),
        }
    }
    out.push_str("            .finish()\n    }\n}\n");
    out
}

/// The decode-path exit check ADR-0004 P10 asks for, as a method on one generated struct.
///
/// One call per required, non-container member; a required nested structure delegates to its own
/// `check_required`. Members inside a **container** are not walked from here — a decoder builds
/// those one at a time and calls the element's own `check_required` as it does, which is why every
/// nested shape gets the method rather than only the operation structs.
///
/// Returning an error rather than `debug_assert!`-ing is deliberate: a `debug_assert!` is compiled
/// out of the release binary, which is the only build that faces a hostile request, and an empty
/// `BucketName` or `ObjectKey` reaching a handler is a value authorization and storage would both
/// accept and neither would recognise. The check costs one comparison per required member.
#[must_use]
pub fn check_required_impl(type_name: &str, baseline_name: &str, fields: &[Field]) -> String {
    let mut body = String::new();
    for field in fields {
        if !field.required || Registry::is_container(&field.ty) {
            continue;
        }
        let name = naming::field_name(&field.name);
        if matches!(field.ty, rustfs_gateway_model::ir::Type::Structure(_)) {
            body.push_str(&format!("        self.{name}.check_required()?;\n"));
        } else {
            body.push_str(&format!(
                "        crate::reject_placeholder(\"{baseline_name}\", \"{}\", &self.{name})?;\n",
                field.name
            ));
        }
    }
    format!(
        "impl {type_name} {{\n    \
             /// Rejects a required member still holding its placeholder default (ADR-0004 P10).\n    \
             ///\n    \
             /// Call this at the end of decoding. A placeholder here is never a client mistake — a\n    \
             /// request that omits a required member is rejected by the binding that looked for it —\n    \
             /// so an error from this method means the decoder failed to fill the member in. It fails\n    \
             /// closed in release builds, which is the one configuration that matters.\n    \
             ///\n    \
             /// Covers every required, non-container member, recursing into required nested shapes. A\n    \
             /// shape inside a list or a map is checked by the decoder that builds it, through that\n    \
             /// shape's own `check_required`.\n    \
             ///\n    \
             /// # Errors\n    \
             ///\n    \
             /// Returns [`crate::PlaceholderDefault`] naming the first offending member.\n    \
             pub fn check_required(&self) -> Result<(), crate::PlaceholderDefault> {{\n\
             {body}        Ok(())\n    }}\n\
         }}\n"
    )
}

/// A `&'static [&'static str]` literal of model member names.
///
/// `lead` is the text that precedes the literal on its line, indent included. rustfmt decides the
/// layout from the whole line, not from the literal alone, so a caller that cannot say what comes
/// before it cannot produce rustfmt's answer.
#[must_use]
pub fn name_list(names: &[String], indent: usize, lead: &str) -> String {
    let quoted: Vec<String> = names.iter().map(|n| format!("\"{n}\"")).collect();
    slice_literal(&quoted, indent, lead)
}

/// rustfmt's `array_width` for this repository: 60% of the configured `max_width` of 130.
///
/// The emitted text has to be what rustfmt would produce, because `cargo fmt` follows the
/// `#[path]` modules into `generated/` and any disagreement would make `cargo xtask spec verify`
/// fail the moment somebody formats. `dto_is_already_formatted` in the test suite is the guard
/// that catches a drift in this number.
const ARRAY_WIDTH: usize = 78;

/// rustfmt's `max_width` for this repository.
const MAX_WIDTH: usize = 130;

/// The terminator that follows a constant's literal and counts towards the line.
const SEMICOLON: usize = 1;

/// A slice literal, laid out the way rustfmt would lay it out.
///
/// `lead` is what precedes the literal on the same line, indent and the trailing `= ` included.
/// The returned text carries its own separator — a space, or a newline and an indent — so the
/// caller's template must not put one in front of it, or the continuation form would leave
/// trailing whitespace on the line above.
///
/// Two limits decide the layout and both have to hold: the contents fit `array_width`, and the
/// finished line fits `max_width`. Checking only the first produces a line that is under
/// seventy-eight characters of literal and over a hundred and thirty of line, which rustfmt then
/// rewrites — and `cargo xtask spec verify` reports as drift the next time anybody formats the
/// tree.
#[must_use]
pub fn slice_literal(items: &[String], indent: usize, lead: &str) -> String {
    let single = format!("&[{}]", items.join(", "));
    // `array_width` measures the array's *contents* — the delimiters that hold them and the borrow
    // in front are both outside the budget, so all three characters of `&[]` come off. Measuring
    // the brackets as well would explode every list eighty or eighty-one characters wide, which
    // rustfmt keeps on one line, and `cargo fmt` would rewrite the tree that codegen just checked in.
    let contents = single.len().saturating_sub("&[]".len());
    // The declaration in front, the literal, and the semicolon after it: that is the line rustfmt
    // measures, so it is the line measured here.
    let inline_line = lead.len() + single.len() + SEMICOLON;
    if contents <= ARRAY_WIDTH && inline_line <= MAX_WIDTH {
        return format!(" {single}");
    }
    // Before expanding one item per line, rustfmt tries the whole literal on the next line at one
    // further indent. Skipping that step produces a vertical list rustfmt immediately collapses.
    let continued = indent + 4;
    let continued_line = continued + single.len() + SEMICOLON;
    if contents <= ARRAY_WIDTH && continued_line <= MAX_WIDTH {
        return format!("\n{}{single}", " ".repeat(continued));
    }
    let pad = " ".repeat(continued);
    let body: String = items.iter().map(|item| format!("{pad}{item},\n")).collect();
    format!(" &[\n{body}{}]", " ".repeat(indent))
}

/// A `pub use` with a brace group, laid out the way rustfmt would lay it out.
///
/// Names are sorted, because rustfmt sorts them; the group stays on one line while it fits inside
/// `max_width`, and is otherwise filled greedily at one indent level, which is rustfmt's default
/// `imports_layout = "Mixed"`.
#[must_use]
pub fn use_group(path: &str, names: &[String]) -> String {
    let mut sorted: Vec<String> = names.to_vec();
    sorted.sort();
    let single = format!("pub use {path}::{{{}}};", sorted.join(", "));
    if single.len() <= MAX_WIDTH {
        return format!("{single}\n");
    }
    let mut lines: Vec<String> = Vec::new();
    let mut current = String::new();
    for name in &sorted {
        let candidate = if current.is_empty() {
            format!("    {name},")
        } else {
            format!("{current} {name},")
        };
        // Measured, not assumed: rustfmt's `Mixed` import layout starts a new line when the
        // filled line would *reach* `max_width`, not only when it would exceed it — an import
        // line of exactly 130 columns is reformatted onto two. `>=` is that boundary.
        if !current.is_empty() && candidate.len() >= MAX_WIDTH {
            lines.push(std::mem::take(&mut current));
            current = format!("    {name},");
        } else {
            current = candidate;
        }
    }
    if !current.is_empty() {
        lines.push(current);
    }
    format!("pub use {path}::{{\n{}\n}};\n", lines.join("\n"))
}
