// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! A decode-diff fuzz finding as a conformance case draft (a-df-0020).
//!
//! Responsible for: re-running a fuzz artifact through the decode property, refusing one that no
//! longer reproduces, and writing what the gateway answered as a conformance case draft under
//! `conformance/cases/_from_fuzz/`: the request exactly as the property read it, signed with the
//! valid credential, the gateway's refusal (status and code) as the expectation, and `FUZZ-DRAFT`
//! markers where a person must write the rationale and the evidence. A draft is not a case:
//! `scripts/check_fuzz_case_drafts.sh` refuses a committed marker, and a reviewed draft moves to
//! the domain directory its behaviour belongs to, under that domain's next id, with a baseline row.
//! NOT responsible for: finding or minimising the input (`cargo fuzz run` and `cargo fuzz tmin`),
//! or deciding which stack is right.
//! Upstream: `fuzz.rs`. Downstream: the `fuzz-to-case` binary.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::decode::Differ;
use crate::fuzz::{request_of, route_differences};

/// The marker a person replaces before a draft becomes a case.
pub const DRAFT_MARKER: &str = "FUZZ-DRAFT";

/// Where drafts are written, relative to the repository root.
pub const DRAFT_DIR: &str = "conformance/cases/_from_fuzz";

pub(crate) fn escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            character if character.is_control() => {
                let _ = write!(out, "\\u{:04X}", u32::from(character));
            }
            character => out.push(character),
        }
    }
    out
}

/// The draft for one fuzz artifact, and the file name it takes in `dir`.
///
/// # Errors
///
/// The bytes are not a request, the finding no longer reproduces, the request carries SSE-C
/// members (a case replays over plaintext, where the gateway refuses those for their own reason;
/// write it by hand as a TLS case), a header value is not UTF-8, or the harness failed.
pub fn draft(input: &[u8], dir: &Path) -> Result<(PathBuf, String), String> {
    draft_with(&Differ::new()?, input, dir)
}

/// [`draft`] against `differ`: the negative controls convert a finding an injected fault causes.
pub(crate) fn draft_with(differ: &Differ, input: &[u8], dir: &Path) -> Result<(PathBuf, String), String> {
    let request = request_of(input).ok_or("the artifact is not a request the decode property reads")?;
    let differences = route_differences(differ, &request)?;
    let Some(finding) = differences.first() else {
        return Err("the artifact no longer reproduces an unregistered route difference; nothing to convert".to_owned());
    };
    if request.secure {
        return Err("the request carries SSE-C members and is compared as over TLS; write it by hand as a TLS case".to_owned());
    }
    let diff = differ.diff(&request)?;
    let digest = hex::encode(Sha256::digest(input));
    let number = next_number(dir)?;
    let id = format!("c-fuzz-{number:04}");
    let mut out = String::new();
    let _ = writeln!(
        out,
        "# {DRAFT_MARKER}: generated by `fuzz-to-case` from a decode_diff fuzz artifact (sha256 {digest})."
    );
    let _ = writeln!(
        out,
        "# Not a case yet: write the rationale and the evidence, then move it to the domain directory its"
    );
    let _ = writeln!(out, "# behaviour belongs to, under that domain's next id, and add its baseline row.");
    let _ = writeln!(out, "#");
    // Comments hold what the stacks said, which can echo request bytes: escaped like any string,
    // since a control character is not allowed even in a TOML comment.
    let _ = writeln!(out, "# Finding: {}", escape(&finding.to_string()));
    let _ = writeln!(
        out,
        "# s3s: {}",
        escape(
            &diff
                .error
                .s3s
                .as_ref()
                .map_or_else(|| "handled".to_owned(), ToString::to_string)
        )
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "[case]");
    let _ = writeln!(out, "id = \"{id}\"");
    let _ = writeln!(out, "schema_version = 1");
    let _ = writeln!(
        out,
        "title = \"{DRAFT_MARKER}: {} {} reaches {} on the gateway and {} on s3s\"",
        request.method,
        escape(&request.target),
        escape(&finding.gateway),
        escape(&finding.s3s)
    );
    let _ = writeln!(
        out,
        "rationale = \"{DRAFT_MARKER}: say what a client sees when the gateway and RustFS route this request to different operations, and which is right.\""
    );
    let _ = writeln!(out, "polarity = \"negative\"");
    let _ = writeln!(out, "operation = \"{}\"", finding.gateway);
    let _ = writeln!(out, "tags = [\"routing\"]");
    let _ = writeln!(out, "timeout_ms = 10000");
    let _ = writeln!(out, "quirks = []");
    let _ = writeln!(out);
    let _ = writeln!(out, "[[case.evidence]]");
    let _ = writeln!(out, "url = \"urn:rustfs-gateway:fuzz:decode_diff:{digest}\"");
    let _ = writeln!(out, "summary = \"{DRAFT_MARKER}: replace with a URL and one original sentence.\"");
    let _ = writeln!(out, "kind = \"observed\"");
    let _ = writeln!(out);
    let _ = writeln!(out, "[request]");
    let _ = writeln!(out, "method = \"{}\"", request.method);
    let _ = writeln!(out, "target = \"{}\"", escape(&request.target));
    let headers: Vec<(&str, &str)> = request
        .headers
        .iter()
        .filter(|(name, _)| !name.eq_ignore_ascii_case("content-length"))
        .map(|(name, value)| {
            std::str::from_utf8(value)
                .map(|value| (name.as_str(), value))
                .map_err(|_| format!("header {name} is not UTF-8; write this case with raw_head_hex by hand"))
        })
        .collect::<Result<_, _>>()?;
    if !headers.is_empty() {
        let _ = writeln!(out, "raw_headers = [");
        for (name, value) in headers {
            let _ = writeln!(out, "  [\"{}\", \"{}\"],", escape(name), escape(value));
        }
        let _ = writeln!(out, "]");
    }
    let body = request.body.concat();
    if !body.is_empty() {
        let _ = writeln!(out, "body = {{ hex = \"{}\" }}", hex::encode(&body));
    }
    let _ = writeln!(
        out,
        "sign = {{ mode = \"sigv4_header\", service = \"s3\", region = \"us-east-1\", credential = \"valid\" }}"
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "[expect]");
    let _ = writeln!(out, "kind = \"response\"");
    match &diff.error.gateway {
        Some(refusal) => {
            let _ = writeln!(out, "status = {}", refusal.status);
            if let Some(code) = &refusal.code {
                let _ = writeln!(out);
                let _ = writeln!(out, "[expect.error]");
                let _ = writeln!(out, "code = \"{}\"", escape(code));
            }
        }
        None => {
            // The most dangerous finding: the gateway ran a handler, for another operation than
            // RustFS runs today. What that handler answers is the backend's; a person writes it.
            let _ = writeln!(
                out,
                "status = 0 # {DRAFT_MARKER}: the gateway ran its {} handler; write the status the case must see",
                escape(&finding.gateway)
            );
        }
    }
    Ok((dir.join(format!("{id}.toml")), out))
}

/// The next unused draft number in `dir`: one past the highest `c-fuzz-NNNN.toml` there.
fn next_number(dir: &Path) -> Result<u32, String> {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(1),
        Err(error) => return Err(format!("{}: {error}", dir.display())),
    };
    let mut highest = 0;
    for entry in entries {
        let name = entry.map_err(|error| format!("{}: {error}", dir.display()))?.file_name();
        let number = name
            .to_str()
            .and_then(|name| name.strip_prefix("c-fuzz-"))
            .and_then(|rest| rest.strip_suffix(".toml"))
            .and_then(|digits| digits.parse::<u32>().ok());
        highest = highest.max(number.unwrap_or(0));
    }
    Ok(highest + 1)
}
