// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo test -p rustfs-gateway-macros`. Do not edit: change the macro and rerun
// with UPDATE_GOLDEN=1. This is what the compiler sees for the input file of the same name, so
// reading it is always an alternative to reading the macro.

impl Fs {
    async fn get_bucket_location(
        &self,
        request: Req<GetBucketLocation>,
    ) -> HandlerResult<GetBucketLocation> {
        let bucket = request.input().bucket.clone();
        self.region_of(&bucket).await
    }
}
impl Fs {
    ///Registers the operations implemented in this block: GetBucketLocation.
    ///
    /// Generated by `#[rustfs_gateway::handlers]`. The hand-written equivalent is a
    /// chain of `RouterBuilder::handle` calls, one per operation.
    pub fn register(
        this: &::std::sync::Arc<Self>,
        builder: ::rustfs_gateway::RouterBuilder,
    ) -> ::rustfs_gateway::RouterBuilder {
        builder.handle::<GetBucketLocation, Self>(::std::sync::Arc::clone(this))
    }
}
impl ::rustfs_gateway::Handler<GetBucketLocation> for Fs {
    fn call(
        &self,
        request: ::rustfs_gateway::Req<GetBucketLocation>,
    ) -> impl ::core::future::Future<
        Output = ::rustfs_gateway::HandlerResult<GetBucketLocation>,
    > + ::core::marker::Send {
        self.get_bucket_location(request)
    }
}
