// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo test -p rustfs-gateway-macros`. Do not edit: change the macro and rerun
// with UPDATE_GOLDEN=1. This is what the compiler sees for the input file of the same name, so
// reading it is always an alternative to reading the macro.

impl Fs {
    async fn put_object(&self, request: Req<PutObject>) -> HandlerResult<PutObject> {
        self.write(request.into_input()).await
    }
    async fn list_objects_v2(
        &self,
        request: Req<ListObjectsV2>,
    ) -> HandlerResult<ListObjectsV2> {
        self.list(request.into_input()).await
    }
}
impl Fs {
    ///Registers the operations implemented in this block: PutObject, ListObjectsV2.
    ///
    /// Generated by `#[rustfs_gateway::handlers]`. The hand-written equivalent is a
    /// chain of `RouterBuilder::handle` calls, one per operation.
    pub fn register_objects(
        this: &::std::sync::Arc<Self>,
        builder: ::rustfs_gateway::RouterBuilder,
    ) -> ::rustfs_gateway::RouterBuilder {
        let _ = this;
        let builder = builder.handle::<PutObject, Self>(::std::sync::Arc::clone(this));
        let builder = builder
            .handle::<ListObjectsV2, Self>(::std::sync::Arc::clone(this));
        builder
    }
}
impl ::rustfs_gateway::Handler<PutObject> for Fs {
    fn call(
        &self,
        request: ::rustfs_gateway::Req<PutObject>,
    ) -> impl ::core::future::Future<
        Output = ::rustfs_gateway::HandlerResult<PutObject>,
    > + ::core::marker::Send {
        self.put_object(request)
    }
    fn call_with_context(
        &self,
        request: ::rustfs_gateway::Req<PutObject>,
        _context: ::rustfs_gateway::HandlerContext,
    ) -> impl ::core::future::Future<
        Output = ::rustfs_gateway::HandlerResult<PutObject>,
    > + ::core::marker::Send {
        self.put_object(request)
    }
}
impl ::rustfs_gateway::Handler<ListObjectsV2> for Fs {
    fn call(
        &self,
        request: ::rustfs_gateway::Req<ListObjectsV2>,
    ) -> impl ::core::future::Future<
        Output = ::rustfs_gateway::HandlerResult<ListObjectsV2>,
    > + ::core::marker::Send {
        self.list_objects_v2(request)
    }
    fn call_with_context(
        &self,
        request: ::rustfs_gateway::Req<ListObjectsV2>,
        _context: ::rustfs_gateway::HandlerContext,
    ) -> impl ::core::future::Future<
        Output = ::rustfs_gateway::HandlerResult<ListObjectsV2>,
    > + ::core::marker::Send {
        self.list_objects_v2(request)
    }
}
