// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The Rust source `cargo xtask rustfs-admin-dialect` writes: one operation module per declared
//! operation, the module list, and the dialect's table, split into one file per list.
//!
//! Responsible for: rendering each file from a [`Plan`] exactly, before rustfmt.
//! NOT responsible for: choosing or ruling the routes, running rustfmt, or writing and comparing
//! files (`super`).
//! Upstream: `super::plan`. Downstream: `super::generate`.

use std::fmt::Write as _;

use super::rulings::{About, Absent};
use super::{Bound, Declared, Plan};

const LICENSE: &str = "// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

";

fn selector(declared: &Declared) -> String {
    let mut predicates = format!("Predicate::Method(http::Method::{})", declared.method);
    if let Some((key, value)) = declared.query {
        let _ = write!(predicates, ", Predicate::QueryEquals({key:?}, {value:?})");
    }
    predicates
}

/// The overlay's rendering of the rows.
fn rendered_selector(declared: &Declared) -> String {
    let row = |template: &str| {
        let mut rendered = format!("PathTemplate({template:?}) ∧ Method({})", declared.method);
        if let Some((key, value)) = declared.query {
            let _ = write!(rendered, " ∧ QueryEquals({key:?}, {value:?})");
        }
        rendered
    };
    std::iter::once(declared.path.as_str())
        .chain(declared.alias.as_deref())
        .map(row)
        .collect::<Vec<_>>()
        .join(" ∨ ")
}

fn request(declared: &Declared) -> String {
    match declared.query {
        Some((key, value)) => format!("{} {}?{key}={value}", declared.method, declared.path),
        None => format!("{} {}", declared.method, declared.path),
    }
}

/// The module documentation's paragraph on whose account the operation acts on.
fn subject_doc(about: About, actions: &[&str]) -> String {
    match about {
        About::Caller => format!(
            "//! It acts only on the caller's own account (`SubjectRule::Caller`): the request cannot name another.\n\
             //! RustFS evaluates no IAM action here, so its action is the vendor label `{}`, which the\n\
             //! authorizer is still asked (ADR-0025, ADR-0028).\n",
            actions.first().copied().unwrap_or_default()
        ),
        About::Query { param, aliases, absent } => {
            let mut doc = format!(
                "//! It acts on the account the `{param}` query parameter names; an absent or empty one is {}.\n\
                 //! The facade reads it once, strictly, before authentication, and hands it to both authorizer\n\
                 //! stages and to the handler as `RequestContextView::subject()`; a handler never reads the query\n\
                 //! for it (ADR-0025, ADR-0028).\n",
                match absent {
                    Absent::Caller => "the caller",
                    Absent::Refuse => "a `400` before authentication",
                }
            );
            if !aliases.is_empty() {
                let spelled: Vec<String> = aliases.iter().map(|alias| format!("`{alias}`")).collect();
                let _ = writeln!(
                    doc,
                    "//! RustFS also reads it as {}, so the facade does too: one spelling, once, or a `400` naming\n\
                     //! `{param}` (ADR-0029).",
                    spelled.join(" or ")
                );
            }
            doc
        }
        About::Set { param, everyone } => {
            let mut doc = format!(
                "//! It acts on each account a `{param}` parameter names, each asked about in turn; naming nobody is the\n\
                 //! caller. The handler reads `RequestContextView::subjects()` (ADR-0026).\n"
            );
            if let Some((flag, action)) = everyone {
                let _ = writeln!(
                    doc,
                    "//! `{flag}=true` is every account, which also needs `{action}`, both asked about no account."
                );
            }
            let _ = writeln!(
                doc,
                "//! A signed request cannot repeat `{param}` today: SigV4 canonicalisation refuses it, so naming\n\
                 //! several accounts fails closed before anything reads the set (ADR-0026 (d))."
            );
            doc
        }
    }
}

/// The `rustfs_gateway_core` root items an operation module uses.
fn core_root_imports(about: Option<About>) -> &'static str {
    match about {
        None => "DerivedResourceError, NoDerived",
        Some(About::Caller | About::Set { everyone: None, .. }) => "DerivedResourceError, NoDerived, SubjectRule",
        Some(About::Query { .. }) => "DerivedResourceError, NoDerived, SubjectRule, WhenAbsent",
        Some(About::Set { everyone: Some(_), .. }) => "DerivedResourceError, Everyone, NoDerived, SubjectRule",
    }
}

fn evidence(d: &Declared) -> String {
    let mut cited = vec![format!("{:?}", d.handler_url)];
    if d.ruled.is_some() {
        cited.push("record::ADR_0025".to_owned());
    }
    if matches!(d.rule.about, Some(About::Set { .. })) || matches!(d.bucket, Some(Bound::Query(_))) {
        cited.push("record::ADR_0026".to_owned());
    }
    if !d.params.is_empty() || !d.shadows.is_empty() {
        cited.push("record::ADR_0027".to_owned());
    }
    if d.rule.about.is_some() {
        cited.push("record::ADR_0028".to_owned());
    }
    if d.bucket.is_some() || d.path.ends_with('/') {
        cited.push("record::ADR_0030".to_owned());
    }
    if d.path.starts_with("/_iceberg/") {
        cited.push("record::ADR_0031".to_owned());
    }
    cited.push("record::ISSUE".to_owned());
    format!("&[{}]", cited.join(", "))
}

/// The module documentation's paragraph on the service-level path parameters `params`.
fn service_level_doc(params: &[&String], other: bool) -> String {
    let listed: Vec<String> = params.iter().map(|param| format!("`{param}`")).collect();
    format!(
        "//!\n//! Its {}path parameter{} ({}) name{} no bucket (ADR-0027): a handler reads each decoded value from\n\
         //! `RequestContextView::path_params()`.\n",
        if other { "other " } else { "" },
        if params.len() == 1 { "" } else { "s" },
        listed.join(", "),
        if params.len() == 1 { "s" } else { "" },
    )
}

/// The module documentation's paragraphs on the operation's bucket, its other path parameters, and
/// a trailing `/`.
fn bucket_doc(d: &Declared) -> String {
    let mut doc = String::new();
    match &d.bucket {
        Some(Bound::Path(param)) => {
            let _ = write!(
                doc,
                "//!\n//! Its `{{{param}}}` parameter is the bucket the operation is authorised on (`BucketParam::Path`,\n\
                 //! ADR-0025 (c), ADR-0030): the raw segment meets the S3 bucket-name rules before authentication, and\n\
                 //! the governor, both authorizer stages, the audit event and the handler's `RequestContextView::bucket()`\n\
                 //! see that bucket and no key. Where RustFS authorises this action on no bucket and reads the segment\n\
                 //! afterwards, handing the authorizer the bucket is a deliberate tightening.\n"
            );
            let others: Vec<&String> = d.params.iter().filter(|other| *other != param).collect();
            if !others.is_empty() {
                doc.push_str(&service_level_doc(&others, true));
            }
        }
        Some(Bound::Query(param)) => {
            let _ = write!(
                doc,
                "//!\n//! Its bucket is the `{param}` query parameter, present exactly once (`BucketParam::Query`, ADR-0026 (e),\n\
                 //! ADR-0030): a repeated, undecodable, absent or empty one is a `400` naming it, before authentication,\n\
                 //! and the raw value meets the S3 bucket-name rules. RustFS reads the first of several values and\n\
                 //! refuses only an empty one, after authorisation.\n"
            );
            if !d.params.is_empty() {
                doc.push_str(&service_level_doc(&d.params.iter().collect::<Vec<_>>(), false));
            }
        }
        None if !d.params.is_empty() => doc.push_str(&service_level_doc(&d.params.iter().collect::<Vec<_>>(), false)),
        None => {}
    }
    if d.path.ends_with('/') {
        doc.push_str(
            "//!\n//! RustFS registers this route with its trailing `/`, and so does the template: it matches exactly that\n\
             //! path, and the path without the `/` names no operation, as in RustFS (ADR-0030).\n",
        );
    }
    doc
}

pub(super) fn render_operation(declared: &Declared) -> String {
    let mut out = String::from(LICENSE);
    let d = declared;
    let request = request(d);
    let _ = writeln!(out, "//! `{}`: `{request}`, registration group `{}`.", d.name, d.group);
    out.push_str("//!\n");
    out.push_str("//! Responsible for: the operation's type, name, rows, action, specification, floor and codec, as the\n");
    let _ = writeln!(out, "//! inventory records RustFS's `{}` route.", d.handler);
    out.push_str("//! NOT responsible for: the handler, which the deployment registers, or the overlay row (`crate::table`).\n");
    out.push_str("//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it,\n");
    let _ = writeln!(out, "//! and a deployment that registers a handler for [`{}`].", d.type_name);
    if let Some(class) = &d.ruled {
        out.push_str("//!\n");
        let _ = writeln!(
            out,
            "//! The inventory records this route as custom-auth (`{class}`); its action is ADR-0025's ruling."
        );
    }
    if let Some(about) = d.rule.about {
        out.push_str("//!\n");
        out.push_str(&subject_doc(about, &d.rule.actions()));
    }
    out.push_str(&bucket_doc(d));
    for shadow in &d.shadows {
        out.push_str("//!\n");
        let _ = writeln!(
            out,
            "//! Its literal `{}` segment stands in front of `{}`'s `{{{}}}` parameter (ADR-0027).",
            shadow.literal, shadow.shadowed, shadow.param
        );
    }
    out.push('\n');
    let (input, mode, decode, input_doc) = match d.request_body {
        "NotRead" => ("()", "None", "Ok(())", "RustFS reads no request body."),
        "Buffered" => (
            "Bytes",
            "Full",
            "admin::buffered(body)",
            "The body as it arrived, which RustFS buffers and parses.",
        ),
        "HandedOn" => (
            "ByteStream",
            "Streaming",
            "admin::streamed(body)",
            "The live body, which RustFS hands on unread to the table catalog.",
        ),
        _ => ("ByteStream", "Streaming", "admin::streamed(body)", "The live body, which RustFS streams."),
    };
    out.push_str("use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};\n");
    if d.bucket.is_some() {
        out.push_str("use rustfs_gateway_core::dialect::{BucketParam, ClaimedRow, OverlayRow};\n");
    } else {
        out.push_str("use rustfs_gateway_core::dialect::{ClaimedRow, OverlayRow};\n");
    }
    out.push_str("use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};\n");
    out.push_str("use rustfs_gateway_core::registry::OperationSpec;\n");
    if d.shadows.is_empty() {
        out.push_str("use rustfs_gateway_core::route::Predicate;\n");
    } else {
        out.push_str("use rustfs_gateway_core::route::{Predicate, ShadowingDecl};\n");
    }
    let _ = writeln!(out, "use rustfs_gateway_core::{{{}}};", core_root_imports(d.rule.about));
    out.push_str("use rustfs_gateway_sig::OperationFloor;\n");
    match input {
        "Bytes" => out.push_str("use bytes::Bytes;\n"),
        "ByteStream" => out.push_str("use rustfs_gateway_stream::ByteStream;\n"),
        _ => {}
    }
    out.push_str(
        "\nuse crate::admin::{self, AdminOperation, AdminResponse};\nuse crate::record::{self, BodyKind, RouteRecord};\n\n",
    );
    let _ = writeln!(out, "/// The operation name.\npub const NAME: &str = {:?};\n", d.name);
    if let Some(subject) = d.rule.subject_expression() {
        let _ = writeln!(
            out,
            "/// Whose account it acts on, which the facade extracts before authentication.\npub const SUBJECT: SubjectRule = {subject};\n"
        );
    }
    let (resource, on) = match &d.bucket {
        Some(Bound::Path(param)) => ("ResourceShape::Bucket", format!("the bucket its `{{{param}}}` parameter names")),
        Some(Bound::Query(param)) => ("ResourceShape::Bucket", format!("the bucket its `{param}` query parameter names")),
        None => ("ResourceShape::Service", "no bucket".to_owned()),
    };
    let _ = writeln!(
        out,
        "/// What authorises it, on {on}.\npub const AUTH: AuthRequirement = {};\n",
        d.rule.expression(resource)
    );
    if let Some(bound) = &d.bucket {
        let _ = writeln!(
            out,
            "/// The bucket it is authorised on, which the facade reads before authentication.\npub const BUCKET: BucketParam = {};\n",
            bound.expression()
        );
    }
    let _ = writeln!(out, "static SELECTOR: &[Predicate] = &[{}];\n", selector(d));
    let mut rows = format!("ClaimedRow {{ template: {:?}, selector: SELECTOR }}", d.path);
    if let Some(alias) = &d.alias {
        let _ = write!(rows, ", ClaimedRow {{ template: {alias:?}, selector: SELECTOR }}");
    }
    let rows_doc = match &d.alias {
        Some(alias) if alias.starts_with("/iceberg/") => "The canonical row, then the compat row RustFS serves it under.",
        Some(_) => "The canonical row, then the MinIO alias RustFS serves it under.",
        None => "The canonical row; RustFS serves no MinIO alias for it.",
    };
    let _ = writeln!(out, "/// {rows_doc}\npub static ROWS: &[ClaimedRow] = &[{rows}];\n");
    if !d.shadows.is_empty() {
        out.push_str(
            "/// The later operations whose parameter meets a literal segment of this one's path: RustFS's router\n\
             /// tries the literal first, so these requests are this operation (ADR-0027).\n\
             pub static SHADOWS: &[ShadowingDecl] = &[\n",
        );
        for shadow in &d.shadows {
            let _ = writeln!(
                out,
                "ShadowingDecl {{ winner: NAME, shadowed: {shadowed:?}, reason: {reason:?}, evidence: &[{router:?}, record::ADR_0027{more}] }},",
                shadowed = shadow.shadowed,
                reason = format!(
                    "RustFS's router tries a literal segment before a parameter, so `{}` here is this operation, never a `{{{}}}` value.",
                    shadow.literal, shadow.param
                ),
                router = d.router_url,
                more = if d.path.starts_with("/_iceberg/") {
                    ", record::ADR_0031"
                } else {
                    ""
                },
            );
        }
        out.push_str("];\n\n");
    }
    let _ = writeln!(out, "/// `{request}`.\n#[derive(Debug)]\npub struct {};\n", d.type_name);
    let _ = writeln!(out, "static SPEC: OperationSpec = admin::spec(NAME, AUTH, {});\n", d.caller_secret);
    out.push_str("/// Privileged and header-signed only: never anonymous, never presigned.\n");
    out.push_str("static FLOOR: OperationFloor = admin::floor(NAME);\n\n");
    let _ = write!(
        out,
        "impl Operation for {ty} {{
    const NAME: &'static str = NAME;

    /// {input_doc}
    type Input = {input};
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {{
        Ok(NoDerived)
    }}

    fn seal_derived_input(_input: &mut Self::Input) {{}}

    fn spec() -> &'static OperationSpec {{
        &SPEC
    }}

    fn floor() -> &'static OperationFloor {{
        &FLOOR
    }}
}}

impl OperationCodec for {ty} {{
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::{mode};

    fn decode(_request: &MetaView<'_>, {body}: RequestBody) -> Result<Self::Input, CodecError> {{
        {decode}
    }}

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {{
        admin::encode(output, status)
    }}
}}

impl AdminOperation for {ty} {{
    const PRECEDENCE: u16 = OVERLAY_ROW.precedence;
    const GROUP: &'static str = RECORD.group;
{bucket_const}
    fn rows() -> &'static [ClaimedRow] {{
        ROWS
    }}
{shadows_fn}}}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {{
    name: NAME,
    precedence: {precedence},
    selector: {selector:?},
    action: {action:?},
    resource: {resource},
    success_status: 200,
    anonymous: false,
    evidence: {evidence},
}};

/// The inventory row this operation was generated from.
pub const RECORD: RouteRecord = RouteRecord {{
    operation: NAME,
    group: {group:?},
    order: {order},
    method: {method:?},
    path: {path:?},
    alias: {alias},
    query: {query},
    action: {action:?},
    ruled: {ruled},
    subject: {subject},
    bucket: {bucket},
    rustfs_handler: {handler:?},
    request_body: BodyKind::{request_body},
    response_body: BodyKind::{response_body},
    caller_secret: {secret},
}};
",
        ty = d.type_name,
        body = if input == "()" { "_body" } else { "body" },
        precedence = d.precedence,
        group = d.group,
        selector = format!("{}{}", rendered_selector(d), d.bucket.as_ref().map(Bound::rendered).unwrap_or_default()),
        action = d.rule.render(),
        resource = resource,
        bucket_const = if d.bucket.is_some() {
            "    const BUCKET: Option<BucketParam> = Some(BUCKET);\n"
        } else {
            ""
        },
        bucket = if d.bucket.is_some() { "Some(BUCKET)" } else { "None" },
        shadows_fn = if d.shadows.is_empty() {
            ""
        } else {
            "\n    fn shadows() -> &'static [ShadowingDecl] {\n        SHADOWS\n    }\n"
        },
        evidence = evidence(d),
        order = d.order,
        method = d.method,
        path = d.path,
        alias = d
            .alias
            .as_ref()
            .map_or_else(|| "None".to_owned(), |alias| format!("Some({alias:?})")),
        query = d
            .query
            .map_or_else(|| "None".to_owned(), |(key, value)| format!("Some(({key:?}, {value:?}))")),
        ruled = d
            .ruled
            .as_ref()
            .map_or_else(|| "None".to_owned(), |class| format!("Some({class:?})")),
        subject = if d.rule.about.is_some() { "Some(SUBJECT)" } else { "None" },
        handler = d.handler,
        request_body = d.request_body,
        response_body = d.response_body,
        secret = d.caller_secret,
    );
    out
}

pub(super) fn render_mod(plan: &Plan) -> String {
    let mut out = String::from(LICENSE);
    out.push_str("//! Every generated RustFS admin operation, one module each.\n//!\n");
    out.push_str("//! Responsible for: mounting them. NOT responsible for: any operation's content (its own module) or the\n");
    out.push_str("//! order they are declared in (`crate::table`). Upstream: the generator. Downstream: `crate::table`\n");
    out.push_str("//! and a deployment that registers handlers.\n\n");
    for declared in &plan.declared {
        let _ = writeln!(out, "pub mod {};", declared.stem);
    }
    out
}

/// `crate::table`: the commit, the pending groups, and the three lists, each in its own file so
/// that none grows past the file-size ceiling as the migrated orders grow.
fn render_table_root(plan: &Plan, commit: &str) -> String {
    let mut out = String::from(LICENSE);
    out.push_str("//! The dialect's generated table: the overlay rows, the route records, the pending groups, and the\n");
    out.push_str("//! one list of every operation.\n//!\n");
    out.push_str("//! Responsible for: [`RUSTFS_SOURCE_COMMIT`] and [`PENDING`] here, and the three per-operation lists\n");
    out.push_str("//! in their own files (`overlay`, `routes`, `fold`), each in inventory order. NOT responsible for: the\n");
    out.push_str("//! claims or the assembly (`crate::dialect`), or any operation's declaration (`crate::ops`).\n");
    out.push_str("//! Upstream: the generator and `crate::ops`. Downstream: `crate::dialect`, the tests, and a deployment\n");
    out.push_str("//! that walks every operation.\n\n");
    out.push_str("mod fold;\nmod overlay;\nmod routes;\n\n");
    out.push_str("pub use fold::fold_every_operation;\npub(crate) use overlay::OVERLAY_ROWS;\npub use routes::ROUTES;\n\n");
    out.push_str("use crate::record::PendingGroup;\n\n");
    let _ = writeln!(
        out,
        "/// The RustFS commit the inventory was recorded from.\npub const RUSTFS_SOURCE_COMMIT: &str = {commit:?};\n"
    );
    out.push_str("/// Every registration group RustFS still serves itself, with its route count.\n");
    out.push_str("pub static PENDING: &[PendingGroup] = &[\n");
    for (group, order, routes) in &plan.pending {
        let _ = writeln!(out, "    PendingGroup {{ group: {group:?}, order: {order}, routes: {routes} }},");
    }
    out.push_str("];\n");
    out
}

/// A table file that lists one `ops::<stem>::<ITEM>` per operation.
fn render_list(plan: &Plan, doc: &str, header: &str, item: &str) -> String {
    let mut out = String::from(LICENSE);
    out.push_str(doc);
    out.push('\n');
    out.push_str(header);
    for d in &plan.declared {
        let _ = writeln!(out, "    ops::{}::{item},", d.stem);
    }
    out.push_str("];\n");
    out
}

fn render_fold(plan: &Plan) -> String {
    let mut out = String::from(LICENSE);
    out.push_str("//! Every generated operation in one generic walk.\n//!\n");
    out.push_str("//! Responsible for: [`fold_every_operation`], in inventory order. NOT responsible for: what a step does\n");
    out.push_str("//! (the caller's `OperationFold`). Upstream: `crate::ops`. Downstream: `crate::dialect` and a deployment\n");
    out.push_str("//! that registers a handler for every operation.\n\n");
    out.push_str("use crate::admin::OperationFold;\nuse crate::ops;\n\n");
    out.push_str("/// Takes `fold`'s step for every operation in turn, in [`crate::ROUTES`] order.\n");
    out.push_str("pub fn fold_every_operation<F: OperationFold>(fold: &mut F, carry: F::Carry) -> F::Carry {\n");
    let count = plan.declared.len();
    for (index, d) in plan.declared.iter().enumerate() {
        if index + 1 == count {
            let _ = writeln!(out, "    fold.step::<ops::{}::{}>(carry)", d.stem, d.type_name);
        } else {
            let _ = writeln!(out, "    let carry = fold.step::<ops::{}::{}>(carry);", d.stem, d.type_name);
        }
    }
    if count == 0 {
        out.push_str("    let _ = fold;\n    carry\n");
    }
    out.push_str("}\n");
    out
}

/// The table's files, by path under the output directory.
pub(super) fn render_tables(plan: &Plan, commit: &str) -> [(&'static str, String); 4] {
    [
        ("table.rs", render_table_root(plan, commit)),
        (
            "table/overlay.rs",
            render_list(
                plan,
                "//! Every generated operation's overlay row.\n//!\n\
                 //! Responsible for: [`OVERLAY_ROWS`], in inventory order. NOT responsible for: any row's content\n\
                 //! (its operation's module). Upstream: `crate::ops`. Downstream: `crate::dialect`'s overlay.\n",
                "use rustfs_gateway_core::dialect::OverlayRow;\n\nuse crate::ops;\n\n\
                 /// Every operation's record, as the overlay reviews it.\npub(crate) static OVERLAY_ROWS: &[OverlayRow] = &[\n",
                "OVERLAY_ROW",
            ),
        ),
        (
            "table/routes.rs",
            render_list(
                plan,
                "//! Every generated operation's route record.\n//!\n\
                 //! Responsible for: [`ROUTES`], in inventory order. NOT responsible for: any record's content (its\n\
                 //! operation's module). Upstream: `crate::ops`. Downstream: the tests and a deployment's report.\n",
                "use crate::ops;\nuse crate::record::RouteRecord;\n\n\
                 /// Every declared operation and the inventory row it was generated from, in inventory order.\n\
                 pub static ROUTES: &[RouteRecord] = &[\n",
                "RECORD",
            ),
        ),
        ("table/fold.rs", render_fold(plan)),
    ]
}
