// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Runtime-contract emission for bucket-CORS policies.
//!
//! Responsible for: mapping typed CORS values to core constants. NOT responsible for: other
//! contract families or file output. Upstream: model CORS contract rules. Downstream: the core
//! generated contract module.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use rustfs_gateway_model::*;

use super::{unique, wrong_type};

macro_rules! emit_policy {
    ($rules:expr, $out:expr, $dimension:ident, $variant:ident, $value_ty:ident, $current:ident, $mutant:ident, $constant:literal, $runtime_ty:literal) => {{
        let value = match unique($rules, MutationDimension::$dimension)? {
            ContractValue::Cors(CorsContractValue::$variant($value_ty::$current)) => {
                concat!($runtime_ty, "::", stringify!($current))
            }
            ContractValue::Cors(CorsContractValue::$variant($value_ty::$mutant)) => {
                concat!($runtime_ty, "::", stringify!($mutant))
            }
            _ => return Err(wrong_type(MutationDimension::$dimension)),
        };
        writeln!(
            $out,
            "/// Current bucket-CORS contract input.\npub(crate) const {}: {} = {};",
            $constant, $runtime_ty, value
        )
        .expect("writing to String cannot fail");
    }};
}

pub(super) fn render(rules: &BTreeMap<String, ContractRule>, out: &mut String) -> std::result::Result<(), String> {
    emit_policy!(
        rules,
        out,
        CorsAllowedMethodValueSet,
        AllowedMethodValueSet,
        AllowedMethodValueSetValue,
        S3Five,
        IncludePatch,
        "CORS_ALLOWED_METHOD_VALUE_SET",
        "AllowedMethodValueSetPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsAllowedMethodCasePolicy,
        AllowedMethodCasePolicy,
        AllowedMethodCasePolicyValue,
        Exact,
        AsciiInsensitive,
        "CORS_ALLOWED_METHOD_CASE_POLICY",
        "AllowedMethodCasePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsOriginWildcardLimit,
        OriginWildcardLimit,
        OriginWildcardLimitValue,
        One,
        Two,
        "CORS_ORIGIN_WILDCARD_LIMIT",
        "OriginWildcardLimitPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsAllowedHeaderWildcardLimit,
        AllowedHeaderWildcardLimit,
        AllowedHeaderWildcardLimitValue,
        One,
        Two,
        "CORS_ALLOWED_HEADER_WILDCARD_LIMIT",
        "AllowedHeaderWildcardLimitPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsExposeHeaderWildcardLimit,
        ExposeHeaderWildcardLimit,
        ExposeHeaderWildcardLimitValue,
        None,
        One,
        "CORS_EXPOSE_HEADER_WILDCARD_LIMIT",
        "ExposeHeaderWildcardLimitPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsDeleteAbsentPolicy,
        DeleteAbsentPolicy,
        CorsDeleteAbsentPolicyValue,
        Succeed,
        NotFound,
        "CORS_DELETE_ABSENT_POLICY",
        "CorsDeleteAbsentPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightDispatchPolicy,
        PreflightDispatchPolicy,
        PreflightDispatchPolicyValue,
        BypassPipeline,
        Route,
        "CORS_PREFLIGHT_DISPATCH_POLICY",
        "PreflightDispatchPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightBucketSource,
        PreflightBucketSource,
        PreflightBucketSourceValue,
        ResolvedTarget,
        RawPath,
        "CORS_PREFLIGHT_BUCKET_SOURCE",
        "PreflightBucketSourcePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightAllowMethodsSource,
        PreflightAllowMethodsSource,
        PreflightAllowMethodsSourceValue,
        MatchedRule,
        RequestedOnly,
        "CORS_PREFLIGHT_ALLOW_METHODS_SOURCE",
        "PreflightAllowMethodsSourcePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightMaxAgePolicy,
        PreflightMaxAgePolicy,
        PreflightMaxAgePolicyValue,
        Include,
        Omit,
        "CORS_PREFLIGHT_MAX_AGE_POLICY",
        "PreflightMaxAgePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightExposePolicy,
        PreflightExposePolicy,
        PreflightExposePolicyValue,
        Include,
        Omit,
        "CORS_PREFLIGHT_EXPOSE_POLICY",
        "PreflightExposePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightVaryPolicy,
        PreflightVaryPolicy,
        PreflightVaryPolicyValue,
        Origin,
        Omit,
        "CORS_PREFLIGHT_VARY_POLICY",
        "PreflightVaryPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsBareWildcardAnswer,
        BareWildcardAnswer,
        BareWildcardAnswerValue,
        LiteralStar,
        ReflectOrigin,
        "CORS_BARE_WILDCARD_ANSWER",
        "BareWildcardAnswerPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPartialWildcardAnswer,
        PartialWildcardAnswer,
        PartialWildcardAnswerValue,
        ReflectOrigin,
        LiteralStar,
        "CORS_PARTIAL_WILDCARD_ANSWER",
        "PartialWildcardAnswerPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsWildcardCredentialsPolicy,
        WildcardCredentialsPolicy,
        WildcardCredentialsPolicyValue,
        Omit,
        Allow,
        "CORS_WILDCARD_CREDENTIALS_POLICY",
        "WildcardCredentialsPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsExactOriginMatch,
        ExactOriginMatch,
        ExactOriginMatchValue,
        Exact,
        AllowAny,
        "CORS_EXACT_ORIGIN_MATCH",
        "ExactOriginMatchPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsOriginWildcardMatch,
        OriginWildcardMatch,
        OriginWildcardMatchValue,
        PrefixAndSuffix,
        SuffixOnly,
        "CORS_ORIGIN_WILDCARD_MATCH",
        "OriginWildcardMatchPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsActualAllowOriginPolicy,
        ActualAllowOriginPolicy,
        ActualAllowOriginPolicyValue,
        Include,
        Omit,
        "CORS_ACTUAL_ALLOW_ORIGIN_POLICY",
        "ActualAllowOriginPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsActualExposePolicy,
        ActualExposePolicy,
        ActualExposePolicyValue,
        Include,
        Omit,
        "CORS_ACTUAL_EXPOSE_POLICY",
        "ActualExposePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsActualVaryPolicy,
        ActualVaryPolicy,
        ActualVaryPolicyValue,
        Origin,
        Omit,
        "CORS_ACTUAL_VARY_POLICY",
        "ActualVaryPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsActualPreflightHeaderPolicy,
        ActualPreflightHeaderPolicy,
        ActualPreflightHeaderPolicyValue,
        Omit,
        Include,
        "CORS_ACTUAL_PREFLIGHT_HEADER_POLICY",
        "ActualPreflightHeaderPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsUnmatchedActualPolicy,
        UnmatchedActualPolicy,
        UnmatchedActualPolicyValue,
        ServeWithoutCors,
        Decorate,
        "CORS_UNMATCHED_ACTUAL_POLICY",
        "UnmatchedActualPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRequestedHeaderCasePolicy,
        RequestedHeaderCasePolicy,
        RequestedHeaderCasePolicyValue,
        AsciiInsensitive,
        Sensitive,
        "CORS_REQUESTED_HEADER_CASE_POLICY",
        "RequestedHeaderCasePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRequestedHeaderWildcardMatch,
        RequestedHeaderWildcardMatch,
        RequestedHeaderWildcardMatchValue,
        PrefixAndSuffix,
        Literal,
        "CORS_REQUESTED_HEADER_WILDCARD_MATCH",
        "RequestedHeaderWildcardMatchPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRequestedHeaderQuantifier,
        RequestedHeaderQuantifier,
        RequestedHeaderQuantifierValue,
        All,
        Any,
        "CORS_REQUESTED_HEADER_QUANTIFIER",
        "RequestedHeaderQuantifierPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsAllowHeadersAnswerSource,
        AllowHeadersAnswerSource,
        AllowHeadersAnswerSourceValue,
        RequestedHeaders,
        StoredPatterns,
        "CORS_ALLOW_HEADERS_ANSWER_SOURCE",
        "AllowHeadersAnswerSourcePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRuleOrderPolicy,
        RuleOrderPolicy,
        CorsRuleOrderPolicyValue,
        FirstMatching,
        LastMatching,
        "CORS_RULE_ORDER_POLICY",
        "CorsRuleOrderPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRuleDimensionJoin,
        RuleDimensionJoin,
        CorsRuleDimensionJoinValue,
        SameRule,
        CrossRule,
        "CORS_RULE_DIMENSION_JOIN",
        "CorsRuleDimensionJoinPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsMatchedRuleValueSource,
        MatchedRuleValueSource,
        CorsMatchedRuleValueSourceValue,
        Winner,
        FirstRule,
        "CORS_MATCHED_RULE_VALUE_SOURCE",
        "CorsMatchedRuleValueSourcePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsHeadersOnPostAuthError,
        HeadersOnPostAuthError,
        HeadersOnPostAuthErrorValue,
        Include,
        SuccessOnly,
        "CORS_HEADERS_ON_POST_AUTH_ERROR",
        "HeadersOnPostAuthErrorPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightRefusalProfile,
        PreflightRefusalProfile,
        PreflightRefusalProfileValue,
        Uniform,
        CauseSpecific,
        "CORS_PREFLIGHT_REFUSAL_PROFILE",
        "PreflightRefusalProfilePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsSourceAbsencePolicy,
        SourceAbsencePolicy,
        CorsSourceAbsencePolicyValue,
        Collapse,
        Distinguish,
        "CORS_SOURCE_ABSENCE_POLICY",
        "CorsSourceAbsencePolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsInvalidTargetPolicy,
        InvalidTargetPolicy,
        CorsInvalidTargetPolicyValue,
        UniformRefusal,
        Route,
        "CORS_INVALID_TARGET_POLICY",
        "CorsInvalidTargetPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsOriginCharacterPolicy,
        OriginCharacterPolicy,
        CorsOriginCharacterPolicyValue,
        VisibleAscii,
        AllowSpaces,
        "CORS_ORIGIN_CHARACTER_POLICY",
        "CorsOriginCharacterPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsOriginEmptyPolicy,
        OriginEmptyPolicy,
        CorsOriginEmptyPolicyValue,
        Reject,
        Allow,
        "CORS_ORIGIN_EMPTY_POLICY",
        "CorsOriginEmptyPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsOriginMaxBytes,
        OriginMaxBytes,
        CorsOriginMaxBytesValue,
        Max2048,
        Unbounded,
        "CORS_ORIGIN_MAX_BYTES",
        "CorsOriginMaxBytesPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsOriginCardinality,
        OriginCardinality,
        CorsOriginCardinalityValue,
        ExactlyOne,
        First,
        "CORS_ORIGIN_CARDINALITY",
        "CorsOriginCardinalityPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRequestMethodCardinality,
        RequestMethodCardinality,
        CorsRequestMethodCardinalityValue,
        ExactlyOne,
        First,
        "CORS_REQUEST_METHOD_CARDINALITY",
        "CorsRequestMethodCardinalityPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsRequestHeadersCardinality,
        RequestHeadersCardinality,
        CorsRequestHeadersCardinalityValue,
        AtMostOne,
        First,
        "CORS_REQUEST_HEADERS_CARDINALITY",
        "CorsRequestHeadersCardinalityPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsBareOptionsPolicy,
        BareOptionsPolicy,
        BareOptionsPolicyValue,
        Route,
        Refuse,
        "CORS_BARE_OPTIONS_POLICY",
        "CorsBareOptionsPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightRequiredHeaderPair,
        PreflightRequiredHeaderPair,
        PreflightRequiredHeaderPairValue,
        Both,
        Either,
        "CORS_PREFLIGHT_REQUIRED_HEADER_PAIR",
        "PreflightRequiredHeaderPairPolicy"
    );
    emit_policy!(
        rules,
        out,
        CorsPreflightAuthorizationScope,
        PreflightAuthorizationScope,
        PreflightAuthorizationScopeValue,
        NoGrant,
        Grant,
        "CORS_PREFLIGHT_AUTHORIZATION_SCOPE",
        "PreflightAuthorizationScopePolicy"
    );
    Ok(())
}
