[package]
name = "xtask"
description = "Repository automation entry point"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
s3gate-codegen = { workspace = true }
s3gate-model = { workspace = true }

[lints]
workspace = true
