[package]
name = "xtask"
description = "Repository automation entry point"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = ["full"]
full = [
    "dep:http",
    "dep:rustfs-gateway",
    "dep:rustfs-gateway-conformance",
    "dep:rustfs-gateway-core",
    "ir-validation",
]
ir-validation = ["dep:jsonschema"]

[dependencies]
command-group.workspace = true
jsonschema = { workspace = true, optional = true }
rustfs-gateway = { workspace = true, optional = true }
rustfs-gateway-codegen = { workspace = true }
rustfs-gateway-conformance = { workspace = true, optional = true }
rustfs-gateway-core = { workspace = true, optional = true }
rustfs-gateway-model = { workspace = true }
http = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
signal-hook.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
