// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Signed production-service evidence for durable `x-amz-meta-*` persistence.
//!
//! Responsible for: metadata surviving a restart on `GET` and `HEAD`, the initiation-time metadata
//! a multipart completion publishes, the size and storability refusals, and the named diagnoses a
//! truncated or unrecognised persisted metadata section answers with — including the record a
//! build predating the section wrote.
//! NOT responsible for: acceptance-time header rules, which `rustfs-gateway-http` owns, or the
//! wire encoding of a returned value, which the generated codec owns.
//! Upstream: the shared CRUD service fixture. Downstream: the crate verification gate.

use super::*;

/// The version record a build predating the metadata section wrote, captured from a real `PUT`.
///
/// Generated by running this crate's own `PutObject` handler at `rustfs/gateway@b0d650dd` — the
/// commit this branch is based on, whose `encode_version_record` emitted a fixed eight lines — and
/// copying the resulting version directory out of the backend root verbatim. It is a real record
/// rather than a hand-written approximation of one, which matters because the whole claim under
/// test is that this build reads what that build wrote.
const V0_FIXTURE: &str = "tests/fixtures/version-record-v0";

fn fixture_path(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(V0_FIXTURE).join(name)
}

fn bucket_path(root: &TestRoot, bucket: &str) -> std::path::PathBuf {
    root.0.join(format!("b-{}", hex::encode(bucket)))
}

/// Copies the captured pre-section version directory into a freshly created bucket.
fn install_v0_fixture(root: &TestRoot, bucket: &str) {
    let name = std::fs::read_to_string(fixture_path("directory-name")).expect("the fixture directory name");
    let destination = bucket_path(root, bucket).join("versions").join(name.trim());
    std::fs::create_dir(&destination).expect("a fresh version directory");
    std::fs::copy(fixture_path("record"), destination.join("record")).expect("the fixture record");
    std::fs::copy(fixture_path("body"), destination.join("body")).expect("the fixture body");
    std::fs::copy(fixture_path("version-sequence"), bucket_path(root, bucket).join("version-sequence"))
        .expect("the fixture sequence");
}

/// The one version directory a single-object bucket holds.
fn only_version_directory(root: &TestRoot, bucket: &str) -> std::path::PathBuf {
    let mut entries = std::fs::read_dir(bucket_path(root, bucket).join("versions"))
        .expect("a readable version directory")
        .flatten()
        .map(|entry| entry.path())
        .collect::<Vec<_>>();
    assert_eq!(entries.len(), 1, "the fixture bucket holds exactly one version");
    entries.pop().expect("one version directory")
}

fn read_record(path: &std::path::Path) -> String {
    std::fs::read_to_string(path.join("record")).expect("a readable version record")
}

fn write_record(path: &std::path::Path, contents: &str) {
    std::fs::write(path.join("record"), contents).expect("the exact record is rewritable");
}

fn meta_headers(headers: http::HeaderMap, pairs: &[(&str, &str)]) -> http::HeaderMap {
    let mut headers = headers;
    for (name, value) in pairs {
        headers.insert(
            http::HeaderName::from_bytes(format!("x-amz-meta-{name}").as_bytes()).expect("a metadata header name"),
            http::HeaderValue::from_str(value).expect("a metadata header value"),
        );
    }
    headers
}

async fn put_with_metadata(
    service: &S3Service,
    bucket: &str,
    key: &str,
    body: &'static [u8],
    pairs: &[(&str, &str)],
) -> rustfs_gateway::WireResponse {
    exchange(
        service,
        signed_with_headers(
            http::Method::PUT,
            &format!("/{bucket}/{key}"),
            Bytes::from_static(body),
            meta_headers(http::HeaderMap::new(), pairs),
        ),
    )
    .await
}

async fn get(service: &S3Service, bucket: &str, key: &str) -> rustfs_gateway::WireResponse {
    exchange(service, signed(http::Method::GET, &format!("/{bucket}/{key}"), Bytes::new())).await
}

async fn head(service: &S3Service, bucket: &str, key: &str) -> rustfs_gateway::WireResponse {
    exchange(service, signed(http::Method::HEAD, &format!("/{bucket}/{key}"), Bytes::new())).await
}

/// Every `x-amz-meta-*` header on a response, in name order.
fn returned_metadata(response: &rustfs_gateway::WireResponse) -> Vec<(String, String)> {
    let mut pairs = response
        .headers()
        .iter()
        .filter_map(|(name, value)| {
            name.as_str()
                .strip_prefix("x-amz-meta-")
                .map(|suffix| (suffix.to_owned(), String::from_utf8_lossy(value.as_bytes()).into_owned()))
        })
        .collect::<Vec<_>>();
    pairs.sort();
    pairs
}

async fn initiate_with_metadata(service: &S3Service, bucket: &str, key: &str, pairs: &[(&str, &str)]) -> String {
    let response = exchange(
        service,
        signed_with_headers(
            http::Method::POST,
            &format!("/{bucket}/{key}?uploads"),
            Bytes::new(),
            meta_headers(http::HeaderMap::new(), pairs),
        ),
    )
    .await;
    assert_eq!(response.status(), 200, "{}", String::from_utf8_lossy(response.body()));
    element(response.body(), "UploadId").expect("an upload id")
}

/// Positive — stored metadata survives a restart and is answered by both `GET` and `HEAD`.
#[tokio::test]
async fn metadata_survives_a_restart_on_get_and_head() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "meta").await;
    assert_eq!(
        put_with_metadata(&running, "meta", "report.txt", b"stamped", &[("mtime", "1767323045.5")])
            .await
            .status(),
        200
    );
    drop(running);

    let (_, reopened) = service(&root);
    let read = get(&reopened, "meta", "report.txt").await;
    assert_eq!(read.status(), 200);
    assert_eq!(read.body().as_ref(), b"stamped");
    assert_eq!(returned_metadata(&read), [("mtime".to_owned(), "1767323045.5".to_owned())]);
    let described = head(&reopened, "meta", "report.txt").await;
    assert_eq!(described.status(), 200);
    assert_eq!(returned_metadata(&described), returned_metadata(&read));
}

/// Positive — a header name's case is the codec's answer, and the stored key is its lowercase form.
#[tokio::test]
async fn a_metadata_key_is_stored_and_returned_lowercased() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "cased").await;
    assert_eq!(
        put_with_metadata(&running, "cased", "report.txt", b"cased", &[("MTime", "9")])
            .await
            .status(),
        200
    );
    let record = read_record(&only_version_directory(&root, "cased"));
    assert!(
        record.contains(&format!("{} 39\n", hex::encode("mtime"))),
        "the record stores the lowercase key: {record}"
    );
    assert_eq!(
        returned_metadata(&get(&running, "cased", "report.txt").await),
        [("mtime".to_owned(), "9".to_owned())]
    );
}

/// Positive — a non-ASCII value is stored decoded and returned as an RFC 2047 encoded word.
#[tokio::test]
async fn a_non_ascii_value_is_stored_decoded_and_returned_encoded() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "unicode").await;
    assert_eq!(
        put_with_metadata(&running, "unicode", "report.txt", b"named", &[("owner", "aurélie")])
            .await
            .status(),
        200
    );
    let record = read_record(&only_version_directory(&root, "unicode"));
    assert!(
        record.contains(&hex::encode("aurélie")),
        "the record stores the decoded Unicode value: {record}"
    );
    drop(running);

    let (_, reopened) = service(&root);
    let returned = returned_metadata(&get(&reopened, "unicode", "report.txt").await);
    let [(name, value)] = returned.as_slice() else {
        panic!("exactly one metadata header, got {returned:?}");
    };
    assert_eq!(name, "owner");
    assert_ne!(value, "aurélie", "a non-ASCII value must not be written into a header field raw");
    assert!(value.starts_with("=?UTF-8?B?") && value.ends_with("?="), "{value}");
}

/// Positive — a multipart object carries the metadata its *initiation* named, across a restart.
///
/// The completion sends its own `x-amz-meta-*` headers and they change nothing: S3 binds the
/// metadata to `CreateMultipartUpload` (`q-mpu-metadata-0039`), and `CompleteMultipartUpload`
/// declares no metadata input at all, so the only way to lose it is to drop it at initiation.
#[tokio::test]
async fn a_completed_upload_publishes_the_metadata_its_initiation_carried() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "assembled").await;
    let upload = initiate_with_metadata(&running, "assembled", "part.txt", &[("mtime", "1767323045.5")]).await;
    let entity_tag = upload_part(&running, "assembled", "part.txt", &upload, 1, b"assembled bytes").await;
    drop(running);

    let (_, reopened) = service(&root);
    let completion = exchange(
        &reopened,
        signed_with_headers(
            http::Method::POST,
            &format!("/assembled/part.txt?uploadId={upload}"),
            completion(&[(1, &entity_tag)]),
            meta_headers(http::HeaderMap::new(), &[("mtime", "0")]),
        ),
    )
    .await;
    assert_eq!(completion.status(), 200, "{}", String::from_utf8_lossy(completion.body()));
    assert_eq!(
        returned_metadata(&get(&reopened, "assembled", "part.txt").await),
        [("mtime".to_owned(), "1767323045.5".to_owned())],
        "the completion's own headers must not replace the initiation's metadata"
    );
}

/// Positive — a record written before the metadata section existed still reads, with no metadata.
#[tokio::test]
async fn a_record_written_before_the_metadata_section_still_reads() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "legacy").await;
    drop(running);
    install_v0_fixture(&root, "legacy");

    let (_, reopened) = service(&root);
    let read = get(&reopened, "legacy", "report.txt").await;
    assert_eq!(read.status(), 200, "{}", String::from_utf8_lossy(read.body()));
    assert_eq!(read.body().as_ref(), b"legacy bytes");
    assert_eq!(returned_metadata(&read), []);
    assert_eq!(read_record(&only_version_directory(&root, "legacy")).lines().count(), 8);
}

/// Positive — an object stored without metadata is written in that same eight-line form.
///
/// This is the other half of the compatibility promise: a build that predates the section refuses
/// any ninth line, so the only records it can still read are the ones this build writes when there
/// is no metadata to carry. A record that does carry metadata is refused by that older reader
/// rather than read as an object with none.
#[tokio::test]
async fn an_object_without_metadata_is_written_in_the_pre_section_form() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "plain").await;
    assert_eq!(
        put_with_metadata(&running, "plain", "report.txt", b"plain", &[])
            .await
            .status(),
        200
    );
    let bare = read_record(&only_version_directory(&root, "plain"));
    assert_eq!(bare.lines().count(), 8, "{bare}");
    assert!(!bare.contains("meta/"), "{bare}");

    create_bucket(&running, "stamped").await;
    assert_eq!(
        put_with_metadata(&running, "stamped", "report.txt", b"plain", &[("mtime", "9")])
            .await
            .status(),
        200
    );
    let stamped = read_record(&only_version_directory(&root, "stamped"));
    assert_eq!(stamped.lines().count(), 10, "{stamped}");
    assert_eq!(stamped.lines().nth(8), Some("meta/1 1"), "{stamped}");
}

/// Negative — a persisted section this build does not understand fails the read closed.
#[tokio::test]
async fn an_unrecognised_persisted_section_fails_the_read_closed() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "future").await;
    assert_eq!(
        put_with_metadata(&running, "future", "report.txt", b"stamped", &[("mtime", "9")])
            .await
            .status(),
        200
    );
    drop(running);
    let directory = only_version_directory(&root, "future");
    let rewritten = read_record(&directory).replace("meta/1 1", "meta/2 1");
    write_record(&directory, &rewritten);

    let (_, reopened) = service(&root);
    let read = get(&reopened, "future", "report.txt").await;
    assert_eq!(read.status(), 500, "{}", String::from_utf8_lossy(read.body()));
    assert_eq!(returned_metadata(&read), []);
    assert_ne!(read.body().as_ref(), b"stamped", "an unreadable record must not still serve its bytes");
    assert_eq!(head(&reopened, "future", "report.txt").await.status(), 500);
}

/// Negative — a section declaring more entries than it holds fails the read closed.
#[tokio::test]
async fn a_truncated_persisted_section_fails_the_read_closed() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "truncated").await;
    assert_eq!(
        put_with_metadata(&running, "truncated", "report.txt", b"stamped", &[("mtime", "9")])
            .await
            .status(),
        200
    );
    drop(running);
    let directory = only_version_directory(&root, "truncated");
    let rewritten = read_record(&directory).replace("meta/1 1", "meta/1 2");
    write_record(&directory, &rewritten);

    let (_, reopened) = service(&root);
    let read = get(&reopened, "truncated", "report.txt").await;
    assert_eq!(read.status(), 500, "{}", String::from_utf8_lossy(read.body()));
    assert_eq!(returned_metadata(&read), []);
    assert_ne!(read.body().as_ref(), b"stamped");
}

/// Negative — a record cut off inside a metadata entry fails closed rather than reading short.
///
/// The bytes stop mid-value, so the entry's hex is an odd number of digits. Nothing about the
/// object's own eight lines is wrong, which is the point: only the section decoder can catch this,
/// and a lenient hex read would hand back a truncated value as though it were the stored one.
#[tokio::test]
async fn a_record_truncated_inside_a_metadata_entry_fails_the_read_closed() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "cut").await;
    assert_eq!(
        put_with_metadata(&running, "cut", "report.txt", b"stamped", &[("mtime", "1767323045")])
            .await
            .status(),
        200
    );
    drop(running);
    let directory = only_version_directory(&root, "cut");
    let record = read_record(&directory);
    let cut = record.len().saturating_sub(2);
    write_record(&directory, record.get(..cut).expect("a record longer than two bytes"));

    let (_, reopened) = service(&root);
    let read = get(&reopened, "cut", "report.txt").await;
    assert_eq!(read.status(), 500, "{}", String::from_utf8_lossy(read.body()));
    assert_eq!(returned_metadata(&read), []);
    assert_ne!(read.body().as_ref(), b"stamped");
}

/// Negative — a record naming a storage class this build cannot resolve fails the read closed.
///
/// The metadata section sits behind the storage-class line, so a lenient reading of that line is
/// also a lenient reading of everything after it. This is the guard that the fixed eight lines
/// still decide the record after the section was appended to them.
#[tokio::test]
async fn a_record_naming_an_unknown_storage_class_fails_the_read_closed() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "tiered").await;
    assert_eq!(
        put_with_metadata(&running, "tiered", "report.txt", b"stamped", &[("mtime", "9")])
            .await
            .status(),
        200
    );
    drop(running);
    let directory = only_version_directory(&root, "tiered");
    let rewritten = read_record(&directory).replace(&hex::encode("STANDARD"), &hex::encode("MOONBASE"));
    write_record(&directory, &rewritten);

    let (_, reopened) = service(&root);
    let read = get(&reopened, "tiered", "report.txt").await;
    assert_eq!(read.status(), 500, "{}", String::from_utf8_lossy(read.body()));
    assert_eq!(returned_metadata(&read), []);
}

/// Negative — metadata past the stored ceiling is refused, and no object is published.
#[tokio::test]
async fn oversized_metadata_is_refused_and_stores_nothing() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "oversized").await;
    let value = "v".repeat(2049 - "mtime".len());
    let response = put_with_metadata(&running, "oversized", "report.txt", b"stamped", &[("mtime", &value)]).await;
    assert_eq!(response.status(), 400, "{}", String::from_utf8_lossy(response.body()));
    assert!(
        String::from_utf8_lossy(response.body()).contains("MetadataTooLarge"),
        "{}",
        String::from_utf8_lossy(response.body())
    );
    assert_eq!(get(&running, "oversized", "report.txt").await.status(), 404);
    drop(running);

    let (_, reopened) = service(&root);
    assert_eq!(get(&reopened, "oversized", "report.txt").await.status(), 404);
}

/// Negative — an upload whose initiation metadata is over the ceiling is never initiated.
#[tokio::test]
async fn an_oversized_initiation_never_becomes_an_upload() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "big-init").await;
    let value = "v".repeat(2049 - "mtime".len());
    let response = exchange(
        &running,
        signed_with_headers(
            http::Method::POST,
            "/big-init/part.txt?uploads",
            Bytes::new(),
            meta_headers(http::HeaderMap::new(), &[("mtime", &value)]),
        ),
    )
    .await;
    assert_eq!(response.status(), 400, "{}", String::from_utf8_lossy(response.body()));
    let listed = exchange(&running, signed(http::Method::GET, "/big-init?uploads", Bytes::new())).await;
    assert_eq!(listed.status(), 200);
    assert!(!String::from_utf8_lossy(listed.body()).contains("<Upload>"), "no upload was initiated");
}

/// Negative — a corrupted upload record refuses the completion instead of publishing without it.
///
/// The completion answers `NoSuchUpload` rather than the section's own diagnosis, because
/// `read_upload_record` maps every undecodable record to "this capability does not exist" and
/// predates this section. The diagnosis is not lost: `ListMultipartUploads` reads the same record
/// through the propagating path and fails closed there, which is asserted below so that the two
/// answers stay one decision rather than drifting into a completion that quietly publishes.
#[tokio::test]
async fn a_corrupted_upload_section_refuses_the_completion() {
    let root = TestRoot::new();
    let (_, running) = service(&root);
    create_bucket(&running, "broken-init").await;
    let upload = initiate_with_metadata(&running, "broken-init", "part.txt", &[("mtime", "9")]).await;
    let entity_tag = upload_part(&running, "broken-init", "part.txt", &upload, 1, b"assembled bytes").await;
    drop(running);

    let uploads = bucket_path(&root, "broken-init").join("uploads");
    let directory = std::fs::read_dir(&uploads)
        .expect("a readable upload directory")
        .flatten()
        .map(|entry| entry.path())
        .find(|path| path.is_dir())
        .expect("one upload directory");
    let record = std::fs::read_to_string(directory.join("record")).expect("the upload record");
    std::fs::write(directory.join("record"), record.replace("meta/1 1", "meta/2 1")).expect("a rewritable upload record");

    let (_, reopened) = service(&root);
    let completed = complete(&reopened, "broken-init", "part.txt", &upload, &[(1, &entity_tag)]).await;
    assert_eq!(completed.status(), 404, "{}", String::from_utf8_lossy(completed.body()));
    assert!(
        String::from_utf8_lossy(completed.body()).contains("NoSuchUpload"),
        "{}",
        String::from_utf8_lossy(completed.body())
    );
    assert_eq!(get(&reopened, "broken-init", "part.txt").await.status(), 404);
    let listed = exchange(&reopened, signed(http::Method::GET, "/broken-init?uploads", Bytes::new())).await;
    assert_eq!(listed.status(), 500, "{}", String::from_utf8_lossy(listed.body()));
}

/// Negative — a lifecycle transition rewrites the record and must not drop its metadata.
///
/// The transition is the one code path that re-encodes a record that already exists, so it is the
/// one place where the metadata can be lost without a client ever asking for it: the object keeps
/// its bytes, its entity tag and its version id, and only the metadata quietly disappears.
#[tokio::test]
async fn a_lifecycle_transition_does_not_drop_the_stored_metadata() {
    use super::lifecycle_transitions::{DUE, DUE_MD5, put_policy, transitioning_service};

    let root = TestRoot::new();
    let (_, initial) = service(&root);
    create_bucket(&initial, "cold").await;
    put_policy(&initial, "cold", DUE, DUE_MD5, None).await;
    assert_eq!(
        put_with_metadata(&initial, "cold", "report.txt", b"stamped", &[("mtime", "1767323045.5")])
            .await
            .status(),
        200
    );
    drop(initial);

    let (backend, transitioned) = transitioning_service(&root, SIGNED_AT_SECONDS + 1);
    assert_eq!(backend.transition_lifecycle_once().await.expect("a valid sweep"), 1);
    drop(transitioned);

    let (_, reopened) = service(&root);
    let read = get(&reopened, "cold", "report.txt").await;
    assert_eq!(read.status(), 200, "{}", String::from_utf8_lossy(read.body()));
    assert_eq!(
        header(&read, "x-amz-storage-class"),
        Some(&http::HeaderValue::from_static("STANDARD_IA")),
        "the transition must have happened for this to be evidence"
    );
    assert_eq!(returned_metadata(&read), [("mtime".to_owned(), "1767323045.5".to_owned())]);
}
