// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from ADR-0039. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:AdminFallback`: the authenticated 501 answer for unmatched admin requests.
//!
//! Responsible for: its rows, caller-only authorization, bodyless codec and fixed handler.
//! NOT responsible for: authentication, policy decisions or deployment registration.
//! Upstream: ADR-0039 and the generator. Downstream: the dialect and a registering deployment.

use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{ClaimedRoute, ClaimedRow, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::{HandlerDeadlineClass, OperationSpec};

use rustfs_gateway_core::{DerivedResourceError, Handler, HandlerError, HandlerResult, NoDerived, Req, SubjectRule};
use rustfs_gateway_sig::OperationFloor;

/// The operation name and its vendor authorization label.
pub const NAME: &str = "rustfs:AdminFallback";
/// Exact, trailing-slash and descendant forms under both admin aliases; all methods.
pub static ROWS: &[ClaimedRow] = &[
    ClaimedRow {
        template: "/rustfs/admin",
        selector: &[],
    },
    ClaimedRow {
        template: "/rustfs/admin/",
        selector: &[],
    },
    ClaimedRow {
        template: "/rustfs/admin/{*remainder}",
        selector: &[],
    },
    ClaimedRow {
        template: "/minio/admin",
        selector: &[],
    },
    ClaimedRow {
        template: "/minio/admin/",
        selector: &[],
    },
    ClaimedRow {
        template: "/minio/admin/{*remainder}",
        selector: &[],
    },
];
/// The reviewed placement after the real operations.
pub const ROUTE: ClaimedRoute = ClaimedRoute {
    precedence: 65535,
    rows: ROWS,
    shadows: &[],
    bucket_param: None,
};
/// The independent overlay record for this synthetic operation, not a native inventory row.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 65535,
    selector: "PathTemplate(\"/rustfs/admin\") ∨ PathTemplate(\"/rustfs/admin/\") ∨ PathTemplate(\"/rustfs/admin/{*remainder}\") ∨ PathTemplate(\"/minio/admin\") ∨ PathTemplate(\"/minio/admin/\") ∨ PathTemplate(\"/minio/admin/{*remainder}\")",
    action: "rustfs:AdminFallback about caller",
    resource: ResourceShape::Service,
    success_status: 501,
    anonymous: false,
    evidence: &["https://github.com/rustfs/gateway/blob/main/docs/adr/0039-authenticated-admin-fallbacks.md"],
};

static SPEC: OperationSpec = OperationSpec::builder(NAME, 501, None)
    .handler_deadline_class(HandlerDeadlineClass::Standard)
    .required_params(&[])
    .auth(AuthRequirement::new(NAME, ResourceShape::Service).about_subject(SubjectRule::Caller))
    .build();
static FLOOR: OperationFloor = crate::admin::floor(NAME);

/// The fallback operation and its fixed handler; register this value for this operation type.
///
/// It is deliberately outside `fold_every_operation`, whose handlers serve inventory routes.
/// Both authorization stages run before this handler, and no caller secret is requested.
#[derive(Debug)]
pub struct AdminFallback;

impl Operation for AdminFallback {
    const NAME: &'static str = NAME;
    type Input = ();
    type Output = ();
    type DerivedResources = NoDerived;
    fn derive_resources(_input: &Self::Input) -> Result<NoDerived, DerivedResourceError> {
        Ok(NoDerived)
    }
    fn seal_derived_input(_input: &mut Self::Input) {}
    fn spec() -> &'static OperationSpec {
        &SPEC
    }
    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for AdminFallback {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::None;
    fn decode(_request: &MetaView<'_>, _body: RequestBody) -> Result<(), CodecError> {
        Ok(())
    }
    fn encode(_output: (), _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        Ok(EncodedResponse::of(status))
    }
}

impl Handler<AdminFallback> for AdminFallback {
    async fn call(&self, _request: Req<AdminFallback>) -> HandlerResult<AdminFallback> {
        Err(HandlerError::not_implemented(
            "A header you provided implies functionality that is not implemented.",
        ))
    }
}
