// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:GetV3UserInfo`: `GET /rustfs/admin/v3/user-info`, registration group `user`.
//!
//! Responsible for: the operation's type, name, rows, action, specification, floor and codec, as the
//! inventory records RustFS's `GetUserInfo` route.
//! NOT responsible for: the handler, which the deployment registers, or the overlay row (`crate::table`).
//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it,
//! and a deployment that registers a handler for [`GetV3UserInfo`].
//!
//! The inventory records this route as custom-auth (`ContextualAuthorization`); its action is ADR-0025's ruling.
//!
//! It acts on the account the `accessKey` query parameter names; an absent or empty one is a `400` before authentication.
//! The facade reads it once, strictly, before authentication, and hands it to both authorizer
//! stages and to the handler as `RequestContextView::subject()`; a handler never reads the query
//! for it (ADR-0025, ADR-0028).
//! RustFS also reads it as `access-key`, so the facade does too: one spelling, once, or a `400` naming
//! `accessKey` (ADR-0029).

use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{ClaimedRow, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::Predicate;
use rustfs_gateway_core::{DerivedResourceError, NoDerived, SubjectRule, WhenAbsent};
use rustfs_gateway_sig::OperationFloor;

use crate::admin::{self, AdminOperation, AdminResponse};
use crate::record::{self, BodyKind, RouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:GetV3UserInfo";

/// Whose account it acts on, which the facade extracts before authentication.
pub const SUBJECT: SubjectRule = SubjectRule::Query {
    param: "accessKey",
    aliases: &["access-key"],
    when_absent: WhenAbsent::Refuse,
};

/// What authorises it, on no bucket.
pub const AUTH: AuthRequirement = AuthRequirement::new("admin:GetUser", ResourceShape::Service).about_subject(SUBJECT);

static SELECTOR: &[Predicate] = &[Predicate::Method(http::Method::GET)];

/// The canonical row, then the MinIO alias RustFS serves it under.
pub static ROWS: &[ClaimedRow] = &[
    ClaimedRow {
        template: "/rustfs/admin/v3/user-info",
        selector: SELECTOR,
    },
    ClaimedRow {
        template: "/minio/admin/v3/user-info",
        selector: SELECTOR,
    },
];

/// `GET /rustfs/admin/v3/user-info`.
#[derive(Debug)]
pub struct GetV3UserInfo;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, false);

/// Privileged and header-signed only: never anonymous, never presigned.
static FLOOR: OperationFloor = admin::floor(NAME);

impl Operation for GetV3UserInfo {
    const NAME: &'static str = NAME;

    /// RustFS reads no request body.
    type Input = ();
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for GetV3UserInfo {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::None;

    fn decode(_request: &MetaView<'_>, _body: RequestBody) -> Result<Self::Input, CodecError> {
        Ok(())
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

impl AdminOperation for GetV3UserInfo {
    const PRECEDENCE: u16 = OVERLAY_ROW.precedence;
    const GROUP: &'static str = RECORD.group;

    fn rows() -> &'static [ClaimedRow] {
        ROWS
    }
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 214,
    selector: "PathTemplate(\"/rustfs/admin/v3/user-info\") ∧ Method(GET) ∨ PathTemplate(\"/minio/admin/v3/user-info\") ∧ Method(GET)",
    action: "admin:GetUser about query(accessKey|access-key, absent=refused)",
    resource: ResourceShape::Service,
    success_status: 200,
    anonymous: false,
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/736e4fb8e8e5d527c25e4e56f352536b311b6daf/rustfs/src/admin/handlers/user.rs",
        record::ADR_0025,
        record::ADR_0028,
        record::ISSUE,
    ],
};

/// The inventory row this operation was generated from.
pub const RECORD: RouteRecord = RouteRecord {
    operation: NAME,
    group: "user",
    order: 4,
    method: "GET",
    path: "/rustfs/admin/v3/user-info",
    alias: Some("/minio/admin/v3/user-info"),
    query: None,
    action: "admin:GetUser about query(accessKey|access-key, absent=refused)",
    ruled: Some("ContextualAuthorization"),
    subject: Some(SUBJECT),
    bucket: None,
    rustfs_handler: "GetUserInfo",
    request_body: BodyKind::NotRead,
    response_body: BodyKind::Buffered,
    caller_secret: false,
};
