// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:GetV4ExtensionsInstances`: `GET /rustfs/admin/v4/extensions/instances`, registration group `extensions`.
//!
//! Responsible for: the operation's type, name, rows, action, specification, floor and codec, as the
//! inventory records RustFS's `ListExtensionInstancesHandler` route.
//! NOT responsible for: the handler, which the deployment registers, or the overlay row (`crate::table`).
//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it,
//! and a deployment that registers a handler for [`GetV4ExtensionsInstances`].

use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{ClaimedRow, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::Predicate;
use rustfs_gateway_core::{DerivedResourceError, NoDerived};
use rustfs_gateway_sig::OperationFloor;

use crate::admin::{self, AdminOperation, AdminResponse};
use crate::record::{self, BodyKind, RouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:GetV4ExtensionsInstances";

/// What authorises it, on no bucket.
pub const AUTH: AuthRequirement = AuthRequirement::new("admin:GetBucketTarget", ResourceShape::Service);

static SELECTOR: &[Predicate] = &[Predicate::Method(http::Method::GET)];

/// The canonical row, then the MinIO alias RustFS serves it under.
pub static ROWS: &[ClaimedRow] = &[
    ClaimedRow {
        template: "/rustfs/admin/v4/extensions/instances",
        selector: SELECTOR,
    },
    ClaimedRow {
        template: "/minio/admin/v4/extensions/instances",
        selector: SELECTOR,
    },
];

/// `GET /rustfs/admin/v4/extensions/instances`.
#[derive(Debug)]
pub struct GetV4ExtensionsInstances;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, false);

/// Privileged and header-signed only: never anonymous, never presigned.
static FLOOR: OperationFloor = admin::floor(NAME);

impl Operation for GetV4ExtensionsInstances {
    const NAME: &'static str = NAME;

    /// RustFS reads no request body.
    type Input = ();
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for GetV4ExtensionsInstances {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::None;

    fn decode(_request: &MetaView<'_>, _body: RequestBody) -> Result<Self::Input, CodecError> {
        Ok(())
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

impl AdminOperation for GetV4ExtensionsInstances {
    const PRECEDENCE: u16 = OVERLAY_ROW.precedence;
    const GROUP: &'static str = RECORD.group;

    fn rows() -> &'static [ClaimedRow] {
        ROWS
    }
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 250,
    selector: "PathTemplate(\"/rustfs/admin/v4/extensions/instances\") ∧ Method(GET) ∨ PathTemplate(\"/minio/admin/v4/extensions/instances\") ∧ Method(GET)",
    action: "admin:GetBucketTarget",
    resource: ResourceShape::Service,
    success_status: 200,
    anonymous: false,
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/736e4fb8e8e5d527c25e4e56f352536b311b6daf/rustfs/src/admin/handlers/extensions.rs",
        record::ISSUE,
    ],
};

/// The inventory row this operation was generated from.
pub const RECORD: RouteRecord = RouteRecord {
    operation: NAME,
    group: "extensions",
    order: 2,
    method: "GET",
    path: "/rustfs/admin/v4/extensions/instances",
    alias: Some("/minio/admin/v4/extensions/instances"),
    query: None,
    action: "admin:GetBucketTarget",
    ruled: None,
    subject: None,
    bucket: None,
    anonymous: false,
    rustfs_handler: "ListExtensionInstancesHandler",
    request_body: BodyKind::NotRead,
    response_body: BodyKind::Buffered,
    caller_secret: false,
};
