// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:GetV3ObjectZipDownloadsByIdZip`: `GET /rustfs/admin/v3/object-zip-downloads/{id}.zip`, registration group `object_zip_download`.
//!
//! Responsible for: the operation's type, name, rows, action, specification, floor and codec, as the
//! inventory records RustFS's `DownloadObjectZipHandler` route.
//! NOT responsible for: the handler, which the deployment registers, or the overlay row (`crate::table`).
//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it,
//! and a deployment that registers a handler for [`GetV3ObjectZipDownloadsByIdZip`].
//!
//! The inventory records this route as custom-auth (`CredentialOnly`); its action is ADR-0025's ruling.
//!
//! It acts only on the caller's own account (`SubjectRule::Caller`): the request cannot name another.
//! RustFS evaluates no IAM action here, so its action is the vendor label `rustfs:DownloadObjectZip`, which the
//! authorizer is still asked (ADR-0025, ADR-0028).
//!
//! RustFS answers this route to whoever presents the `token` query parameter the POST minted, with
//! no signature; the gateway has no bearer scheme on its floor (ADR-0026 (g)), and admitting the
//! route anonymously was refused there, so the floor is privileged: a download URL presented
//! without a header signature is `403` here until that scheme exists (rustfs/backlog#2753). The
//! `{id}.zip` segment is matched as one opaque `{+id}` capture (ADR-0040): the handler reads `id`
//! as the whole segment, suffix included, and validates it against the token.
//!
//! Its path parameter (`id`) names no bucket (ADR-0027): a handler reads each decoded value from
//! `RequestContextView::path_params()`.

use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{ClaimedRow, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::{Predicate, ShadowingDecl};
use rustfs_gateway_core::{DerivedResourceError, NoDerived, SubjectRule};
use rustfs_gateway_sig::OperationFloor;

use crate::admin::{self, AdminOperation, AdminResponse};
use crate::record::{self, BodyKind, RouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:GetV3ObjectZipDownloadsByIdZip";

/// Whose account it acts on, which the facade extracts before authentication.
pub const SUBJECT: SubjectRule = SubjectRule::Caller;

/// What authorises it, on no bucket.
pub const AUTH: AuthRequirement = AuthRequirement::new("rustfs:DownloadObjectZip", ResourceShape::Service).about_subject(SUBJECT);

static SELECTOR: &[Predicate] = &[Predicate::Method(http::Method::GET)];

/// The canonical row, then the MinIO alias RustFS serves it under.
pub static ROWS: &[ClaimedRow] = &[
    ClaimedRow {
        template: "/rustfs/admin/v3/object-zip-downloads/{+id}",
        selector: SELECTOR,
    },
    ClaimedRow {
        template: "/minio/admin/v3/object-zip-downloads/{+id}",
        selector: SELECTOR,
    },
];

/// Reviewed precedence over overlapping templates and authenticated fallbacks.
pub static SHADOWS: &[ShadowingDecl] = &[ShadowingDecl {
    winner: NAME,
    shadowed: "rustfs:AdminFallback",
    reason: "Registered admin routes precede their authenticated fallback.",
    evidence: &["https://github.com/rustfs/gateway/blob/main/docs/adr/0039-authenticated-admin-fallbacks.md"],
}];

/// `GET /rustfs/admin/v3/object-zip-downloads/{id}.zip`.
#[derive(Debug)]
pub struct GetV3ObjectZipDownloadsByIdZip;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, false);

/// Privileged and header-signed only: never anonymous, never presigned.
static FLOOR: OperationFloor = admin::floor(NAME);

impl Operation for GetV3ObjectZipDownloadsByIdZip {
    const NAME: &'static str = NAME;

    /// RustFS reads no request body.
    type Input = ();
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for GetV3ObjectZipDownloadsByIdZip {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::None;

    fn decode(_request: &MetaView<'_>, _body: RequestBody) -> Result<Self::Input, CodecError> {
        Ok(())
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

impl AdminOperation for GetV3ObjectZipDownloadsByIdZip {
    const PRECEDENCE: u16 = OVERLAY_ROW.precedence;
    const GROUP: &'static str = RECORD.group;

    fn rows() -> &'static [ClaimedRow] {
        ROWS
    }

    fn shadows() -> &'static [ShadowingDecl] {
        SHADOWS
    }
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 213,
    selector: "PathTemplate(\"/rustfs/admin/v3/object-zip-downloads/{+id}\") ∧ Method(GET) ∨ PathTemplate(\"/minio/admin/v3/object-zip-downloads/{+id}\") ∧ Method(GET)",
    action: "rustfs:DownloadObjectZip about caller",
    resource: ResourceShape::Service,
    success_status: 200,
    anonymous: false,
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/5e1bd498ce1ca33bcb0ca50aeee861e69e6c8744/rustfs/src/admin/handlers/object_zip_download.rs",
        record::ADR_0025,
        record::ADR_0027,
        record::ADR_0028,
        record::ISSUE,
    ],
};

/// The inventory row this operation was generated from.
pub const RECORD: RouteRecord = RouteRecord {
    operation: NAME,
    group: "object_zip_download",
    order: 7,
    method: "GET",
    path: "/rustfs/admin/v3/object-zip-downloads/{id}.zip",
    alias: Some("/minio/admin/v3/object-zip-downloads/{id}.zip"),
    query: None,
    action: "rustfs:DownloadObjectZip about caller",
    ruled: Some("CredentialOnly"),
    subject: Some(SUBJECT),
    bucket: None,
    anonymous: false,
    rustfs_handler: "DownloadObjectZipHandler",
    request_body: BodyKind::NotRead,
    response_body: BodyKind::Streamed,
    caller_secret: false,
};
