// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:ListenNotification`: `GET /?events=…`, RustFS's `MiscExtRoute::ListenNotification[service]` extension route (rustfs/backlog#2753).
//!
//! Responsible for: the operation's type, name, S3-table row, action, specification, floor and codec, as the
//! inventory records RustFS's `MiscExtRoute::ListenNotification[service]` route.
//! NOT responsible for: the handler, which the deployment registers, or the overlay row's place in the record
//! (`crate::table`).
//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it, and a
//! deployment that registers a handler for [`ListenNotification`].
//!
//! RustFS's admin router claims this S3-shaped request before its S3 service reads anything else,
//! `x-id` included: a `GET` of the service whose query names `events`, with any value, whatever
//! else the query names. It requires a signature and then has the handler check
//! `s3:ListenNotification`. So the row sits ahead of every standard `GET` row of its target and
//! declares each of those overlaps, the floor is privileged, the authorizer is asked
//! `s3:ListenNotification` on no bucket before the handler runs, and the gateway reads no body and
//! answers what the handler answers. Under legacy RustFS's selection the same discriminator names
//! this operation (`rustfs-gateway-core`'s `legacy_rustfs`), so both selections reach it.

use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{DialectRoute, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::{Predicate, ShadowingDecl, TargetKind};
use rustfs_gateway_core::{DerivedResourceError, NoDerived};
use rustfs_gateway_sig::OperationFloor;

use crate::admin::{self, AdminResponse, ExtensionOperation};
use crate::record::{self, ExtensionRouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:ListenNotification";

/// What authorises it, on no bucket: the action RustFS's handler checks.
pub const AUTH: AuthRequirement = AuthRequirement::new("s3:ListenNotification", ResourceShape::Service);

/// RustFS's admin router, whose extension matching this row mirrors.
const ROUTER: &str = "https://github.com/rustfs/rustfs/blob/5e1bd498ce1ca33bcb0ca50aeee861e69e6c8744/rustfs/src/admin/router.rs";

/// Why this row stands in front of every standard row of its method and target.
const CLAIM: &str = "RustFS's admin router claims a GET of the service whose query names `events`, with any value before its S3 service, whatever else the query names.";

/// The row: the method, the target, and the one discriminator RustFS's router reads.
pub static SELECTOR: &[Predicate] = &[
    Predicate::Method(http::Method::GET),
    Predicate::Target(TargetKind::Service),
    Predicate::QueryPresent("events"),
];

/// Every standard row of the same method and target, and every later extension row a request can name
/// together with this one: each a routing decision the placement makes, evidenced by RustFS's router.
pub static SHADOWS: &[ShadowingDecl] = &[
    ShadowingDecl {
        winner: NAME,
        shadowed: "ListDirectoryBuckets",
        reason: CLAIM,
        evidence: &[ROUTER],
    },
    ShadowingDecl {
        winner: NAME,
        shadowed: "ListBuckets",
        reason: CLAIM,
        evidence: &[ROUTER],
    },
];

/// Where the dialect places the row: ahead of every S3 row of its method and target.
pub const ROUTE: DialectRoute = DialectRoute {
    precedence: 86,
    selector: SELECTOR,
    path_shape: "/",
    shadows: SHADOWS,
};

/// `GET /?events=…`.
#[derive(Debug)]
pub struct ListenNotification;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, false);

/// Privileged and header-signed only: never anonymous, never presigned. RustFS answers an unsigned request
/// `403 AccessDenied` here, and no RustFS client is shown to presign an extension route (ADR-0024 (f)).
static FLOOR: OperationFloor = admin::floor(NAME);

impl Operation for ListenNotification {
    const NAME: &'static str = NAME;

    /// RustFS reads no request body: everything it needs is in the path and the query.
    type Input = ();
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for ListenNotification {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::None;

    fn decode(_request: &MetaView<'_>, _body: RequestBody) -> Result<Self::Input, CodecError> {
        Ok(())
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

impl ExtensionOperation for ListenNotification {
    const ROUTE: DialectRoute = ROUTE;
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 86,
    selector: "Method(GET) ∧ Target(Service) ∧ QueryPresent(\"events\")",
    action: "s3:ListenNotification",
    resource: ResourceShape::Service,
    success_status: 200,
    anonymous: false,
    evidence: &[ROUTER, record::EXTENSION_ISSUE, record::ISSUE],
};

/// The inventory row this operation was generated from.
pub const RECORD: ExtensionRouteRecord = ExtensionRouteRecord {
    operation: NAME,
    name: "MiscExtRoute::ListenNotification[service]",
    method: "GET",
    target: "service",
    query: ("events", "present"),
    action: "s3:ListenNotification",
};
