// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:PostV3IntegrityByBucketJobsByJobIdControl`: `POST /rustfs/admin/v3/integrity/{bucket}/jobs/{job_id}/control`, registration group `integrity`.
//!
//! Responsible for: the operation's type, name, rows, action, specification, floor and codec, as the
//! inventory records RustFS's `Handler(Route::Control)` route.
//! NOT responsible for: the handler, which the deployment registers, or the overlay row (`crate::table`).
//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it,
//! and a deployment that registers a handler for [`PostV3IntegrityByBucketJobsByJobIdControl`].
//!
//! Its `{bucket}` parameter is the bucket the operation is authorised on (`BucketParam::Path`,
//! ADR-0025 (c), ADR-0030): the raw segment meets the S3 bucket-name rules before authentication, and
//! the governor, both authorizer stages, the audit event and the handler's `RequestContextView::bucket()`
//! see that bucket and no key. Where RustFS authorises this action on no bucket and reads the segment
//! afterwards, handing the authorizer the bucket is a deliberate tightening.
//!
//! Its other path parameter (`job_id`) names no bucket (ADR-0027): a handler reads each decoded value from
//! `RequestContextView::path_params()`.

use bytes::Bytes;
use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{BucketParam, ClaimedRow, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::Predicate;
use rustfs_gateway_core::{DerivedResourceError, NoDerived};
use rustfs_gateway_sig::OperationFloor;

use crate::admin::{self, AdminOperation, AdminResponse};
use crate::record::{self, BodyKind, RouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:PostV3IntegrityByBucketJobsByJobIdControl";

/// What authorises it, on the bucket its `{bucket}` parameter names.
pub const AUTH: AuthRequirement = AuthRequirement::new("admin:StartBatchJob", ResourceShape::Bucket);

/// The bucket it is authorised on, which the facade reads before authentication.
pub const BUCKET: BucketParam = BucketParam::Path("bucket");

static SELECTOR: &[Predicate] = &[Predicate::Method(http::Method::POST)];

/// The canonical row, then the MinIO alias RustFS serves it under.
pub static ROWS: &[ClaimedRow] = &[
    ClaimedRow {
        template: "/rustfs/admin/v3/integrity/{bucket}/jobs/{job_id}/control",
        selector: SELECTOR,
    },
    ClaimedRow {
        template: "/minio/admin/v3/integrity/{bucket}/jobs/{job_id}/control",
        selector: SELECTOR,
    },
];

/// `POST /rustfs/admin/v3/integrity/{bucket}/jobs/{job_id}/control`.
#[derive(Debug)]
pub struct PostV3IntegrityByBucketJobsByJobIdControl;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, true);

/// Privileged and header-signed only: never anonymous, never presigned.
static FLOOR: OperationFloor = admin::floor(NAME);

impl Operation for PostV3IntegrityByBucketJobsByJobIdControl {
    const NAME: &'static str = NAME;

    /// The body as it arrived, which RustFS buffers and parses.
    type Input = Bytes;
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for PostV3IntegrityByBucketJobsByJobIdControl {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::Full;

    fn decode(_request: &MetaView<'_>, body: RequestBody) -> Result<Self::Input, CodecError> {
        admin::buffered(body)
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

impl AdminOperation for PostV3IntegrityByBucketJobsByJobIdControl {
    const PRECEDENCE: u16 = OVERLAY_ROW.precedence;
    const GROUP: &'static str = RECORD.group;
    const BUCKET: Option<BucketParam> = Some(BUCKET);

    fn rows() -> &'static [ClaimedRow] {
        ROWS
    }
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 302,
    selector: "PathTemplate(\"/rustfs/admin/v3/integrity/{bucket}/jobs/{job_id}/control\") ∧ Method(POST) ∨ PathTemplate(\"/minio/admin/v3/integrity/{bucket}/jobs/{job_id}/control\") ∧ Method(POST) ⇒ BucketParam(\"bucket\")",
    action: "admin:StartBatchJob",
    resource: ResourceShape::Bucket,
    success_status: 200,
    anonymous: false,
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/3268c42e00b375859b4535d53fe219b02d7bfe31/rustfs/src/admin/handlers/integrity.rs",
        record::ADR_0027,
        record::ADR_0030,
        record::ISSUE,
    ],
};

/// The inventory row this operation was generated from.
pub const RECORD: RouteRecord = RouteRecord {
    operation: NAME,
    group: "integrity",
    order: 5,
    method: "POST",
    path: "/rustfs/admin/v3/integrity/{bucket}/jobs/{job_id}/control",
    alias: Some("/minio/admin/v3/integrity/{bucket}/jobs/{job_id}/control"),
    query: None,
    action: "admin:StartBatchJob",
    ruled: None,
    subject: None,
    bucket: Some(BUCKET),
    anonymous: false,
    rustfs_handler: "Handler(Route::Control)",
    request_body: BodyKind::Buffered,
    response_body: BodyKind::Buffered,
    caller_secret: true,
};
