// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:PostV3KmsKeysUntag`: `POST /rustfs/admin/v3/kms/keys/untag`, registration group `kms`.
//!
//! Responsible for: the operation's type, name, rows, action, specification, floor and codec, as the
//! inventory records RustFS's `UntagKmsKeyHandler` route.
//! NOT responsible for: the handler, which the deployment registers, or the overlay row (`crate::table`).
//! Upstream: the recorded inventory and `crate::admin`. Downstream: `crate::table`, which lists it,
//! and a deployment that registers a handler for [`PostV3KmsKeysUntag`].

use bytes::Bytes;
use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{ClaimedRow, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::{Predicate, ShadowingDecl};
use rustfs_gateway_core::{DerivedResourceError, NoDerived};
use rustfs_gateway_sig::OperationFloor;

use crate::admin::{self, AdminOperation, AdminResponse};
use crate::record::{self, BodyKind, RouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:PostV3KmsKeysUntag";

/// What authorises it, on no bucket.
pub const AUTH: AuthRequirement = AuthRequirement::new("kms:UntagResource", ResourceShape::Service);

static SELECTOR: &[Predicate] = &[Predicate::Method(http::Method::POST)];

/// The canonical row, then the MinIO alias RustFS serves it under.
pub static ROWS: &[ClaimedRow] = &[
    ClaimedRow {
        template: "/rustfs/admin/v3/kms/keys/untag",
        selector: SELECTOR,
    },
    ClaimedRow {
        template: "/minio/admin/v3/kms/keys/untag",
        selector: SELECTOR,
    },
];

/// Reviewed precedence over overlapping templates and authenticated fallbacks.
pub static SHADOWS: &[ShadowingDecl] = &[ShadowingDecl {
    winner: NAME,
    shadowed: "rustfs:AdminFallback",
    reason: "Registered admin routes precede their authenticated fallback.",
    evidence: &["https://github.com/rustfs/gateway/blob/main/docs/adr/0039-authenticated-admin-fallbacks.md"],
}];

/// `POST /rustfs/admin/v3/kms/keys/untag`.
#[derive(Debug)]
pub struct PostV3KmsKeysUntag;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, false);

/// Privileged and header-signed only: never anonymous, never presigned.
static FLOOR: OperationFloor = admin::floor(NAME);

impl Operation for PostV3KmsKeysUntag {
    const NAME: &'static str = NAME;

    /// The body as it arrived, which RustFS buffers and parses.
    type Input = Bytes;
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for PostV3KmsKeysUntag {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::Full;

    fn decode(_request: &MetaView<'_>, body: RequestBody) -> Result<Self::Input, CodecError> {
        admin::buffered(body)
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

impl AdminOperation for PostV3KmsKeysUntag {
    const PRECEDENCE: u16 = OVERLAY_ROW.precedence;
    const GROUP: &'static str = RECORD.group;

    fn rows() -> &'static [ClaimedRow] {
        ROWS
    }

    fn shadows() -> &'static [ShadowingDecl] {
        SHADOWS
    }
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 318,
    selector: "PathTemplate(\"/rustfs/admin/v3/kms/keys/untag\") ∧ Method(POST) ∨ PathTemplate(\"/minio/admin/v3/kms/keys/untag\") ∧ Method(POST)",
    action: "kms:UntagResource",
    resource: ResourceShape::Service,
    success_status: 200,
    anonymous: false,
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/5e1bd498ce1ca33bcb0ca50aeee861e69e6c8744/rustfs/src/admin/handlers/kms_key_metadata.rs",
        record::ISSUE,
    ],
};

/// The inventory row this operation was generated from.
pub const RECORD: RouteRecord = RouteRecord {
    operation: NAME,
    group: "kms",
    order: 3,
    method: "POST",
    path: "/rustfs/admin/v3/kms/keys/untag",
    alias: Some("/minio/admin/v3/kms/keys/untag"),
    query: None,
    action: "kms:UntagResource",
    ruled: None,
    subject: None,
    bucket: None,
    anonymous: false,
    rustfs_handler: "UntagKmsKeyHandler",
    request_body: BodyKind::Buffered,
    response_body: BodyKind::Buffered,
    caller_secret: false,
};
