// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! `rustfs:StsFormPost`: `POST /` with an `application/x-www-form-urlencoded` body on every host, registration group `sts`
//! (ADR-0041).
//!
//! Responsible for: the operation's type, name, form claim, action, specification, floor and codec, as the
//! inventory records RustFS's `AssumeRoleHandle` route.
//! NOT responsible for: the handler, which the deployment registers, or matching the claim
//! (`rustfs_gateway_core::route::FormClaim`).
//! Upstream: the recorded inventory, ADR-0041 and `crate::admin`. Downstream: `crate::dialect`, which declares
//! it behind [`CLAIM`], and a deployment that registers a handler for [`StsFormPost`].
//!
//! RustFS's STS endpoint. Its router takes the request before its S3 path parser runs, whatever the host's
//! bucket label and whatever the query, verifies whatever signature it carries (a header signature under any
//! service RustFS accepts, a presigned URL, SigV2), and then lets an unsigned request through as well: the
//! handler reads `Action` from the body, refuses `AssumeRole` without credentials, and authenticates
//! `AssumeRoleWithWebIdentity` by the token in the body. So the operation is reachable anonymously, its action
//! is the vendor label `rustfs:AssumeRoleHandle`, the authorizer is still asked, with no identity, and the body is handed over
//! as it arrived.

use bytes::Bytes;
use rustfs_gateway_core::codec::{CodecError, EncodedResponse, MetaView, OperationCodec, RequestBody, RequestBodyMode};
use rustfs_gateway_core::dialect::{FormRoute, OverlayRow};
use rustfs_gateway_core::op::{AuthRequirement, Operation, ResourceShape};
use rustfs_gateway_core::registry::OperationSpec;
use rustfs_gateway_core::route::FormClaim;
use rustfs_gateway_core::{DerivedResourceError, NoDerived};
use rustfs_gateway_sig::{OperationFloor, SigService};

use crate::admin::{self, AdminResponse};
use crate::record::{self, BodyKind, FormRouteRecord};

/// The operation name.
pub const NAME: &str = "rustfs:StsFormPost";

/// What authorises it, on no bucket: the vendor label of RustFS's handler, which makes no IAM check
/// before it reads the body.
pub const AUTH: AuthRequirement = AuthRequirement::new("rustfs:AssumeRoleHandle", ResourceShape::Service);

/// RustFS's STS predicate: a `POST` of exactly `/` whose first `Content-Type` value names the form media
/// type, on every host and whatever the query.
pub static CLAIM: FormClaim = FormClaim {
    path: "/",
    reason: "RustFS's router takes a form POST of / as its STS endpoint before its S3 path parser runs, on every host and whatever the query.",
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/5e1bd498ce1ca33bcb0ca50aeee861e69e6c8744/rustfs/src/server/layer.rs",
        "https://github.com/rustfs/rustfs/blob/5e1bd498ce1ca33bcb0ca50aeee861e69e6c8744/rustfs/src/admin/router.rs",
    ],
};

/// Where the dialect serves it.
pub const ROUTE: FormRoute = FormRoute {
    precedence: 99,
    claim: &CLAIM,
};

/// `POST /` with a form body.
#[derive(Debug)]
pub struct StsFormPost;

static SPEC: OperationSpec = admin::spec(NAME, AUTH, false);

/// Not privileged, and reachable anonymously by its own opt-in, which the start-up posture report lists: a
/// header signature, a presigned URL where the assembly admits one on a standard operation, SigV2 where the
/// floor admits it, or nothing at all.
///
/// Legacy-compat (rustfs/backlog#2684): legacy RustFS verifies a presigned URL (SigV4 or SigV2) on its STS
/// endpoint and hands the handler its credentials. A presigned URL signs neither the `Content-Type` nor the
/// body, and the claim reads neither host nor query, so any `POST` URL presigned for the path `/` (one for
/// `POST /`, or a virtual-hosted `DeleteObjects` URL, `POST /?delete` on a bucket's host) resent with a form
/// body lets whoever holds it choose the `Action`, the session policy and the duration of the credentials it
/// mints under the signer's identity. Kept so a client that presigns its STS call keeps working; the intended
/// future behaviour is a privileged floor, header signatures only.
static FLOOR: OperationFloor =
    OperationFloor::builtin(NAME, SigService::Sts).allow_anonymous_after_listing_in_the_posture_report();

impl Operation for StsFormPost {
    const NAME: &'static str = NAME;

    /// The form body, as it arrived.
    type Input = Bytes;
    type Output = AdminResponse;
    type DerivedResources = NoDerived;

    fn derive_resources(_input: &Self::Input) -> Result<Self::DerivedResources, DerivedResourceError> {
        Ok(NoDerived)
    }

    fn seal_derived_input(_input: &mut Self::Input) {}

    fn spec() -> &'static OperationSpec {
        &SPEC
    }

    fn floor() -> &'static OperationFloor {
        &FLOOR
    }
}

impl OperationCodec for StsFormPost {
    const REQUEST_BODY: RequestBodyMode = RequestBodyMode::Full;

    fn decode(_request: &MetaView<'_>, body: RequestBody) -> Result<Self::Input, CodecError> {
        admin::buffered(body)
    }

    fn encode(output: Self::Output, _request: &MetaView<'_>, status: u16) -> Result<EncodedResponse, CodecError> {
        admin::encode(output, status)
    }
}

/// This operation's row in the dialect's overlay, as a reviewer reads it.
pub const OVERLAY_ROW: OverlayRow = OverlayRow {
    name: NAME,
    precedence: 99,
    selector: "FormClaim(POST \"/\")",
    action: "rustfs:AssumeRoleHandle",
    resource: ResourceShape::Service,
    success_status: 200,
    anonymous: true,
    evidence: &[
        "https://github.com/rustfs/rustfs/blob/5e1bd498ce1ca33bcb0ca50aeee861e69e6c8744/rustfs/src/admin/handlers/sts.rs",
        "https://github.com/rustfs/gateway/blob/main/docs/adr/0041-form-claims-and-the-rustfs-sts-endpoint.md",
        record::ISSUE,
    ],
};

/// The inventory row this operation was generated from.
pub const RECORD: FormRouteRecord = FormRouteRecord {
    operation: NAME,
    group: "sts",
    method: "POST",
    path: "/",
    action: "rustfs:AssumeRoleHandle",
    rustfs_handler: "AssumeRoleHandle",
    request_body: BodyKind::Buffered,
    response_body: BodyKind::Buffered,
};
