// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! The dialect's generated table: the overlay rows, the route records, the pending groups, and the
//! one list of every operation.
//!
//! Responsible for: [`OVERLAY_ROWS`], [`ROUTES`], [`PENDING`] and [`fold_every_operation`], in inventory
//! order. NOT responsible for: the claims or the assembly (`crate::dialect`), or any operation's
//! declaration (`crate::ops`). Upstream: the generator and `crate::ops`. Downstream: `crate::dialect`,
//! the tests, and a deployment that walks every operation.

use rustfs_gateway_core::dialect::OverlayRow;

use crate::admin::OperationFold;
use crate::ops;
use crate::record::{PendingGroup, RouteRecord};

/// The RustFS commit the inventory was recorded from.
pub const RUSTFS_SOURCE_COMMIT: &str = "736e4fb8e8e5d527c25e4e56f352536b311b6daf";

/// Every operation's record, as the overlay reviews it.
pub(crate) static OVERLAY_ROWS: &[OverlayRow] = &[
    ops::get_debug_pprof_profile::OVERLAY_ROW,
    ops::get_debug_pprof_status::OVERLAY_ROW,
    ops::get_debug_tls_status::OVERLAY_ROW,
    ops::get_export_bucket_metadata::OVERLAY_ROW,
    ops::get_v3_datausageinfo::OVERLAY_ROW,
    ops::get_v3_export_bucket_metadata::OVERLAY_ROW,
    ops::get_v3_gateway_key_inventory::OVERLAY_ROW,
    ops::get_v3_healthinfo::OVERLAY_ROW,
    ops::get_v3_info::OVERLAY_ROW,
    ops::get_v3_inspect_data::OVERLAY_ROW,
    ops::get_v3_log::OVERLAY_ROW,
    ops::get_v3_metrics::OVERLAY_ROW,
    ops::get_v3_module_switches::OVERLAY_ROW,
    ops::get_v3_obdinfo::OVERLAY_ROW,
    ops::get_v3_object_data_cache_stats::OVERLAY_ROW,
    ops::get_v3_profiling_download::OVERLAY_ROW,
    ops::get_v3_rebalance_status::OVERLAY_ROW,
    ops::get_v3_speedtest_client_devnull::OVERLAY_ROW,
    ops::get_v3_storageinfo::OVERLAY_ROW,
    ops::get_v3_top_locks::OVERLAY_ROW,
    ops::get_v3_trace::OVERLAY_ROW,
    ops::get_v4_cluster_snapshot::OVERLAY_ROW,
    ops::get_v4_extensions_catalog::OVERLAY_ROW,
    ops::get_v4_extensions_instances::OVERLAY_ROW,
    ops::get_v4_plugins_catalog::OVERLAY_ROW,
    ops::get_v4_runtime_capabilities::OVERLAY_ROW,
    ops::post_v3_force_unlock::OVERLAY_ROW,
    ops::post_v3_inspect_data::OVERLAY_ROW,
    ops::post_v3_object_data_cache_flush::OVERLAY_ROW,
    ops::post_v3_profile::OVERLAY_ROW,
    ops::post_v3_profiling_start::OVERLAY_ROW,
    ops::post_v3_rebalance_start::OVERLAY_ROW,
    ops::post_v3_rebalance_stop::OVERLAY_ROW,
    ops::post_v3_service_restart::OVERLAY_ROW,
    ops::post_v3_service_stop::OVERLAY_ROW,
    ops::post_v3_service_freeze::OVERLAY_ROW,
    ops::post_v3_service_unfreeze::OVERLAY_ROW,
    ops::post_v3_speedtest::OVERLAY_ROW,
    ops::post_v3_speedtest_client_devnull::OVERLAY_ROW,
    ops::post_v3_speedtest_drive::OVERLAY_ROW,
    ops::post_v3_speedtest_net::OVERLAY_ROW,
    ops::post_v3_speedtest_object::OVERLAY_ROW,
    ops::post_v3_speedtest_site::OVERLAY_ROW,
    ops::post_v3_update::OVERLAY_ROW,
    ops::post_v4_inspect_archive::OVERLAY_ROW,
    ops::put_import_bucket_metadata::OVERLAY_ROW,
    ops::put_v3_import_bucket_metadata::OVERLAY_ROW,
    ops::put_v3_module_switches::OVERLAY_ROW,
];

/// Every declared operation and the inventory row it was generated from, in inventory order.
pub static ROUTES: &[RouteRecord] = &[
    ops::get_debug_pprof_profile::RECORD,
    ops::get_debug_pprof_status::RECORD,
    ops::get_debug_tls_status::RECORD,
    ops::get_export_bucket_metadata::RECORD,
    ops::get_v3_datausageinfo::RECORD,
    ops::get_v3_export_bucket_metadata::RECORD,
    ops::get_v3_gateway_key_inventory::RECORD,
    ops::get_v3_healthinfo::RECORD,
    ops::get_v3_info::RECORD,
    ops::get_v3_inspect_data::RECORD,
    ops::get_v3_log::RECORD,
    ops::get_v3_metrics::RECORD,
    ops::get_v3_module_switches::RECORD,
    ops::get_v3_obdinfo::RECORD,
    ops::get_v3_object_data_cache_stats::RECORD,
    ops::get_v3_profiling_download::RECORD,
    ops::get_v3_rebalance_status::RECORD,
    ops::get_v3_speedtest_client_devnull::RECORD,
    ops::get_v3_storageinfo::RECORD,
    ops::get_v3_top_locks::RECORD,
    ops::get_v3_trace::RECORD,
    ops::get_v4_cluster_snapshot::RECORD,
    ops::get_v4_extensions_catalog::RECORD,
    ops::get_v4_extensions_instances::RECORD,
    ops::get_v4_plugins_catalog::RECORD,
    ops::get_v4_runtime_capabilities::RECORD,
    ops::post_v3_force_unlock::RECORD,
    ops::post_v3_inspect_data::RECORD,
    ops::post_v3_object_data_cache_flush::RECORD,
    ops::post_v3_profile::RECORD,
    ops::post_v3_profiling_start::RECORD,
    ops::post_v3_rebalance_start::RECORD,
    ops::post_v3_rebalance_stop::RECORD,
    ops::post_v3_service_restart::RECORD,
    ops::post_v3_service_stop::RECORD,
    ops::post_v3_service_freeze::RECORD,
    ops::post_v3_service_unfreeze::RECORD,
    ops::post_v3_speedtest::RECORD,
    ops::post_v3_speedtest_client_devnull::RECORD,
    ops::post_v3_speedtest_drive::RECORD,
    ops::post_v3_speedtest_net::RECORD,
    ops::post_v3_speedtest_object::RECORD,
    ops::post_v3_speedtest_site::RECORD,
    ops::post_v3_update::RECORD,
    ops::post_v4_inspect_archive::RECORD,
    ops::put_import_bucket_metadata::RECORD,
    ops::put_v3_import_bucket_metadata::RECORD,
    ops::put_v3_module_switches::RECORD,
];

/// Every registration group RustFS still serves itself, with its route count.
pub static PENDING: &[PendingGroup] = &[
    PendingGroup {
        group: "account",
        order: 4,
        routes: 2,
    },
    PendingGroup {
        group: "audit",
        order: 3,
        routes: 3,
    },
    PendingGroup {
        group: "batch_job",
        order: 3,
        routes: 5,
    },
    PendingGroup {
        group: "config_admin",
        order: 3,
        routes: 9,
    },
    PendingGroup {
        group: "durability_handler",
        order: 5,
        routes: 3,
    },
    PendingGroup {
        group: "heal",
        order: 5,
        routes: 5,
    },
    PendingGroup {
        group: "health",
        order: 8,
        routes: 6,
    },
    PendingGroup {
        group: "idp_compat",
        order: 4,
        routes: 13,
    },
    PendingGroup {
        group: "ilm_transition",
        order: 3,
        routes: 11,
    },
    PendingGroup {
        group: "kms",
        order: 3,
        routes: 35,
    },
    PendingGroup {
        group: "mfa",
        order: 4,
        routes: 8,
    },
    PendingGroup {
        group: "object_zip_download",
        order: 7,
        routes: 2,
    },
    PendingGroup {
        group: "oidc",
        order: 7,
        routes: 8,
    },
    PendingGroup {
        group: "on_demand_migration",
        order: 5,
        routes: 6,
    },
    PendingGroup {
        group: "plugins_instances",
        order: 3,
        routes: 4,
    },
    PendingGroup {
        group: "pools",
        order: 3,
        routes: 6,
    },
    PendingGroup {
        group: "quota_handler",
        order: 5,
        routes: 7,
    },
    PendingGroup {
        group: "replication_handler",
        order: 4,
        routes: 6,
    },
    PendingGroup {
        group: "scanner",
        order: 3,
        routes: 5,
    },
    PendingGroup {
        group: "site_replication",
        order: 3,
        routes: 22,
    },
    PendingGroup {
        group: "sts",
        order: 7,
        routes: 2,
    },
    PendingGroup {
        group: "table_catalog",
        order: 6,
        routes: 98,
    },
    PendingGroup {
        group: "tier",
        order: 3,
        routes: 7,
    },
    PendingGroup {
        group: "usage_prefix",
        order: 5,
        routes: 1,
    },
    PendingGroup {
        group: "user",
        order: 4,
        routes: 37,
    },
];

/// Takes `fold`'s step for every operation in turn, in [`ROUTES`] order.
pub fn fold_every_operation<F: OperationFold>(fold: &mut F, carry: F::Carry) -> F::Carry {
    let carry = fold.step::<ops::get_debug_pprof_profile::GetDebugPprofProfile>(carry);
    let carry = fold.step::<ops::get_debug_pprof_status::GetDebugPprofStatus>(carry);
    let carry = fold.step::<ops::get_debug_tls_status::GetDebugTlsStatus>(carry);
    let carry = fold.step::<ops::get_export_bucket_metadata::GetExportBucketMetadata>(carry);
    let carry = fold.step::<ops::get_v3_datausageinfo::GetV3Datausageinfo>(carry);
    let carry = fold.step::<ops::get_v3_export_bucket_metadata::GetV3ExportBucketMetadata>(carry);
    let carry = fold.step::<ops::get_v3_gateway_key_inventory::GetV3GatewayKeyInventory>(carry);
    let carry = fold.step::<ops::get_v3_healthinfo::GetV3Healthinfo>(carry);
    let carry = fold.step::<ops::get_v3_info::GetV3Info>(carry);
    let carry = fold.step::<ops::get_v3_inspect_data::GetV3InspectData>(carry);
    let carry = fold.step::<ops::get_v3_log::GetV3Log>(carry);
    let carry = fold.step::<ops::get_v3_metrics::GetV3Metrics>(carry);
    let carry = fold.step::<ops::get_v3_module_switches::GetV3ModuleSwitches>(carry);
    let carry = fold.step::<ops::get_v3_obdinfo::GetV3Obdinfo>(carry);
    let carry = fold.step::<ops::get_v3_object_data_cache_stats::GetV3ObjectDataCacheStats>(carry);
    let carry = fold.step::<ops::get_v3_profiling_download::GetV3ProfilingDownload>(carry);
    let carry = fold.step::<ops::get_v3_rebalance_status::GetV3RebalanceStatus>(carry);
    let carry = fold.step::<ops::get_v3_speedtest_client_devnull::GetV3SpeedtestClientDevnull>(carry);
    let carry = fold.step::<ops::get_v3_storageinfo::GetV3Storageinfo>(carry);
    let carry = fold.step::<ops::get_v3_top_locks::GetV3TopLocks>(carry);
    let carry = fold.step::<ops::get_v3_trace::GetV3Trace>(carry);
    let carry = fold.step::<ops::get_v4_cluster_snapshot::GetV4ClusterSnapshot>(carry);
    let carry = fold.step::<ops::get_v4_extensions_catalog::GetV4ExtensionsCatalog>(carry);
    let carry = fold.step::<ops::get_v4_extensions_instances::GetV4ExtensionsInstances>(carry);
    let carry = fold.step::<ops::get_v4_plugins_catalog::GetV4PluginsCatalog>(carry);
    let carry = fold.step::<ops::get_v4_runtime_capabilities::GetV4RuntimeCapabilities>(carry);
    let carry = fold.step::<ops::post_v3_force_unlock::PostV3ForceUnlock>(carry);
    let carry = fold.step::<ops::post_v3_inspect_data::PostV3InspectData>(carry);
    let carry = fold.step::<ops::post_v3_object_data_cache_flush::PostV3ObjectDataCacheFlush>(carry);
    let carry = fold.step::<ops::post_v3_profile::PostV3Profile>(carry);
    let carry = fold.step::<ops::post_v3_profiling_start::PostV3ProfilingStart>(carry);
    let carry = fold.step::<ops::post_v3_rebalance_start::PostV3RebalanceStart>(carry);
    let carry = fold.step::<ops::post_v3_rebalance_stop::PostV3RebalanceStop>(carry);
    let carry = fold.step::<ops::post_v3_service_restart::PostV3ServiceRestart>(carry);
    let carry = fold.step::<ops::post_v3_service_stop::PostV3ServiceStop>(carry);
    let carry = fold.step::<ops::post_v3_service_freeze::PostV3ServiceFreeze>(carry);
    let carry = fold.step::<ops::post_v3_service_unfreeze::PostV3ServiceUnfreeze>(carry);
    let carry = fold.step::<ops::post_v3_speedtest::PostV3Speedtest>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_client_devnull::PostV3SpeedtestClientDevnull>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_drive::PostV3SpeedtestDrive>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_net::PostV3SpeedtestNet>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_object::PostV3SpeedtestObject>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_site::PostV3SpeedtestSite>(carry);
    let carry = fold.step::<ops::post_v3_update::PostV3Update>(carry);
    let carry = fold.step::<ops::post_v4_inspect_archive::PostV4InspectArchive>(carry);
    let carry = fold.step::<ops::put_import_bucket_metadata::PutImportBucketMetadata>(carry);
    let carry = fold.step::<ops::put_v3_import_bucket_metadata::PutV3ImportBucketMetadata>(carry);
    fold.step::<ops::put_v3_module_switches::PutV3ModuleSwitches>(carry)
}
