// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! The dialect's generated table: the overlay rows, the route records, the pending groups, and the
//! one list of every operation.
//!
//! Responsible for: [`OVERLAY_ROWS`], [`ROUTES`], [`PENDING`] and [`fold_every_operation`], in inventory
//! order. NOT responsible for: the claims or the assembly (`crate::dialect`), or any operation's
//! declaration (`crate::ops`). Upstream: the generator and `crate::ops`. Downstream: `crate::dialect`,
//! the tests, and a deployment that walks every operation.

use rustfs_gateway_core::dialect::OverlayRow;

use crate::admin::OperationFold;
use crate::ops;
use crate::record::{PendingGroup, RouteRecord};

/// The RustFS commit the inventory was recorded from.
pub const RUSTFS_SOURCE_COMMIT: &str = "736e4fb8e8e5d527c25e4e56f352536b311b6daf";

/// Every operation's record, as the overlay reviews it.
pub(crate) static OVERLAY_ROWS: &[OverlayRow] = &[
    ops::delete_v3_audit_target_by_target_type_by_target_name_reset::OVERLAY_ROW,
    ops::delete_v3_cancel_job::OVERLAY_ROW,
    ops::delete_v3_clear_config_history_kv::OVERLAY_ROW,
    ops::delete_v3_del_config_kv::OVERLAY_ROW,
    ops::delete_v3_ilm_transition_jobs_by_job_id::OVERLAY_ROW,
    ops::delete_v3_kms_keys_delete::OVERLAY_ROW,
    ops::delete_v3_tier_by_tiername::OVERLAY_ROW,
    ops::delete_v4_plugins_instances_by_id::OVERLAY_ROW,
    ops::get_debug_pprof_profile::OVERLAY_ROW,
    ops::get_debug_pprof_status::OVERLAY_ROW,
    ops::get_debug_tls_status::OVERLAY_ROW,
    ops::get_export_bucket_metadata::OVERLAY_ROW,
    ops::get_v3_audit_target_list::OVERLAY_ROW,
    ops::get_v3_config::OVERLAY_ROW,
    ops::get_v3_datausageinfo::OVERLAY_ROW,
    ops::get_v3_decommission_status::OVERLAY_ROW,
    ops::get_v3_describe_job::OVERLAY_ROW,
    ops::get_v3_export_bucket_metadata::OVERLAY_ROW,
    ops::get_v3_gateway_key_inventory::OVERLAY_ROW,
    ops::get_v3_get_config_kv::OVERLAY_ROW,
    ops::get_v3_healthinfo::OVERLAY_ROW,
    ops::get_v3_help_config_kv::OVERLAY_ROW,
    ops::get_v3_ilm_expiry_status::OVERLAY_ROW,
    ops::get_v3_ilm_recovery_exports_by_export_id::OVERLAY_ROW,
    ops::get_v3_ilm_recovery_records::OVERLAY_ROW,
    ops::get_v3_ilm_recovery_records_by_control_id::OVERLAY_ROW,
    ops::get_v3_ilm_transition_jobs_by_job_id::OVERLAY_ROW,
    ops::get_v3_ilm_transition_reconcile_by_transaction_id::OVERLAY_ROW,
    ops::get_v3_ilm_transition_state_reconcile::OVERLAY_ROW,
    ops::get_v3_info::OVERLAY_ROW,
    ops::get_v3_inspect_data::OVERLAY_ROW,
    ops::get_v3_kms_backup::OVERLAY_ROW,
    ops::get_v3_kms_config::OVERLAY_ROW,
    ops::get_v3_kms_describe_key::OVERLAY_ROW,
    ops::get_v3_kms_key_status::OVERLAY_ROW,
    ops::get_v3_kms_keys::OVERLAY_ROW,
    ops::get_v3_kms_keys_rekey_status::OVERLAY_ROW,
    ops::get_v3_kms_keys_by_key_id::OVERLAY_ROW,
    ops::get_v3_kms_list_keys::OVERLAY_ROW,
    ops::get_v3_kms_service_status::OVERLAY_ROW,
    ops::get_v3_kms_status::OVERLAY_ROW,
    ops::get_v3_list_config_history_kv::OVERLAY_ROW,
    ops::get_v3_list_jobs::OVERLAY_ROW,
    ops::get_v3_log::OVERLAY_ROW,
    ops::get_v3_metrics::OVERLAY_ROW,
    ops::get_v3_module_switches::OVERLAY_ROW,
    ops::get_v3_obdinfo::OVERLAY_ROW,
    ops::get_v3_object_data_cache_stats::OVERLAY_ROW,
    ops::get_v3_pools_list::OVERLAY_ROW,
    ops::get_v3_pools_status::OVERLAY_ROW,
    ops::get_v3_profiling_download::OVERLAY_ROW,
    ops::get_v3_rebalance_status::OVERLAY_ROW,
    ops::get_v3_scanner_status::OVERLAY_ROW,
    ops::get_v3_scanner_usage_state_recovery_intents_by_intent_id::OVERLAY_ROW,
    ops::get_v3_site_replication_info::OVERLAY_ROW,
    ops::get_v3_site_replication_metainfo::OVERLAY_ROW,
    ops::get_v3_site_replication_peer_idp_settings::OVERLAY_ROW,
    ops::get_v3_site_replication_repair_status::OVERLAY_ROW,
    ops::get_v3_site_replication_status::OVERLAY_ROW,
    ops::get_v3_speedtest_client_devnull::OVERLAY_ROW,
    ops::get_v3_status_job::OVERLAY_ROW,
    ops::get_v3_storageinfo::OVERLAY_ROW,
    ops::get_v3_tier::OVERLAY_ROW,
    ops::get_v3_tier_stats::OVERLAY_ROW,
    ops::get_v3_tier_by_tier::OVERLAY_ROW,
    ops::get_v3_top_locks::OVERLAY_ROW,
    ops::get_v3_trace::OVERLAY_ROW,
    ops::get_v4_cluster_snapshot::OVERLAY_ROW,
    ops::get_v4_extensions_catalog::OVERLAY_ROW,
    ops::get_v4_extensions_instances::OVERLAY_ROW,
    ops::get_v4_plugins_catalog::OVERLAY_ROW,
    ops::get_v4_plugins_instances::OVERLAY_ROW,
    ops::get_v4_plugins_instances_by_id::OVERLAY_ROW,
    ops::get_v4_runtime_capabilities::OVERLAY_ROW,
    ops::post_v3_force_unlock::OVERLAY_ROW,
    ops::post_v3_ilm_recovery_records_by_control_id::OVERLAY_ROW,
    ops::post_v3_ilm_transition_reconcile_by_transaction_id::OVERLAY_ROW,
    ops::post_v3_ilm_transition_run::OVERLAY_ROW,
    ops::post_v3_ilm_transition_state_reconcile::OVERLAY_ROW,
    ops::post_v3_inspect_data::OVERLAY_ROW,
    ops::post_v3_kms_backup::OVERLAY_ROW,
    ops::post_v3_kms_clear_cache::OVERLAY_ROW,
    ops::post_v3_kms_configure::OVERLAY_ROW,
    ops::post_v3_kms_create_key::OVERLAY_ROW,
    ops::post_v3_kms_generate_data_key::OVERLAY_ROW,
    ops::post_v3_kms_key_create::OVERLAY_ROW,
    ops::post_v3_kms_keys::OVERLAY_ROW,
    ops::post_v3_kms_keys_cancel_deletion::OVERLAY_ROW,
    ops::post_v3_kms_keys_disable::OVERLAY_ROW,
    ops::post_v3_kms_keys_enable::OVERLAY_ROW,
    ops::post_v3_kms_keys_rekey::OVERLAY_ROW,
    ops::post_v3_kms_keys_rekey_cancel::OVERLAY_ROW,
    ops::post_v3_kms_keys_rotate::OVERLAY_ROW,
    ops::post_v3_kms_keys_tag::OVERLAY_ROW,
    ops::post_v3_kms_keys_untag::OVERLAY_ROW,
    ops::post_v3_kms_keys_update_description::OVERLAY_ROW,
    ops::post_v3_kms_reconfigure::OVERLAY_ROW,
    ops::post_v3_kms_reload::OVERLAY_ROW,
    ops::post_v3_kms_restore::OVERLAY_ROW,
    ops::post_v3_kms_restore_abort::OVERLAY_ROW,
    ops::post_v3_kms_restore_dry_run::OVERLAY_ROW,
    ops::post_v3_kms_start::OVERLAY_ROW,
    ops::post_v3_kms_status::OVERLAY_ROW,
    ops::post_v3_kms_stop::OVERLAY_ROW,
    ops::post_v3_object_data_cache_flush::OVERLAY_ROW,
    ops::post_v3_pools_cancel::OVERLAY_ROW,
    ops::post_v3_pools_clear::OVERLAY_ROW,
    ops::post_v3_pools_decommission::OVERLAY_ROW,
    ops::post_v3_profile::OVERLAY_ROW,
    ops::post_v3_profiling_start::OVERLAY_ROW,
    ops::post_v3_rebalance_start::OVERLAY_ROW,
    ops::post_v3_rebalance_stop::OVERLAY_ROW,
    ops::post_v3_scanner_cycle_state_reset::OVERLAY_ROW,
    ops::post_v3_scanner_usage_state_reset::OVERLAY_ROW,
    ops::post_v3_service_restart::OVERLAY_ROW,
    ops::post_v3_service_stop::OVERLAY_ROW,
    ops::post_v3_service_freeze::OVERLAY_ROW,
    ops::post_v3_service_unfreeze::OVERLAY_ROW,
    ops::post_v3_site_replication_devnull::OVERLAY_ROW,
    ops::post_v3_site_replication_netperf::OVERLAY_ROW,
    ops::post_v3_site_replication_rotate_svc_acct::OVERLAY_ROW,
    ops::post_v3_speedtest::OVERLAY_ROW,
    ops::post_v3_speedtest_client_devnull::OVERLAY_ROW,
    ops::post_v3_speedtest_drive::OVERLAY_ROW,
    ops::post_v3_speedtest_net::OVERLAY_ROW,
    ops::post_v3_speedtest_object::OVERLAY_ROW,
    ops::post_v3_speedtest_site::OVERLAY_ROW,
    ops::post_v3_start_job::OVERLAY_ROW,
    ops::post_v3_tier_clear::OVERLAY_ROW,
    ops::post_v3_tier_by_tiername::OVERLAY_ROW,
    ops::post_v3_update::OVERLAY_ROW,
    ops::post_v4_inspect_archive::OVERLAY_ROW,
    ops::put_import_bucket_metadata::OVERLAY_ROW,
    ops::put_v3_audit_target_by_target_type_by_target_name::OVERLAY_ROW,
    ops::put_v3_config::OVERLAY_ROW,
    ops::put_v3_import_bucket_metadata::OVERLAY_ROW,
    ops::put_v3_module_switches::OVERLAY_ROW,
    ops::put_v3_restore_config_history_kv::OVERLAY_ROW,
    ops::put_v3_set_config_kv::OVERLAY_ROW,
    ops::put_v3_site_replication_add::OVERLAY_ROW,
    ops::put_v3_site_replication_edit::OVERLAY_ROW,
    ops::put_v3_site_replication_join::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_bucket_meta::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_bucket_ops::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_edit::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_edit_capabilities::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_iam_item::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_join::OVERLAY_ROW,
    ops::put_v3_site_replication_peer_remove::OVERLAY_ROW,
    ops::put_v3_site_replication_remove::OVERLAY_ROW,
    ops::put_v3_site_replication_repair::OVERLAY_ROW,
    ops::put_v3_site_replication_resync_op::OVERLAY_ROW,
    ops::put_v3_site_replication_state_edit::OVERLAY_ROW,
    ops::put_v3_tier::OVERLAY_ROW,
    ops::put_v4_plugins_instances_by_id::OVERLAY_ROW,
];

/// Every declared operation and the inventory row it was generated from, in inventory order.
pub static ROUTES: &[RouteRecord] = &[
    ops::delete_v3_audit_target_by_target_type_by_target_name_reset::RECORD,
    ops::delete_v3_cancel_job::RECORD,
    ops::delete_v3_clear_config_history_kv::RECORD,
    ops::delete_v3_del_config_kv::RECORD,
    ops::delete_v3_ilm_transition_jobs_by_job_id::RECORD,
    ops::delete_v3_kms_keys_delete::RECORD,
    ops::delete_v3_tier_by_tiername::RECORD,
    ops::delete_v4_plugins_instances_by_id::RECORD,
    ops::get_debug_pprof_profile::RECORD,
    ops::get_debug_pprof_status::RECORD,
    ops::get_debug_tls_status::RECORD,
    ops::get_export_bucket_metadata::RECORD,
    ops::get_v3_audit_target_list::RECORD,
    ops::get_v3_config::RECORD,
    ops::get_v3_datausageinfo::RECORD,
    ops::get_v3_decommission_status::RECORD,
    ops::get_v3_describe_job::RECORD,
    ops::get_v3_export_bucket_metadata::RECORD,
    ops::get_v3_gateway_key_inventory::RECORD,
    ops::get_v3_get_config_kv::RECORD,
    ops::get_v3_healthinfo::RECORD,
    ops::get_v3_help_config_kv::RECORD,
    ops::get_v3_ilm_expiry_status::RECORD,
    ops::get_v3_ilm_recovery_exports_by_export_id::RECORD,
    ops::get_v3_ilm_recovery_records::RECORD,
    ops::get_v3_ilm_recovery_records_by_control_id::RECORD,
    ops::get_v3_ilm_transition_jobs_by_job_id::RECORD,
    ops::get_v3_ilm_transition_reconcile_by_transaction_id::RECORD,
    ops::get_v3_ilm_transition_state_reconcile::RECORD,
    ops::get_v3_info::RECORD,
    ops::get_v3_inspect_data::RECORD,
    ops::get_v3_kms_backup::RECORD,
    ops::get_v3_kms_config::RECORD,
    ops::get_v3_kms_describe_key::RECORD,
    ops::get_v3_kms_key_status::RECORD,
    ops::get_v3_kms_keys::RECORD,
    ops::get_v3_kms_keys_rekey_status::RECORD,
    ops::get_v3_kms_keys_by_key_id::RECORD,
    ops::get_v3_kms_list_keys::RECORD,
    ops::get_v3_kms_service_status::RECORD,
    ops::get_v3_kms_status::RECORD,
    ops::get_v3_list_config_history_kv::RECORD,
    ops::get_v3_list_jobs::RECORD,
    ops::get_v3_log::RECORD,
    ops::get_v3_metrics::RECORD,
    ops::get_v3_module_switches::RECORD,
    ops::get_v3_obdinfo::RECORD,
    ops::get_v3_object_data_cache_stats::RECORD,
    ops::get_v3_pools_list::RECORD,
    ops::get_v3_pools_status::RECORD,
    ops::get_v3_profiling_download::RECORD,
    ops::get_v3_rebalance_status::RECORD,
    ops::get_v3_scanner_status::RECORD,
    ops::get_v3_scanner_usage_state_recovery_intents_by_intent_id::RECORD,
    ops::get_v3_site_replication_info::RECORD,
    ops::get_v3_site_replication_metainfo::RECORD,
    ops::get_v3_site_replication_peer_idp_settings::RECORD,
    ops::get_v3_site_replication_repair_status::RECORD,
    ops::get_v3_site_replication_status::RECORD,
    ops::get_v3_speedtest_client_devnull::RECORD,
    ops::get_v3_status_job::RECORD,
    ops::get_v3_storageinfo::RECORD,
    ops::get_v3_tier::RECORD,
    ops::get_v3_tier_stats::RECORD,
    ops::get_v3_tier_by_tier::RECORD,
    ops::get_v3_top_locks::RECORD,
    ops::get_v3_trace::RECORD,
    ops::get_v4_cluster_snapshot::RECORD,
    ops::get_v4_extensions_catalog::RECORD,
    ops::get_v4_extensions_instances::RECORD,
    ops::get_v4_plugins_catalog::RECORD,
    ops::get_v4_plugins_instances::RECORD,
    ops::get_v4_plugins_instances_by_id::RECORD,
    ops::get_v4_runtime_capabilities::RECORD,
    ops::post_v3_force_unlock::RECORD,
    ops::post_v3_ilm_recovery_records_by_control_id::RECORD,
    ops::post_v3_ilm_transition_reconcile_by_transaction_id::RECORD,
    ops::post_v3_ilm_transition_run::RECORD,
    ops::post_v3_ilm_transition_state_reconcile::RECORD,
    ops::post_v3_inspect_data::RECORD,
    ops::post_v3_kms_backup::RECORD,
    ops::post_v3_kms_clear_cache::RECORD,
    ops::post_v3_kms_configure::RECORD,
    ops::post_v3_kms_create_key::RECORD,
    ops::post_v3_kms_generate_data_key::RECORD,
    ops::post_v3_kms_key_create::RECORD,
    ops::post_v3_kms_keys::RECORD,
    ops::post_v3_kms_keys_cancel_deletion::RECORD,
    ops::post_v3_kms_keys_disable::RECORD,
    ops::post_v3_kms_keys_enable::RECORD,
    ops::post_v3_kms_keys_rekey::RECORD,
    ops::post_v3_kms_keys_rekey_cancel::RECORD,
    ops::post_v3_kms_keys_rotate::RECORD,
    ops::post_v3_kms_keys_tag::RECORD,
    ops::post_v3_kms_keys_untag::RECORD,
    ops::post_v3_kms_keys_update_description::RECORD,
    ops::post_v3_kms_reconfigure::RECORD,
    ops::post_v3_kms_reload::RECORD,
    ops::post_v3_kms_restore::RECORD,
    ops::post_v3_kms_restore_abort::RECORD,
    ops::post_v3_kms_restore_dry_run::RECORD,
    ops::post_v3_kms_start::RECORD,
    ops::post_v3_kms_status::RECORD,
    ops::post_v3_kms_stop::RECORD,
    ops::post_v3_object_data_cache_flush::RECORD,
    ops::post_v3_pools_cancel::RECORD,
    ops::post_v3_pools_clear::RECORD,
    ops::post_v3_pools_decommission::RECORD,
    ops::post_v3_profile::RECORD,
    ops::post_v3_profiling_start::RECORD,
    ops::post_v3_rebalance_start::RECORD,
    ops::post_v3_rebalance_stop::RECORD,
    ops::post_v3_scanner_cycle_state_reset::RECORD,
    ops::post_v3_scanner_usage_state_reset::RECORD,
    ops::post_v3_service_restart::RECORD,
    ops::post_v3_service_stop::RECORD,
    ops::post_v3_service_freeze::RECORD,
    ops::post_v3_service_unfreeze::RECORD,
    ops::post_v3_site_replication_devnull::RECORD,
    ops::post_v3_site_replication_netperf::RECORD,
    ops::post_v3_site_replication_rotate_svc_acct::RECORD,
    ops::post_v3_speedtest::RECORD,
    ops::post_v3_speedtest_client_devnull::RECORD,
    ops::post_v3_speedtest_drive::RECORD,
    ops::post_v3_speedtest_net::RECORD,
    ops::post_v3_speedtest_object::RECORD,
    ops::post_v3_speedtest_site::RECORD,
    ops::post_v3_start_job::RECORD,
    ops::post_v3_tier_clear::RECORD,
    ops::post_v3_tier_by_tiername::RECORD,
    ops::post_v3_update::RECORD,
    ops::post_v4_inspect_archive::RECORD,
    ops::put_import_bucket_metadata::RECORD,
    ops::put_v3_audit_target_by_target_type_by_target_name::RECORD,
    ops::put_v3_config::RECORD,
    ops::put_v3_import_bucket_metadata::RECORD,
    ops::put_v3_module_switches::RECORD,
    ops::put_v3_restore_config_history_kv::RECORD,
    ops::put_v3_set_config_kv::RECORD,
    ops::put_v3_site_replication_add::RECORD,
    ops::put_v3_site_replication_edit::RECORD,
    ops::put_v3_site_replication_join::RECORD,
    ops::put_v3_site_replication_peer_bucket_meta::RECORD,
    ops::put_v3_site_replication_peer_bucket_ops::RECORD,
    ops::put_v3_site_replication_peer_edit::RECORD,
    ops::put_v3_site_replication_peer_edit_capabilities::RECORD,
    ops::put_v3_site_replication_peer_iam_item::RECORD,
    ops::put_v3_site_replication_peer_join::RECORD,
    ops::put_v3_site_replication_peer_remove::RECORD,
    ops::put_v3_site_replication_remove::RECORD,
    ops::put_v3_site_replication_repair::RECORD,
    ops::put_v3_site_replication_resync_op::RECORD,
    ops::put_v3_site_replication_state_edit::RECORD,
    ops::put_v3_tier::RECORD,
    ops::put_v4_plugins_instances_by_id::RECORD,
];

/// Every registration group RustFS still serves itself, with its route count.
pub static PENDING: &[PendingGroup] = &[
    PendingGroup {
        group: "account",
        order: 4,
        routes: 2,
    },
    PendingGroup {
        group: "durability_handler",
        order: 5,
        routes: 3,
    },
    PendingGroup {
        group: "heal",
        order: 5,
        routes: 5,
    },
    PendingGroup {
        group: "health",
        order: 8,
        routes: 6,
    },
    PendingGroup {
        group: "idp_compat",
        order: 4,
        routes: 13,
    },
    PendingGroup {
        group: "mfa",
        order: 4,
        routes: 8,
    },
    PendingGroup {
        group: "object_zip_download",
        order: 7,
        routes: 2,
    },
    PendingGroup {
        group: "oidc",
        order: 7,
        routes: 8,
    },
    PendingGroup {
        group: "on_demand_migration",
        order: 5,
        routes: 6,
    },
    PendingGroup {
        group: "quota_handler",
        order: 5,
        routes: 7,
    },
    PendingGroup {
        group: "replication_handler",
        order: 4,
        routes: 6,
    },
    PendingGroup {
        group: "sts",
        order: 7,
        routes: 2,
    },
    PendingGroup {
        group: "table_catalog",
        order: 6,
        routes: 98,
    },
    PendingGroup {
        group: "usage_prefix",
        order: 5,
        routes: 1,
    },
    PendingGroup {
        group: "user",
        order: 4,
        routes: 37,
    },
];

/// Takes `fold`'s step for every operation in turn, in [`ROUTES`] order.
pub fn fold_every_operation<F: OperationFold>(fold: &mut F, carry: F::Carry) -> F::Carry {
    let carry = fold.step::<ops::delete_v3_audit_target_by_target_type_by_target_name_reset::DeleteV3AuditTargetByTargetTypeByTargetNameReset>(carry);
    let carry = fold.step::<ops::delete_v3_cancel_job::DeleteV3CancelJob>(carry);
    let carry = fold.step::<ops::delete_v3_clear_config_history_kv::DeleteV3ClearConfigHistoryKv>(carry);
    let carry = fold.step::<ops::delete_v3_del_config_kv::DeleteV3DelConfigKv>(carry);
    let carry = fold.step::<ops::delete_v3_ilm_transition_jobs_by_job_id::DeleteV3IlmTransitionJobsByJobId>(carry);
    let carry = fold.step::<ops::delete_v3_kms_keys_delete::DeleteV3KmsKeysDelete>(carry);
    let carry = fold.step::<ops::delete_v3_tier_by_tiername::DeleteV3TierByTiername>(carry);
    let carry = fold.step::<ops::delete_v4_plugins_instances_by_id::DeleteV4PluginsInstancesById>(carry);
    let carry = fold.step::<ops::get_debug_pprof_profile::GetDebugPprofProfile>(carry);
    let carry = fold.step::<ops::get_debug_pprof_status::GetDebugPprofStatus>(carry);
    let carry = fold.step::<ops::get_debug_tls_status::GetDebugTlsStatus>(carry);
    let carry = fold.step::<ops::get_export_bucket_metadata::GetExportBucketMetadata>(carry);
    let carry = fold.step::<ops::get_v3_audit_target_list::GetV3AuditTargetList>(carry);
    let carry = fold.step::<ops::get_v3_config::GetV3Config>(carry);
    let carry = fold.step::<ops::get_v3_datausageinfo::GetV3Datausageinfo>(carry);
    let carry = fold.step::<ops::get_v3_decommission_status::GetV3DecommissionStatus>(carry);
    let carry = fold.step::<ops::get_v3_describe_job::GetV3DescribeJob>(carry);
    let carry = fold.step::<ops::get_v3_export_bucket_metadata::GetV3ExportBucketMetadata>(carry);
    let carry = fold.step::<ops::get_v3_gateway_key_inventory::GetV3GatewayKeyInventory>(carry);
    let carry = fold.step::<ops::get_v3_get_config_kv::GetV3GetConfigKv>(carry);
    let carry = fold.step::<ops::get_v3_healthinfo::GetV3Healthinfo>(carry);
    let carry = fold.step::<ops::get_v3_help_config_kv::GetV3HelpConfigKv>(carry);
    let carry = fold.step::<ops::get_v3_ilm_expiry_status::GetV3IlmExpiryStatus>(carry);
    let carry = fold.step::<ops::get_v3_ilm_recovery_exports_by_export_id::GetV3IlmRecoveryExportsByExportId>(carry);
    let carry = fold.step::<ops::get_v3_ilm_recovery_records::GetV3IlmRecoveryRecords>(carry);
    let carry = fold.step::<ops::get_v3_ilm_recovery_records_by_control_id::GetV3IlmRecoveryRecordsByControlId>(carry);
    let carry = fold.step::<ops::get_v3_ilm_transition_jobs_by_job_id::GetV3IlmTransitionJobsByJobId>(carry);
    let carry =
        fold.step::<ops::get_v3_ilm_transition_reconcile_by_transaction_id::GetV3IlmTransitionReconcileByTransactionId>(carry);
    let carry = fold.step::<ops::get_v3_ilm_transition_state_reconcile::GetV3IlmTransitionStateReconcile>(carry);
    let carry = fold.step::<ops::get_v3_info::GetV3Info>(carry);
    let carry = fold.step::<ops::get_v3_inspect_data::GetV3InspectData>(carry);
    let carry = fold.step::<ops::get_v3_kms_backup::GetV3KmsBackup>(carry);
    let carry = fold.step::<ops::get_v3_kms_config::GetV3KmsConfig>(carry);
    let carry = fold.step::<ops::get_v3_kms_describe_key::GetV3KmsDescribeKey>(carry);
    let carry = fold.step::<ops::get_v3_kms_key_status::GetV3KmsKeyStatus>(carry);
    let carry = fold.step::<ops::get_v3_kms_keys::GetV3KmsKeys>(carry);
    let carry = fold.step::<ops::get_v3_kms_keys_rekey_status::GetV3KmsKeysRekeyStatus>(carry);
    let carry = fold.step::<ops::get_v3_kms_keys_by_key_id::GetV3KmsKeysByKeyId>(carry);
    let carry = fold.step::<ops::get_v3_kms_list_keys::GetV3KmsListKeys>(carry);
    let carry = fold.step::<ops::get_v3_kms_service_status::GetV3KmsServiceStatus>(carry);
    let carry = fold.step::<ops::get_v3_kms_status::GetV3KmsStatus>(carry);
    let carry = fold.step::<ops::get_v3_list_config_history_kv::GetV3ListConfigHistoryKv>(carry);
    let carry = fold.step::<ops::get_v3_list_jobs::GetV3ListJobs>(carry);
    let carry = fold.step::<ops::get_v3_log::GetV3Log>(carry);
    let carry = fold.step::<ops::get_v3_metrics::GetV3Metrics>(carry);
    let carry = fold.step::<ops::get_v3_module_switches::GetV3ModuleSwitches>(carry);
    let carry = fold.step::<ops::get_v3_obdinfo::GetV3Obdinfo>(carry);
    let carry = fold.step::<ops::get_v3_object_data_cache_stats::GetV3ObjectDataCacheStats>(carry);
    let carry = fold.step::<ops::get_v3_pools_list::GetV3PoolsList>(carry);
    let carry = fold.step::<ops::get_v3_pools_status::GetV3PoolsStatus>(carry);
    let carry = fold.step::<ops::get_v3_profiling_download::GetV3ProfilingDownload>(carry);
    let carry = fold.step::<ops::get_v3_rebalance_status::GetV3RebalanceStatus>(carry);
    let carry = fold.step::<ops::get_v3_scanner_status::GetV3ScannerStatus>(carry);
    let carry = fold
        .step::<ops::get_v3_scanner_usage_state_recovery_intents_by_intent_id::GetV3ScannerUsageStateRecoveryIntentsByIntentId>(
        carry,
    );
    let carry = fold.step::<ops::get_v3_site_replication_info::GetV3SiteReplicationInfo>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_metainfo::GetV3SiteReplicationMetainfo>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_peer_idp_settings::GetV3SiteReplicationPeerIdpSettings>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_repair_status::GetV3SiteReplicationRepairStatus>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_status::GetV3SiteReplicationStatus>(carry);
    let carry = fold.step::<ops::get_v3_speedtest_client_devnull::GetV3SpeedtestClientDevnull>(carry);
    let carry = fold.step::<ops::get_v3_status_job::GetV3StatusJob>(carry);
    let carry = fold.step::<ops::get_v3_storageinfo::GetV3Storageinfo>(carry);
    let carry = fold.step::<ops::get_v3_tier::GetV3Tier>(carry);
    let carry = fold.step::<ops::get_v3_tier_stats::GetV3TierStats>(carry);
    let carry = fold.step::<ops::get_v3_tier_by_tier::GetV3TierByTier>(carry);
    let carry = fold.step::<ops::get_v3_top_locks::GetV3TopLocks>(carry);
    let carry = fold.step::<ops::get_v3_trace::GetV3Trace>(carry);
    let carry = fold.step::<ops::get_v4_cluster_snapshot::GetV4ClusterSnapshot>(carry);
    let carry = fold.step::<ops::get_v4_extensions_catalog::GetV4ExtensionsCatalog>(carry);
    let carry = fold.step::<ops::get_v4_extensions_instances::GetV4ExtensionsInstances>(carry);
    let carry = fold.step::<ops::get_v4_plugins_catalog::GetV4PluginsCatalog>(carry);
    let carry = fold.step::<ops::get_v4_plugins_instances::GetV4PluginsInstances>(carry);
    let carry = fold.step::<ops::get_v4_plugins_instances_by_id::GetV4PluginsInstancesById>(carry);
    let carry = fold.step::<ops::get_v4_runtime_capabilities::GetV4RuntimeCapabilities>(carry);
    let carry = fold.step::<ops::post_v3_force_unlock::PostV3ForceUnlock>(carry);
    let carry = fold.step::<ops::post_v3_ilm_recovery_records_by_control_id::PostV3IlmRecoveryRecordsByControlId>(carry);
    let carry =
        fold.step::<ops::post_v3_ilm_transition_reconcile_by_transaction_id::PostV3IlmTransitionReconcileByTransactionId>(carry);
    let carry = fold.step::<ops::post_v3_ilm_transition_run::PostV3IlmTransitionRun>(carry);
    let carry = fold.step::<ops::post_v3_ilm_transition_state_reconcile::PostV3IlmTransitionStateReconcile>(carry);
    let carry = fold.step::<ops::post_v3_inspect_data::PostV3InspectData>(carry);
    let carry = fold.step::<ops::post_v3_kms_backup::PostV3KmsBackup>(carry);
    let carry = fold.step::<ops::post_v3_kms_clear_cache::PostV3KmsClearCache>(carry);
    let carry = fold.step::<ops::post_v3_kms_configure::PostV3KmsConfigure>(carry);
    let carry = fold.step::<ops::post_v3_kms_create_key::PostV3KmsCreateKey>(carry);
    let carry = fold.step::<ops::post_v3_kms_generate_data_key::PostV3KmsGenerateDataKey>(carry);
    let carry = fold.step::<ops::post_v3_kms_key_create::PostV3KmsKeyCreate>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys::PostV3KmsKeys>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_cancel_deletion::PostV3KmsKeysCancelDeletion>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_disable::PostV3KmsKeysDisable>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_enable::PostV3KmsKeysEnable>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_rekey::PostV3KmsKeysRekey>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_rekey_cancel::PostV3KmsKeysRekeyCancel>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_rotate::PostV3KmsKeysRotate>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_tag::PostV3KmsKeysTag>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_untag::PostV3KmsKeysUntag>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_update_description::PostV3KmsKeysUpdateDescription>(carry);
    let carry = fold.step::<ops::post_v3_kms_reconfigure::PostV3KmsReconfigure>(carry);
    let carry = fold.step::<ops::post_v3_kms_reload::PostV3KmsReload>(carry);
    let carry = fold.step::<ops::post_v3_kms_restore::PostV3KmsRestore>(carry);
    let carry = fold.step::<ops::post_v3_kms_restore_abort::PostV3KmsRestoreAbort>(carry);
    let carry = fold.step::<ops::post_v3_kms_restore_dry_run::PostV3KmsRestoreDryRun>(carry);
    let carry = fold.step::<ops::post_v3_kms_start::PostV3KmsStart>(carry);
    let carry = fold.step::<ops::post_v3_kms_status::PostV3KmsStatus>(carry);
    let carry = fold.step::<ops::post_v3_kms_stop::PostV3KmsStop>(carry);
    let carry = fold.step::<ops::post_v3_object_data_cache_flush::PostV3ObjectDataCacheFlush>(carry);
    let carry = fold.step::<ops::post_v3_pools_cancel::PostV3PoolsCancel>(carry);
    let carry = fold.step::<ops::post_v3_pools_clear::PostV3PoolsClear>(carry);
    let carry = fold.step::<ops::post_v3_pools_decommission::PostV3PoolsDecommission>(carry);
    let carry = fold.step::<ops::post_v3_profile::PostV3Profile>(carry);
    let carry = fold.step::<ops::post_v3_profiling_start::PostV3ProfilingStart>(carry);
    let carry = fold.step::<ops::post_v3_rebalance_start::PostV3RebalanceStart>(carry);
    let carry = fold.step::<ops::post_v3_rebalance_stop::PostV3RebalanceStop>(carry);
    let carry = fold.step::<ops::post_v3_scanner_cycle_state_reset::PostV3ScannerCycleStateReset>(carry);
    let carry = fold.step::<ops::post_v3_scanner_usage_state_reset::PostV3ScannerUsageStateReset>(carry);
    let carry = fold.step::<ops::post_v3_service_restart::PostV3ServiceRestart>(carry);
    let carry = fold.step::<ops::post_v3_service_stop::PostV3ServiceStop>(carry);
    let carry = fold.step::<ops::post_v3_service_freeze::PostV3ServiceFreeze>(carry);
    let carry = fold.step::<ops::post_v3_service_unfreeze::PostV3ServiceUnfreeze>(carry);
    let carry = fold.step::<ops::post_v3_site_replication_devnull::PostV3SiteReplicationDevnull>(carry);
    let carry = fold.step::<ops::post_v3_site_replication_netperf::PostV3SiteReplicationNetperf>(carry);
    let carry = fold.step::<ops::post_v3_site_replication_rotate_svc_acct::PostV3SiteReplicationRotateSvcAcct>(carry);
    let carry = fold.step::<ops::post_v3_speedtest::PostV3Speedtest>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_client_devnull::PostV3SpeedtestClientDevnull>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_drive::PostV3SpeedtestDrive>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_net::PostV3SpeedtestNet>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_object::PostV3SpeedtestObject>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_site::PostV3SpeedtestSite>(carry);
    let carry = fold.step::<ops::post_v3_start_job::PostV3StartJob>(carry);
    let carry = fold.step::<ops::post_v3_tier_clear::PostV3TierClear>(carry);
    let carry = fold.step::<ops::post_v3_tier_by_tiername::PostV3TierByTiername>(carry);
    let carry = fold.step::<ops::post_v3_update::PostV3Update>(carry);
    let carry = fold.step::<ops::post_v4_inspect_archive::PostV4InspectArchive>(carry);
    let carry = fold.step::<ops::put_import_bucket_metadata::PutImportBucketMetadata>(carry);
    let carry =
        fold.step::<ops::put_v3_audit_target_by_target_type_by_target_name::PutV3AuditTargetByTargetTypeByTargetName>(carry);
    let carry = fold.step::<ops::put_v3_config::PutV3Config>(carry);
    let carry = fold.step::<ops::put_v3_import_bucket_metadata::PutV3ImportBucketMetadata>(carry);
    let carry = fold.step::<ops::put_v3_module_switches::PutV3ModuleSwitches>(carry);
    let carry = fold.step::<ops::put_v3_restore_config_history_kv::PutV3RestoreConfigHistoryKv>(carry);
    let carry = fold.step::<ops::put_v3_set_config_kv::PutV3SetConfigKv>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_add::PutV3SiteReplicationAdd>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_edit::PutV3SiteReplicationEdit>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_join::PutV3SiteReplicationJoin>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_bucket_meta::PutV3SiteReplicationPeerBucketMeta>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_bucket_ops::PutV3SiteReplicationPeerBucketOps>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_edit::PutV3SiteReplicationPeerEdit>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_edit_capabilities::PutV3SiteReplicationPeerEditCapabilities>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_iam_item::PutV3SiteReplicationPeerIamItem>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_join::PutV3SiteReplicationPeerJoin>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_remove::PutV3SiteReplicationPeerRemove>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_remove::PutV3SiteReplicationRemove>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_repair::PutV3SiteReplicationRepair>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_resync_op::PutV3SiteReplicationResyncOp>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_state_edit::PutV3SiteReplicationStateEdit>(carry);
    let carry = fold.step::<ops::put_v3_tier::PutV3Tier>(carry);
    fold.step::<ops::put_v4_plugins_instances_by_id::PutV4PluginsInstancesById>(carry)
}
