// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The macro's generated operation list is the route table's, or this test is red.
//!
//! Responsible for: proving that codegen owns `src/op_names.rs` and that it says exactly what
//! `rustfs_gateway_core::standard_operation_names()` says.
//! NOT responsible for: the mapping between a method name and an operation (`src/tests`).
//! Upstream: `rustfs-gateway-core`. Downstream: nothing.

use std::fs;
use std::path::PathBuf;

fn generated_source() -> String {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src").join("op_names.rs");
    fs::read_to_string(path).expect("src/op_names.rs exists")
}

/// The names as generated into `src/op_names.rs`.
fn generated_names() -> Vec<String> {
    let source = generated_source();
    let (_, tail) = source
        .split_once("static OPERATION_NAMES: &[&str] = &[")
        .expect("the list is declared");
    let (list, _) = tail.split_once("];").expect("the list is terminated");
    list.split(',')
        .map(str::trim)
        .filter(|item| !item.is_empty())
        .map(|item| item.trim_matches('"').to_owned())
        .collect()
}

/// Negative — a hand-maintained list is a second authority even when a comparison test catches
/// its drift later.
#[test]
fn the_operation_names_are_codegen_owned() {
    assert!(
        generated_source().contains("// @generated by `cargo xtask codegen`. Do not edit."),
        "crates/macros/src/op_names.rs must be generated from the same lowered IR as the route table"
    );
}

/// Positive — both generated consumers agree, name for name and in the same order.
#[test]
fn the_generated_operation_names_match_the_route_table() {
    let expected: Vec<String> = rustfs_gateway_core::standard_operation_names()
        .into_iter()
        .map(str::to_owned)
        .collect();
    assert_eq!(
        generated_names(),
        expected,
        "crates/macros/src/op_names.rs has drifted from the generated route table; regenerate with \
         `cargo xtask codegen`, because a name the macro accepts and the router does not is a \
         handler nothing can reach"
    );
}

/// Negative — the generated list is sorted and has no duplicates, so a merge cannot hide an entry.
#[test]
fn the_generated_list_is_sorted_and_unique() {
    let names = generated_names();
    let mut sorted = names.clone();
    sorted.sort();
    sorted.dedup();
    assert_eq!(names, sorted, "the list must stay sorted and free of duplicates");
    assert!(!names.is_empty(), "an empty list would make every method name an error");
}

/// Negative — nothing in the generated list is namespaced: third-party names are never in this table.
///
/// The macro maps a method name to an operation mechanically, and a namespaced name has a colon in
/// it, which no method name can produce. A namespaced entry here would be a name the macro could
/// never reach and a reader would assume it could.
#[test]
fn the_generated_list_holds_no_third_party_names() {
    for name in generated_names() {
        assert!(
            !name.contains(':'),
            "{name} is a third-party name; those are registered by hand, not by the macro"
        );
    }
}
