// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask rustfs-admin-dialect` from
// crates/goldens/src/migration_inventory/rustfs_admin_routes.json. Do not edit by hand: change the
// inventory or xtask/src/rustfs_admin_dialect.rs, then regenerate.

//! Every generated operation in one generic walk.
//!
//! Responsible for: [`fold_every_operation`], in inventory order. NOT responsible for: what a step does
//! (the caller's `OperationFold`). Upstream: `crate::ops`. Downstream: `crate::dialect` and a deployment
//! that registers a handler for every operation.

use crate::admin::OperationFold;
use crate::ops;

/// Takes `fold`'s step for every operation in turn, in [`crate::ROUTES`] order.
pub fn fold_every_operation<F: OperationFold>(fold: &mut F, carry: F::Carry) -> F::Carry {
    let carry = fold.step::<ops::delete_v3_audit_target_by_target_type_by_target_name_reset::DeleteV3AuditTargetByTargetTypeByTargetNameReset>(carry);
    let carry = fold.step::<ops::delete_v3_cancel_job::DeleteV3CancelJob>(carry);
    let carry = fold.step::<ops::delete_v3_clear_config_history_kv::DeleteV3ClearConfigHistoryKv>(carry);
    let carry = fold.step::<ops::delete_v3_del_config_kv::DeleteV3DelConfigKv>(carry);
    let carry = fold.step::<ops::delete_v3_delete_service_account::DeleteV3DeleteServiceAccount>(carry);
    let carry = fold.step::<ops::delete_v3_delete_service_accounts::DeleteV3DeleteServiceAccounts>(carry);
    let carry = fold.step::<ops::delete_v3_group_by_group::DeleteV3GroupByGroup>(carry);
    let carry = fold.step::<ops::delete_v3_idp_config_by_idp_type_by_name::DeleteV3IdpConfigByIdpTypeByName>(carry);
    let carry = fold.step::<ops::delete_v3_ilm_transition_jobs_by_job_id::DeleteV3IlmTransitionJobsByJobId>(carry);
    let carry = fold.step::<ops::delete_v3_kms_keys_delete::DeleteV3KmsKeysDelete>(carry);
    let carry = fold.step::<ops::delete_v3_remove_canned_policy::DeleteV3RemoveCannedPolicy>(carry);
    let carry = fold.step::<ops::delete_v3_remove_remote_target::DeleteV3RemoveRemoteTarget>(carry);
    let carry = fold.step::<ops::delete_v3_remove_user::DeleteV3RemoveUser>(carry);
    let carry = fold
        .step::<ops::delete_v3_target_by_target_type_by_target_name_reset::DeleteV3TargetByTargetTypeByTargetNameReset>(carry);
    let carry = fold.step::<ops::delete_v3_tier_by_tiername::DeleteV3TierByTiername>(carry);
    let carry = fold.step::<ops::delete_v3_user_mfa::DeleteV3UserMfa>(carry);
    let carry = fold.step::<ops::delete_v4_plugins_instances_by_id::DeleteV4PluginsInstancesById>(carry);
    let carry = fold.step::<ops::get_debug_pprof_profile::GetDebugPprofProfile>(carry);
    let carry = fold.step::<ops::get_debug_pprof_status::GetDebugPprofStatus>(carry);
    let carry = fold.step::<ops::get_debug_tls_status::GetDebugTlsStatus>(carry);
    let carry = fold.step::<ops::get_export_bucket_metadata::GetExportBucketMetadata>(carry);
    let carry = fold.step::<ops::get_v3_account_info::GetV3AccountInfo>(carry);
    let carry = fold.step::<ops::get_v3_account_mfa::GetV3AccountMfa>(carry);
    let carry = fold.step::<ops::get_v3_accountinfo::GetV3Accountinfo>(carry);
    let carry = fold.step::<ops::get_v3_audit_target_list::GetV3AuditTargetList>(carry);
    let carry = fold.step::<ops::get_v3_config::GetV3Config>(carry);
    let carry = fold.step::<ops::get_v3_datausageinfo::GetV3Datausageinfo>(carry);
    let carry = fold.step::<ops::get_v3_decommission_status::GetV3DecommissionStatus>(carry);
    let carry = fold.step::<ops::get_v3_describe_job::GetV3DescribeJob>(carry);
    let carry = fold.step::<ops::get_v3_export_bucket_metadata::GetV3ExportBucketMetadata>(carry);
    let carry = fold.step::<ops::get_v3_export_iam::GetV3ExportIam>(carry);
    let carry = fold.step::<ops::get_v3_gateway_key_inventory::GetV3GatewayKeyInventory>(carry);
    let carry = fold.step::<ops::get_v3_get_config_kv::GetV3GetConfigKv>(carry);
    let carry = fold.step::<ops::get_v3_group::GetV3Group>(carry);
    let carry = fold.step::<ops::get_v3_groups::GetV3Groups>(carry);
    let carry = fold.step::<ops::get_v3_healthinfo::GetV3Healthinfo>(carry);
    let carry = fold.step::<ops::get_v3_help_config_kv::GetV3HelpConfigKv>(carry);
    let carry = fold.step::<ops::get_v3_idp_config_by_idp_type::GetV3IdpConfigByIdpType>(carry);
    let carry = fold.step::<ops::get_v3_idp_config_by_idp_type_by_name::GetV3IdpConfigByIdpTypeByName>(carry);
    let carry = fold.step::<ops::get_v3_idp_builtin_policy_entities::GetV3IdpBuiltinPolicyEntities>(carry);
    let carry = fold.step::<ops::get_v3_idp_ldap_list_access_keys::GetV3IdpLdapListAccessKeys>(carry);
    let carry = fold.step::<ops::get_v3_idp_ldap_list_access_keys_bulk::GetV3IdpLdapListAccessKeysBulk>(carry);
    let carry = fold.step::<ops::get_v3_idp_ldap_policy_entities::GetV3IdpLdapPolicyEntities>(carry);
    let carry = fold.step::<ops::get_v3_idp_openid_list_access_keys_bulk::GetV3IdpOpenidListAccessKeysBulk>(carry);
    let carry = fold.step::<ops::get_v3_ilm_expiry_status::GetV3IlmExpiryStatus>(carry);
    let carry = fold.step::<ops::get_v3_ilm_recovery_exports_by_export_id::GetV3IlmRecoveryExportsByExportId>(carry);
    let carry = fold.step::<ops::get_v3_ilm_recovery_records::GetV3IlmRecoveryRecords>(carry);
    let carry = fold.step::<ops::get_v3_ilm_recovery_records_by_control_id::GetV3IlmRecoveryRecordsByControlId>(carry);
    let carry = fold.step::<ops::get_v3_ilm_transition_jobs_by_job_id::GetV3IlmTransitionJobsByJobId>(carry);
    let carry =
        fold.step::<ops::get_v3_ilm_transition_reconcile_by_transaction_id::GetV3IlmTransitionReconcileByTransactionId>(carry);
    let carry = fold.step::<ops::get_v3_ilm_transition_state_reconcile::GetV3IlmTransitionStateReconcile>(carry);
    let carry = fold.step::<ops::get_v3_info::GetV3Info>(carry);
    let carry = fold.step::<ops::get_v3_info_access_key::GetV3InfoAccessKey>(carry);
    let carry = fold.step::<ops::get_v3_info_canned_policy::GetV3InfoCannedPolicy>(carry);
    let carry = fold.step::<ops::get_v3_info_service_account::GetV3InfoServiceAccount>(carry);
    let carry = fold.step::<ops::get_v3_inspect_data::GetV3InspectData>(carry);
    let carry = fold.step::<ops::get_v3_kms_backup::GetV3KmsBackup>(carry);
    let carry = fold.step::<ops::get_v3_kms_config::GetV3KmsConfig>(carry);
    let carry = fold.step::<ops::get_v3_kms_describe_key::GetV3KmsDescribeKey>(carry);
    let carry = fold.step::<ops::get_v3_kms_key_status::GetV3KmsKeyStatus>(carry);
    let carry = fold.step::<ops::get_v3_kms_keys::GetV3KmsKeys>(carry);
    let carry = fold.step::<ops::get_v3_kms_keys_rekey_status::GetV3KmsKeysRekeyStatus>(carry);
    let carry = fold.step::<ops::get_v3_kms_keys_by_key_id::GetV3KmsKeysByKeyId>(carry);
    let carry = fold.step::<ops::get_v3_kms_list_keys::GetV3KmsListKeys>(carry);
    let carry = fold.step::<ops::get_v3_kms_service_status::GetV3KmsServiceStatus>(carry);
    let carry = fold.step::<ops::get_v3_kms_status::GetV3KmsStatus>(carry);
    let carry = fold.step::<ops::get_v3_list_access_keys_bulk::GetV3ListAccessKeysBulk>(carry);
    let carry = fold.step::<ops::get_v3_list_canned_policies::GetV3ListCannedPolicies>(carry);
    let carry = fold.step::<ops::get_v3_list_config_history_kv::GetV3ListConfigHistoryKv>(carry);
    let carry = fold.step::<ops::get_v3_list_jobs::GetV3ListJobs>(carry);
    let carry = fold.step::<ops::get_v3_list_remote_targets::GetV3ListRemoteTargets>(carry);
    let carry = fold.step::<ops::get_v3_list_service_accounts::GetV3ListServiceAccounts>(carry);
    let carry = fold.step::<ops::get_v3_list_users::GetV3ListUsers>(carry);
    let carry = fold.step::<ops::get_v3_log::GetV3Log>(carry);
    let carry = fold.step::<ops::get_v3_metrics::GetV3Metrics>(carry);
    let carry = fold.step::<ops::get_v3_mfa_challenge::GetV3MfaChallenge>(carry);
    let carry = fold.step::<ops::get_v3_module_switches::GetV3ModuleSwitches>(carry);
    let carry = fold.step::<ops::get_v3_obdinfo::GetV3Obdinfo>(carry);
    let carry = fold.step::<ops::get_v3_object_data_cache_stats::GetV3ObjectDataCacheStats>(carry);
    let carry = fold.step::<ops::get_v3_pools_list::GetV3PoolsList>(carry);
    let carry = fold.step::<ops::get_v3_pools_status::GetV3PoolsStatus>(carry);
    let carry = fold.step::<ops::get_v3_profiling_download::GetV3ProfilingDownload>(carry);
    let carry = fold.step::<ops::get_v3_rebalance_status::GetV3RebalanceStatus>(carry);
    let carry = fold.step::<ops::get_v3_replication_mrf::GetV3ReplicationMrf>(carry);
    let carry = fold.step::<ops::get_v3_replicationmetrics::GetV3Replicationmetrics>(carry);
    let carry = fold.step::<ops::get_v3_scanner_status::GetV3ScannerStatus>(carry);
    let carry = fold
        .step::<ops::get_v3_scanner_usage_state_recovery_intents_by_intent_id::GetV3ScannerUsageStateRecoveryIntentsByIntentId>(
        carry,
    );
    let carry = fold.step::<ops::get_v3_site_replication_info::GetV3SiteReplicationInfo>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_metainfo::GetV3SiteReplicationMetainfo>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_peer_idp_settings::GetV3SiteReplicationPeerIdpSettings>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_repair_status::GetV3SiteReplicationRepairStatus>(carry);
    let carry = fold.step::<ops::get_v3_site_replication_status::GetV3SiteReplicationStatus>(carry);
    let carry = fold.step::<ops::get_v3_speedtest_client_devnull::GetV3SpeedtestClientDevnull>(carry);
    let carry = fold.step::<ops::get_v3_status_job::GetV3StatusJob>(carry);
    let carry = fold.step::<ops::get_v3_storageinfo::GetV3Storageinfo>(carry);
    let carry = fold.step::<ops::get_v3_target_arns::GetV3TargetArns>(carry);
    let carry = fold.step::<ops::get_v3_target_list::GetV3TargetList>(carry);
    let carry = fold.step::<ops::get_v3_temporary_account_info::GetV3TemporaryAccountInfo>(carry);
    let carry = fold.step::<ops::get_v3_tier::GetV3Tier>(carry);
    let carry = fold.step::<ops::get_v3_tier_stats::GetV3TierStats>(carry);
    let carry = fold.step::<ops::get_v3_tier_by_tier::GetV3TierByTier>(carry);
    let carry = fold.step::<ops::get_v3_top_locks::GetV3TopLocks>(carry);
    let carry = fold.step::<ops::get_v3_trace::GetV3Trace>(carry);
    let carry = fold.step::<ops::get_v3_user_info::GetV3UserInfo>(carry);
    let carry = fold.step::<ops::get_v3_user_mfa::GetV3UserMfa>(carry);
    let carry = fold.step::<ops::get_v4_cluster_snapshot::GetV4ClusterSnapshot>(carry);
    let carry = fold.step::<ops::get_v4_extensions_catalog::GetV4ExtensionsCatalog>(carry);
    let carry = fold.step::<ops::get_v4_extensions_instances::GetV4ExtensionsInstances>(carry);
    let carry = fold.step::<ops::get_v4_plugins_catalog::GetV4PluginsCatalog>(carry);
    let carry = fold.step::<ops::get_v4_plugins_instances::GetV4PluginsInstances>(carry);
    let carry = fold.step::<ops::get_v4_plugins_instances_by_id::GetV4PluginsInstancesById>(carry);
    let carry = fold.step::<ops::get_v4_runtime_capabilities::GetV4RuntimeCapabilities>(carry);
    let carry = fold.step::<ops::post_v3_account_mfa_activate::PostV3AccountMfaActivate>(carry);
    let carry = fold.step::<ops::post_v3_account_mfa_disable::PostV3AccountMfaDisable>(carry);
    let carry = fold.step::<ops::post_v3_account_mfa_enroll::PostV3AccountMfaEnroll>(carry);
    let carry = fold.step::<ops::post_v3_account_mfa_recovery_codes::PostV3AccountMfaRecoveryCodes>(carry);
    let carry = fold.step::<ops::post_v3_account_password::PostV3AccountPassword>(carry);
    let carry = fold.step::<ops::post_v3_force_unlock::PostV3ForceUnlock>(carry);
    let carry = fold.step::<ops::post_v3_idp_config_by_idp_type_by_name::PostV3IdpConfigByIdpTypeByName>(carry);
    let carry = fold.step::<ops::post_v3_idp_builtin_policy_attach::PostV3IdpBuiltinPolicyAttach>(carry);
    let carry = fold.step::<ops::post_v3_idp_builtin_policy_detach::PostV3IdpBuiltinPolicyDetach>(carry);
    let carry = fold.step::<ops::post_v3_idp_ldap_policy_by_operation::PostV3IdpLdapPolicyByOperation>(carry);
    let carry = fold.step::<ops::post_v3_ilm_recovery_records_by_control_id::PostV3IlmRecoveryRecordsByControlId>(carry);
    let carry =
        fold.step::<ops::post_v3_ilm_transition_reconcile_by_transaction_id::PostV3IlmTransitionReconcileByTransactionId>(carry);
    let carry = fold.step::<ops::post_v3_ilm_transition_run::PostV3IlmTransitionRun>(carry);
    let carry = fold.step::<ops::post_v3_ilm_transition_state_reconcile::PostV3IlmTransitionStateReconcile>(carry);
    let carry = fold.step::<ops::post_v3_inspect_data::PostV3InspectData>(carry);
    let carry = fold.step::<ops::post_v3_kms_backup::PostV3KmsBackup>(carry);
    let carry = fold.step::<ops::post_v3_kms_clear_cache::PostV3KmsClearCache>(carry);
    let carry = fold.step::<ops::post_v3_kms_configure::PostV3KmsConfigure>(carry);
    let carry = fold.step::<ops::post_v3_kms_create_key::PostV3KmsCreateKey>(carry);
    let carry = fold.step::<ops::post_v3_kms_generate_data_key::PostV3KmsGenerateDataKey>(carry);
    let carry = fold.step::<ops::post_v3_kms_key_create::PostV3KmsKeyCreate>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys::PostV3KmsKeys>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_cancel_deletion::PostV3KmsKeysCancelDeletion>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_disable::PostV3KmsKeysDisable>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_enable::PostV3KmsKeysEnable>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_rekey::PostV3KmsKeysRekey>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_rekey_cancel::PostV3KmsKeysRekeyCancel>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_rotate::PostV3KmsKeysRotate>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_tag::PostV3KmsKeysTag>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_untag::PostV3KmsKeysUntag>(carry);
    let carry = fold.step::<ops::post_v3_kms_keys_update_description::PostV3KmsKeysUpdateDescription>(carry);
    let carry = fold.step::<ops::post_v3_kms_reconfigure::PostV3KmsReconfigure>(carry);
    let carry = fold.step::<ops::post_v3_kms_reload::PostV3KmsReload>(carry);
    let carry = fold.step::<ops::post_v3_kms_restore::PostV3KmsRestore>(carry);
    let carry = fold.step::<ops::post_v3_kms_restore_abort::PostV3KmsRestoreAbort>(carry);
    let carry = fold.step::<ops::post_v3_kms_restore_dry_run::PostV3KmsRestoreDryRun>(carry);
    let carry = fold.step::<ops::post_v3_kms_start::PostV3KmsStart>(carry);
    let carry = fold.step::<ops::post_v3_kms_status::PostV3KmsStatus>(carry);
    let carry = fold.step::<ops::post_v3_kms_stop::PostV3KmsStop>(carry);
    let carry = fold.step::<ops::post_v3_object_data_cache_flush::PostV3ObjectDataCacheFlush>(carry);
    let carry = fold.step::<ops::post_v3_pools_cancel::PostV3PoolsCancel>(carry);
    let carry = fold.step::<ops::post_v3_pools_clear::PostV3PoolsClear>(carry);
    let carry = fold.step::<ops::post_v3_pools_decommission::PostV3PoolsDecommission>(carry);
    let carry = fold.step::<ops::post_v3_profile::PostV3Profile>(carry);
    let carry = fold.step::<ops::post_v3_profiling_start::PostV3ProfilingStart>(carry);
    let carry = fold.step::<ops::post_v3_rebalance_start::PostV3RebalanceStart>(carry);
    let carry = fold.step::<ops::post_v3_rebalance_stop::PostV3RebalanceStop>(carry);
    let carry = fold.step::<ops::post_v3_replication_diff::PostV3ReplicationDiff>(carry);
    let carry = fold.step::<ops::post_v3_revoke_tokens_by_user_provider::PostV3RevokeTokensByUserProvider>(carry);
    let carry = fold.step::<ops::post_v3_scanner_cycle_state_reset::PostV3ScannerCycleStateReset>(carry);
    let carry = fold.step::<ops::post_v3_scanner_usage_state_reset::PostV3ScannerUsageStateReset>(carry);
    let carry = fold.step::<ops::post_v3_service_restart::PostV3ServiceRestart>(carry);
    let carry = fold.step::<ops::post_v3_service_stop::PostV3ServiceStop>(carry);
    let carry = fold.step::<ops::post_v3_service_freeze::PostV3ServiceFreeze>(carry);
    let carry = fold.step::<ops::post_v3_service_unfreeze::PostV3ServiceUnfreeze>(carry);
    let carry = fold.step::<ops::post_v3_site_replication_devnull::PostV3SiteReplicationDevnull>(carry);
    let carry = fold.step::<ops::post_v3_site_replication_netperf::PostV3SiteReplicationNetperf>(carry);
    let carry = fold.step::<ops::post_v3_site_replication_rotate_svc_acct::PostV3SiteReplicationRotateSvcAcct>(carry);
    let carry = fold.step::<ops::post_v3_speedtest::PostV3Speedtest>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_client_devnull::PostV3SpeedtestClientDevnull>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_drive::PostV3SpeedtestDrive>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_net::PostV3SpeedtestNet>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_object::PostV3SpeedtestObject>(carry);
    let carry = fold.step::<ops::post_v3_speedtest_site::PostV3SpeedtestSite>(carry);
    let carry = fold.step::<ops::post_v3_start_job::PostV3StartJob>(carry);
    let carry = fold.step::<ops::post_v3_tier_clear::PostV3TierClear>(carry);
    let carry = fold.step::<ops::post_v3_tier_by_tiername::PostV3TierByTiername>(carry);
    let carry = fold.step::<ops::post_v3_update::PostV3Update>(carry);
    let carry = fold.step::<ops::post_v3_update_service_account::PostV3UpdateServiceAccount>(carry);
    let carry = fold.step::<ops::post_v4_inspect_archive::PostV4InspectArchive>(carry);
    let carry = fold.step::<ops::put_import_bucket_metadata::PutImportBucketMetadata>(carry);
    let carry = fold.step::<ops::put_v3_add_canned_policy::PutV3AddCannedPolicy>(carry);
    let carry = fold.step::<ops::put_v3_add_service_account::PutV3AddServiceAccount>(carry);
    let carry = fold.step::<ops::put_v3_add_service_accounts::PutV3AddServiceAccounts>(carry);
    let carry = fold.step::<ops::put_v3_add_user::PutV3AddUser>(carry);
    let carry =
        fold.step::<ops::put_v3_audit_target_by_target_type_by_target_name::PutV3AuditTargetByTargetTypeByTargetName>(carry);
    let carry = fold.step::<ops::put_v3_config::PutV3Config>(carry);
    let carry = fold.step::<ops::put_v3_idp_config_by_idp_type_by_name::PutV3IdpConfigByIdpTypeByName>(carry);
    let carry = fold.step::<ops::put_v3_idp_ldap_add_service_account::PutV3IdpLdapAddServiceAccount>(carry);
    let carry = fold.step::<ops::put_v3_import_bucket_metadata::PutV3ImportBucketMetadata>(carry);
    let carry = fold.step::<ops::put_v3_import_iam::PutV3ImportIam>(carry);
    let carry = fold.step::<ops::put_v3_import_iam_v2::PutV3ImportIamV2>(carry);
    let carry = fold.step::<ops::put_v3_module_switches::PutV3ModuleSwitches>(carry);
    let carry = fold.step::<ops::put_v3_restore_config_history_kv::PutV3RestoreConfigHistoryKv>(carry);
    let carry = fold.step::<ops::put_v3_set_config_kv::PutV3SetConfigKv>(carry);
    let carry = fold.step::<ops::put_v3_set_group_status::PutV3SetGroupStatus>(carry);
    let carry = fold.step::<ops::put_v3_set_policy::PutV3SetPolicy>(carry);
    let carry = fold.step::<ops::put_v3_set_remote_target::PutV3SetRemoteTarget>(carry);
    let carry = fold.step::<ops::put_v3_set_user_or_group_policy::PutV3SetUserOrGroupPolicy>(carry);
    let carry = fold.step::<ops::put_v3_set_user_secret_key::PutV3SetUserSecretKey>(carry);
    let carry = fold.step::<ops::put_v3_set_user_status::PutV3SetUserStatus>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_add::PutV3SiteReplicationAdd>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_edit::PutV3SiteReplicationEdit>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_join::PutV3SiteReplicationJoin>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_bucket_meta::PutV3SiteReplicationPeerBucketMeta>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_bucket_ops::PutV3SiteReplicationPeerBucketOps>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_edit::PutV3SiteReplicationPeerEdit>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_edit_capabilities::PutV3SiteReplicationPeerEditCapabilities>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_iam_item::PutV3SiteReplicationPeerIamItem>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_join::PutV3SiteReplicationPeerJoin>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_peer_remove::PutV3SiteReplicationPeerRemove>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_remove::PutV3SiteReplicationRemove>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_repair::PutV3SiteReplicationRepair>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_resync_op::PutV3SiteReplicationResyncOp>(carry);
    let carry = fold.step::<ops::put_v3_site_replication_state_edit::PutV3SiteReplicationStateEdit>(carry);
    let carry = fold.step::<ops::put_v3_target_by_target_type_by_target_name::PutV3TargetByTargetTypeByTargetName>(carry);
    let carry = fold.step::<ops::put_v3_tier::PutV3Tier>(carry);
    let carry = fold.step::<ops::put_v3_update_group_members::PutV3UpdateGroupMembers>(carry);
    fold.step::<ops::put_v4_plugins_instances_by_id::PutV4PluginsInstancesById>(carry)
}
