#!/usr/bin/env bash
# REQUIRES-BUILD
set -euo pipefail

# =============================================================================
# check_verify_map_generated.sh
#
# WHAT THIS CHECKS
#   `xtask/verify-map.toml` exists, carries the codegen ownership marker, and is
#   byte-for-byte what `cargo xtask codegen --check` regenerates in memory.
#
# WHY
#   rustfs/backlog#1743. `verify --op` must use a generated operation-to-test
#   mapping. A hand-maintained map silently stops running cases as operations
#   evolve, producing a fast but meaningless green verification loop.
#
# HOW TO EXEMPT
#   Not applicable. Change the model, overlay, or generator and regenerate the
#   map. Direct edits are always drift.
#
# USAGE
#   scripts/check_verify_map_generated.sh
#   GATEWAY_CHECK_ROOT=/path/to/repo scripts/check_verify_map_generated.sh
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${GATEWAY_CHECK_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
MAP="$ROOT_DIR/xtask/verify-map.toml"
EXPECTED='# @generated by cargo xtask codegen; do not edit'

if [[ ! -f "$MAP" ]]; then
    printf 'check_verify_map_generated.sh: required generated input is missing: %s\n' "$MAP" >&2
    exit 1
fi

IFS= read -r first_line <"$MAP" || true
if [[ "$first_line" != "$EXPECTED" ]]; then
    printf 'check_verify_map_generated.sh: %s has no exact codegen ownership marker\n' "$MAP" >&2
    exit 1
fi

# IR validation deliberately carries a full draft 2020-12 implementation. This guard exercises
# only codegen, so keep that unrelated dependency out of its cold CI build.
if ! (cd "$ROOT_DIR" && "${CARGO:-cargo}" run --quiet --package xtask --no-default-features -- codegen --check); then
    printf 'check_verify_map_generated.sh: verify-map drifted; regenerate with `cargo xtask codegen`\n' >&2
    exit 1
fi

printf 'OK: operation verification map is generated and current\n'
