// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The operation catalog used by repository automation.
//!
//! Responsible for: loading operation IR and suggesting the nearest operation name.
//! NOT responsible for: routing or code generation policy.
//! Upstream: xtask commands. Downstream: `rustfs-gateway-codegen`.

use rustfs_gateway_codegen::{CodegenInput, CodegenOutput};
use rustfs_gateway_model::ir::OperationIr;

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::codegen::repo_root;

pub(crate) fn operations() -> Result<Vec<OperationIr>, String> {
    let root = repo_root();
    rustfs_gateway_codegen::generate(&CodegenInput::at(&root), &CodegenOutput::at(&root))
        .map(|artifacts| artifacts.operations)
        .map_err(|error| error.to_string())
}

pub(crate) fn nearest(operations: &[OperationIr], needle: &str) -> Option<String> {
    operations
        .iter()
        .map(|operation| {
            (
                distance(&needle.to_lowercase(), &operation.operation.to_lowercase()),
                operation.operation.clone(),
            )
        })
        .min()
        .map(|(_, operation)| operation)
}

pub(crate) fn verify_map_path() -> PathBuf {
    repo_root().join("xtask/verify-map.toml")
}

pub(crate) fn render_verify_map(operations: &[OperationIr]) -> Result<String, String> {
    let cases = operation_cases(&repo_root().join("conformance/cases"))?;
    let mut operations: Vec<&OperationIr> = operations.iter().collect();
    operations.sort_by(|left, right| left.operation.cmp(&right.operation));
    let mut out = String::from("# @generated by cargo xtask codegen; do not edit\n\n");
    for operation in operations {
        let cases = cases
            .get(&operation.operation)
            .map(|cases| cases.join(","))
            .unwrap_or_default();
        out.push_str("[[operation]]\n");
        out.push_str(&format!("name = {:?}\n", operation.operation));
        out.push_str(&format!("cases = {cases:?}\n\n"));
    }
    Ok(out)
}

pub(crate) fn verify_entry(name: &str) -> Result<VerifyEntry, String> {
    let body = fs::read_to_string(verify_map_path()).map_err(|error| format!("verify map could not be read: {error}"))?;
    parse_verify_map(&body)
        .into_iter()
        .find(|entry| entry.name == name)
        .ok_or_else(|| format!("verify map has no entry for {name}; run `cargo xtask codegen`"))
}

pub(crate) fn scaffold_entry(name: &str) -> Result<Option<ScaffoldEntry>, String> {
    let root = repo_root().join("xtask/scaffolds");
    let entries = match fs::read_dir(&root) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(format!("{}: {error}", root.display())),
    };
    for entry in entries {
        let path = entry.map_err(|error| error.to_string())?.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
            continue;
        }
        let body = fs::read_to_string(&path).map_err(|error| format!("{}: {error}", path.display()))?;
        let entry = ScaffoldEntry {
            name: quoted_field(&body, "name = ").unwrap_or_default(),
            test: quoted_field(&body, "test = ").unwrap_or_default(),
        };
        if entry.name == name {
            return Ok(Some(entry));
        }
    }
    Ok(None)
}

pub(crate) struct VerifyEntry {
    pub(crate) name: String,
    pub(crate) cases: Vec<String>,
}

pub(crate) struct ScaffoldEntry {
    pub(crate) name: String,
    pub(crate) test: String,
}

fn parse_verify_map(body: &str) -> Vec<VerifyEntry> {
    let mut entries = Vec::new();
    let mut name: Option<String> = None;
    let mut cases: Option<String> = None;
    for line in body.lines().chain(["[[operation]]"]) {
        if line == "[[operation]]" {
            if let (Some(name), Some(cases)) = (name.take(), cases.take()) {
                entries.push(VerifyEntry {
                    name,
                    cases: split_cases(&cases),
                });
            }
            continue;
        }
        if let Some(value) = quoted_value(line, "name = ") {
            name = Some(value);
        } else if let Some(value) = quoted_value(line, "cases = ") {
            cases = Some(value);
        }
    }
    entries
}

fn split_cases(value: &str) -> Vec<String> {
    value.split(',').filter(|case| !case.is_empty()).map(str::to_owned).collect()
}

fn quoted_value(line: &str, prefix: &str) -> Option<String> {
    line.strip_prefix(prefix)
        .and_then(|value| value.strip_prefix('"'))
        .and_then(|value| value.strip_suffix('"'))
        .map(str::to_owned)
}

fn quoted_field(body: &str, prefix: &str) -> Option<String> {
    body.lines().find_map(|line| quoted_value(line.trim(), prefix))
}

fn operation_cases(root: &Path) -> Result<BTreeMap<String, Vec<String>>, String> {
    let mut paths = Vec::new();
    collect_toml(root, &mut paths)?;
    paths.sort();
    let mut cases: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for path in paths {
        let body = fs::read_to_string(&path).map_err(|error| format!("{}: {error}", path.display()))?;
        let operation = body.lines().find_map(|line| quoted_value(line.trim(), "operation = "));
        let id = body.lines().find_map(|line| quoted_value(line.trim(), "id = "));
        if let (Some(operation), Some(id)) = (operation, id) {
            cases.entry(operation).or_default().push(id);
        }
    }
    Ok(cases)
}

fn collect_toml(root: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in fs::read_dir(root).map_err(|error| format!("{}: {error}", root.display()))? {
        let path = entry.map_err(|error| error.to_string())?.path();
        if path.is_dir() {
            collect_toml(&path, paths)?;
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("toml") {
            paths.push(path);
        }
    }
    Ok(())
}

fn distance(left: &str, right: &str) -> usize {
    let left: Vec<char> = left.chars().collect();
    let right: Vec<char> = right.chars().collect();
    let mut previous: Vec<usize> = (0..=right.len()).collect();
    let mut current = vec![0; right.len() + 1];
    for (left_index, left_char) in left.iter().enumerate() {
        current[0] = left_index + 1;
        for (right_index, right_char) in right.iter().enumerate() {
            let substitution = previous[right_index] + usize::from(left_char != right_char);
            current[right_index + 1] = substitution.min(previous[right_index + 1] + 1).min(current[right_index] + 1);
        }
        std::mem::swap(&mut previous, &mut current);
    }
    previous[right.len()]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    use rustfs_gateway_core::route::generated_entries;

    #[test]
    fn generated_map_lists_all_cases_without_a_fake_shared_test() {
        let rendered = render_verify_map(&operations().expect("the operation catalog must load"))
            .expect("the repository case catalog must load");

        assert!(!rendered.contains("test ="));
        assert!(rendered.contains("cases ="));
    }

    #[test]
    fn operation_map_covers_every_generated_operation() {
        let operations = operations().expect("the operation catalog must load");
        let expected = render_verify_map(&operations).expect("the repository case catalog must load");
        let actual = fs::read_to_string(verify_map_path()).expect("the checked-in verify map must load");
        assert_eq!(actual, expected, "the verification map must be regenerated");

        let mapped: BTreeSet<_> = parse_verify_map(&actual).into_iter().map(|entry| entry.name).collect();
        let modeled: BTreeSet<_> = operations.into_iter().map(|operation| operation.operation).collect();
        let routed: BTreeSet<_> = generated_entries()
            .expect("the runtime route entries must build")
            .into_iter()
            .map(|entry| entry.op_name.to_owned())
            .collect();
        assert_eq!(mapped, modeled);
        assert_eq!(mapped, routed);
    }

    #[test]
    fn selected_operation_has_runtime_route_contract() {
        let selected = std::env::var("RUSTFS_GATEWAY_VERIFY_OPERATION").ok();
        let operations = operations().expect("the operation catalog must load");
        let cases = operation_cases(&repo_root().join("conformance/cases")).expect("the case catalog must load");
        let names = operations
            .iter()
            .map(|operation| operation.operation.as_str())
            .filter(|name| selected.as_deref().is_none_or(|selected| selected == *name));
        let mut checked = 0;
        for name in names {
            let entry = verify_entry(name).expect("the operation must have a generated verification entry");
            assert_eq!(entry.cases, cases.get(name).cloned().unwrap_or_default());
            crate::route::verify_operation_route(name).unwrap_or_else(|error| panic!("{name}: {error}"));
            checked += 1;
        }
        assert_eq!(checked, selected.as_ref().map_or(operations.len(), |_| 1));
    }
}
