// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The operation catalog used by repository automation.
//!
//! Responsible for: loading operation IR and suggesting the nearest operation name.
//! NOT responsible for: routing or code generation policy.
//! Upstream: xtask commands. Downstream: `rustfs-gateway-codegen`.

use rustfs_gateway_codegen::{CodegenInput, CodegenOutput};
use rustfs_gateway_model::ir::OperationIr;

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use crate::codegen::repo_root;

pub(crate) fn operations() -> Result<Vec<OperationIr>, String> {
    let root = repo_root();
    rustfs_gateway_codegen::generate(&CodegenInput::at(&root), &CodegenOutput::at(&root))
        .map(|artifacts| artifacts.operations)
        .map_err(|error| error.to_string())
}

#[cfg(feature = "operation")]
pub(crate) fn manual_operations() -> Result<Vec<String>, String> {
    let root = repo_root();
    let mut names: Vec<String> = rustfs_gateway_codegen::generate(&CodegenInput::at(&root), &CodegenOutput::at(&root))
        .map_err(|error| error.to_string())?
        .manual_operations
        .into_iter()
        .collect();
    names.sort();
    Ok(names)
}

#[cfg(feature = "operation")]
pub(crate) fn nearest(operations: &[OperationIr], needle: &str) -> Option<String> {
    operations
        .iter()
        .map(|operation| {
            (
                distance(&needle.to_lowercase(), &operation.operation.to_lowercase()),
                operation.operation.clone(),
            )
        })
        .min()
        .map(|(_, operation)| operation)
}

pub(crate) fn verify_map_path() -> PathBuf {
    repo_root().join("xtask/verify-map.toml")
}

pub(crate) fn render_verify_map(operations: &[OperationIr]) -> Result<String, String> {
    let cases = operation_cases(&repo_root().join("conformance/cases"))?;
    let mut operations: Vec<&OperationIr> = operations.iter().collect();
    operations.sort_by(|left, right| left.operation.cmp(&right.operation));
    let mut out = String::from("# @generated by cargo xtask codegen; do not edit\n\n");
    for operation in operations {
        let cases = cases
            .get(&operation.operation)
            .map(|cases| cases.join(","))
            .unwrap_or_default();
        out.push_str("[[operation]]\n");
        out.push_str(&format!("name = {:?}\n", operation.operation));
        out.push_str(&format!("cases = {cases:?}\n\n"));
    }
    Ok(out)
}

#[cfg(feature = "operation")]
pub(crate) fn verify_entry(name: &str) -> Result<VerifyEntry, String> {
    let body = fs::read_to_string(verify_map_path()).map_err(|error| format!("verify map could not be read: {error}"))?;
    parse_verify_map(&body)
        .into_iter()
        .find(|entry| entry.name == name)
        .ok_or_else(|| format!("verify map has no entry for {name}; run `cargo xtask codegen`"))
}

#[cfg(feature = "operation")]
pub(crate) fn verify_operation_contract(name: &str, mapped_cases: &[String]) -> Result<(), String> {
    let cases = operation_cases(&repo_root().join("conformance/cases"))?;
    verify_operation_contract_with(name, mapped_cases, &cases)
}

/// [`verify_operation_contract`] against a case corpus already read, so a caller checking every
/// operation reads the corpus once rather than once per operation.
#[cfg(feature = "operation")]
fn verify_operation_contract_with(
    name: &str,
    mapped_cases: &[String],
    cases: &BTreeMap<String, Vec<String>>,
) -> Result<(), String> {
    let discovered = cases.get(name).map(Vec::as_slice).unwrap_or_default();
    verify_case_mapping(name, mapped_cases, discovered)?;
    crate::route_contract::verify_operation_route(name)
}

/// The corpus's cases for `name`, in path order: the cases a manually implemented operation is
/// verified against, which has no generated verify-map row to compare the corpus with.
#[cfg(feature = "operation")]
pub(crate) fn corpus_cases(name: &str) -> Result<Vec<String>, String> {
    let cases = operation_cases(&repo_root().join("conformance/cases"))?;
    Ok(cases.get(name).cloned().unwrap_or_default())
}

#[cfg(feature = "operation")]
fn verify_case_mapping(name: &str, mapped: &[String], discovered: &[String]) -> Result<(), String> {
    if mapped == discovered {
        Ok(())
    } else {
        Err(format!(
            "{name} maps cases {mapped:?}, but the corpus contains {discovered:?}; run `cargo xtask codegen`"
        ))
    }
}

#[cfg(feature = "operation")]
pub(crate) fn scaffold_entry(name: &str) -> Result<Option<ScaffoldEntry>, String> {
    let root = repo_root().join("xtask/scaffolds");
    let entries = match fs::read_dir(&root) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(format!("{}: {error}", root.display())),
    };
    for entry in entries {
        let path = entry.map_err(|error| error.to_string())?.path();
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
            continue;
        }
        let body = fs::read_to_string(&path).map_err(|error| format!("{}: {error}", path.display()))?;
        let entry = ScaffoldEntry {
            name: quoted_field(&body, "name = ").unwrap_or_default(),
            test: quoted_field(&body, "test = ").unwrap_or_default(),
        };
        if entry.name == name {
            return Ok(Some(entry));
        }
    }
    Ok(None)
}

#[cfg(feature = "operation")]
pub(crate) struct VerifyEntry {
    pub(crate) name: String,
    pub(crate) cases: Vec<String>,
}

#[cfg(feature = "operation")]
pub(crate) struct ScaffoldEntry {
    pub(crate) name: String,
    pub(crate) test: String,
}

#[cfg(feature = "operation")]
fn parse_verify_map(body: &str) -> Vec<VerifyEntry> {
    let mut entries = Vec::new();
    let mut name: Option<String> = None;
    let mut cases: Option<String> = None;
    for line in body.lines().chain(["[[operation]]"]) {
        if line == "[[operation]]" {
            if let (Some(name), Some(cases)) = (name.take(), cases.take()) {
                entries.push(VerifyEntry {
                    name,
                    cases: split_cases(&cases),
                });
            }
            continue;
        }
        if let Some(value) = quoted_value(line, "name = ") {
            name = Some(value);
        } else if let Some(value) = quoted_value(line, "cases = ") {
            cases = Some(value);
        }
    }
    entries
}

#[cfg(feature = "operation")]
fn split_cases(value: &str) -> Vec<String> {
    value.split(',').filter(|case| !case.is_empty()).map(str::to_owned).collect()
}

fn quoted_value(line: &str, prefix: &str) -> Option<String> {
    line.strip_prefix(prefix)
        .and_then(|value| value.strip_prefix('"'))
        .and_then(|value| value.strip_suffix('"'))
        .map(str::to_owned)
}

#[cfg(feature = "operation")]
fn quoted_field(body: &str, prefix: &str) -> Option<String> {
    body.lines().find_map(|line| quoted_value(line.trim(), prefix))
}

fn operation_cases(root: &Path) -> Result<BTreeMap<String, Vec<String>>, String> {
    let mut paths = Vec::new();
    collect_toml(root, &mut paths)?;
    paths.sort();
    let mut cases: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for path in paths {
        let body = fs::read_to_string(&path).map_err(|error| format!("{}: {error}", path.display()))?;
        let operation = body.lines().find_map(|line| quoted_value(line.trim(), "operation = "));
        let id = body.lines().find_map(|line| quoted_value(line.trim(), "id = "));
        if let (Some(operation), Some(id)) = (operation, id) {
            cases.entry(operation).or_default().push(id);
        }
    }
    Ok(cases)
}

fn collect_toml(root: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    for entry in fs::read_dir(root).map_err(|error| format!("{}: {error}", root.display()))? {
        let path = entry.map_err(|error| error.to_string())?.path();
        if path.is_dir() {
            collect_toml(&path, paths)?;
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("toml") {
            paths.push(path);
        }
    }
    Ok(())
}

#[cfg(feature = "operation")]
fn distance(left: &str, right: &str) -> usize {
    let left: Vec<char> = left.chars().collect();
    let right: Vec<char> = right.chars().collect();
    let mut previous: Vec<usize> = (0..=right.len()).collect();
    let mut current = vec![0; right.len() + 1];
    for (left_index, left_char) in left.iter().enumerate() {
        current[0] = left_index + 1;
        for (right_index, right_char) in right.iter().enumerate() {
            let substitution = previous[right_index] + usize::from(left_char != right_char);
            current[right_index + 1] = substitution.min(previous[right_index + 1] + 1).min(current[right_index] + 1);
        }
        std::mem::swap(&mut previous, &mut current);
    }
    previous[right.len()]
}

#[cfg(test)]
mod tests {
    /// A manually implemented operation has no verify-map row, so its cases are the corpus's own:
    /// `PostObject`'s in path order, and none for a name the corpus does not know.
    #[cfg(feature = "operation")]
    #[test]
    fn a_manual_operation_takes_its_cases_from_the_corpus() {
        let cases = super::corpus_cases("PostObject").expect("the corpus reads");
        assert_eq!(cases.first().map(String::as_str), Some("c-post-0001"));
        assert!(cases.iter().any(|case| case == "c-post-0020"), "{cases:?}");
        assert!(cases.windows(2).all(|pair| pair[0] < pair[1]), "{cases:?}");
        assert!(super::corpus_cases("NoSuchOperation").expect("the corpus reads").is_empty());
    }

    use super::*;
    use std::collections::BTreeSet;

    use rustfs_gateway_core::route::ROUTES;

    #[test]
    fn operation_contract_rejects_a_missing_mapped_case() {
        assert!(verify_case_mapping("GetObject", &[], &["c-object-0001".to_owned()]).is_err());
    }

    #[test]
    fn operation_contract_rejects_an_unmapped_extra_case() {
        assert!(verify_case_mapping("GetObject", &["c-object-0001".to_owned()], &[]).is_err());
    }

    #[test]
    fn generated_map_lists_all_cases_without_a_fake_shared_test() {
        let rendered = render_verify_map(&operations().expect("the operation catalog must load"))
            .expect("the repository case catalog must load");

        assert!(!rendered.contains("test ="));
        assert!(rendered.contains("cases ="));
    }

    #[test]
    fn operation_map_covers_every_generated_operation() {
        let operations = operations().expect("the operation catalog must load");
        let expected = render_verify_map(&operations).expect("the repository case catalog must load");
        let actual = fs::read_to_string(verify_map_path()).expect("the checked-in verify map must load");
        assert_eq!(actual, expected, "the verification map must be regenerated");

        let mapped: BTreeSet<_> = parse_verify_map(&actual).into_iter().map(|entry| entry.name).collect();
        let modeled: BTreeSet<_> = operations.into_iter().map(|operation| operation.operation).collect();
        let manual: BTreeSet<_> = manual_operations()
            .expect("the manual operation catalog must load")
            .into_iter()
            .collect();
        let handler_surface: BTreeSet<_> = modeled.union(&manual).cloned().collect();
        let routed: BTreeSet<_> = ROUTES
            .iter()
            .filter(|row| row.handler_registration)
            .map(|row| row.operation.to_owned())
            .collect();
        let route_only: BTreeSet<_> = ROUTES
            .iter()
            .filter(|row| !row.handler_registration)
            .map(|row| row.operation.to_owned())
            .collect();
        assert_eq!(mapped, modeled);
        assert_eq!(handler_surface, routed);
        assert!(route_only.contains("CreateSession"));
        assert!(mapped.is_disjoint(&route_only));
        assert!(manual.is_disjoint(&route_only));
    }

    /// Every operation's case mapping and runtime route witness. The corpus and the verify map are
    /// read once; each operation's witness still builds the runtime table as `verify --operation`
    /// does, so the operations are spread across the machine's cores instead of checked one after
    /// another, which cost this test about 20 seconds of the crate's 30-second loop.
    #[test]
    fn selected_operation_has_runtime_route_contract() {
        let selected = std::env::var("RUSTFS_GATEWAY_VERIFY_OPERATION").ok();
        let operations = operations().expect("the operation catalog must load");
        let names: Vec<&str> = operations
            .iter()
            .map(|operation| operation.operation.as_str())
            .filter(|name| selected.as_deref().is_none_or(|selected| selected == *name))
            .collect();
        let cases = operation_cases(&repo_root().join("conformance/cases")).expect("the repository case catalog must load");
        let body = fs::read_to_string(verify_map_path()).expect("the checked-in verify map must load");
        let entries = parse_verify_map(&body);
        let lanes = std::thread::available_parallelism().map_or(4, std::num::NonZeroUsize::get);
        let per_lane = names.len().div_ceil(lanes).max(1);
        let checked: usize = std::thread::scope(|scope| {
            let lanes: Vec<_> = names
                .chunks(per_lane)
                .map(|lane| {
                    let (cases, entries) = (&cases, &entries);
                    scope.spawn(move || {
                        let mut done = 0;
                        for name in lane {
                            let entry = entries
                                .iter()
                                .find(|entry| entry.name == *name)
                                .unwrap_or_else(|| panic!("{name}: the operation must have a generated verification entry"));
                            verify_operation_contract_with(name, &entry.cases, cases)
                                .unwrap_or_else(|error| panic!("{name}: {error}"));
                            done += 1;
                        }
                        done
                    })
                })
                .collect();
            lanes
                .into_iter()
                .map(|lane| lane.join().unwrap_or_else(|panic| std::panic::resume_unwind(panic)))
                .sum()
        });
        assert_eq!(checked, selected.as_ref().map_or(operations.len(), |_| 1));
    }
}
