// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `OPERATIONS.md`: the wire-level reverse index.
//!
//! Responsible for: letting an agent start from a failure — a query key, a header, an error code —
//! and reach the operation, without reading `generated/**` or the model.
//! NOT responsible for: field-level bindings, which live in `spec/operations/<Op>.toml`.
//! Upstream: [`rustfs_gateway_model::ir`]. Downstream: every agent that touches an operation.
//!
//! The three reverse tables come first on purpose. The forward table (operation to shape) is the
//! one an agent already has; the entry point in practice is a failing request, not a name.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use rustfs_gateway_model::ir::*;
use rustfs_gateway_model::lower::RouteOnly;

use super::spec_toml::{predicate, type_name};

/// Renders `OPERATIONS.md` for the whole generated set.
pub fn render(
    operations: &[OperationIr],
    route_only: &[RouteOnly],
    route_only_reasons: &BTreeMap<String, String>,
    deferred: &BTreeMap<String, String>,
) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "<!-- @generated by `cargo xtask codegen`. Do not edit: change `overlays/` and regenerate. -->\n\
         # S3 operations\n\n\
         Every wire fact about the operations this gateway implements, derived from the pinned\n\
         Smithy model plus `overlays/`. `generated/**` and `model/s3.json` are on the do-not-read\n\
         list; this file and `spec/operations/<Op>.toml` are what you read instead.\n\n\
         Start from what you have. A failing request gives you a query key, a header or an error\n\
         code — the three reverse indexes below turn any of those into an operation. The forward\n\
         table and the per-operation sections follow.\n"
    );

    let _ = writeln!(out, "## Reverse index: query key to operations\n");
    let _ = writeln!(
        out,
        "An operation marked **(absent)** is selected by a request that does **not** carry the key:\n\
         `PUT /{{Bucket}}` is a bucket creation only while no subresource key is present. Following\n\
         such a row as though the key selected the operation is the opposite of what the table says.\n"
    );
    let _ = writeln!(out, "| Query key | Operations |");
    let _ = writeln!(out, "| --- | --- |");
    for (key, ops) in invert_query_keys(operations) {
        let _ = writeln!(out, "| `{key}` | {} |", links_with_notes(&ops));
    }

    let _ = writeln!(out, "\n## Reverse index: header to operations\n");
    let _ = writeln!(out, "| Header | Operations |");
    let _ = writeln!(out, "| --- | --- |");
    for (header, ops) in invert(operations, |ir| ir.headers()) {
        let _ = writeln!(out, "| `{header}` | {} |", links(&ops));
    }

    let _ = writeln!(out, "\n## Reverse index: error code to operations\n");
    let _ = writeln!(out, "| Error code | Operations |");
    let _ = writeln!(out, "| --- | --- |");
    for (code, ops) in invert(operations, |ir| ir.errors.codes.clone()) {
        let _ = writeln!(out, "| `{code}` | {} |", links(&ops));
    }

    let _ = writeln!(out, "\n## Operations\n");
    let _ = writeln!(
        out,
        "| Operation | Method | Path shape | Query keys | Key headers | Success | Error codes | Quirks |"
    );
    let _ = writeln!(out, "| --- | --- | --- | --- | --- | --- | --- | --- |");
    let mut by_precedence: Vec<&OperationIr> = operations.iter().collect();
    by_precedence.sort_by(|a, b| a.operation.cmp(&b.operation));
    for ir in &by_precedence {
        let _ = writeln!(
            out,
            "| [{}](#{}) | {} | `{}` | {} | {} | {} | {} | {} |",
            ir.operation,
            anchor(&ir.operation),
            ir.http.method.as_str(),
            ir.http.path_shape,
            code_list(&ir.query_keys()),
            code_list(&key_headers(ir)),
            ir.http.success_status,
            code_list(&ir.errors.codes),
            code_list(&ir.quirk_refs),
        );
    }

    let _ = writeln!(
        out,
        "\n**Key headers** are the ones with protocol weight: headers a route matches on, prefix\n\
         header families, and headers carrying a required field. Every other bound header is listed\n\
         in the operation's own section below."
    );

    let _ = writeln!(out, "\n## Route table order\n");
    let _ = writeln!(out, "First match wins; lower precedence is tried first.\n");
    let _ = writeln!(out, "| Precedence | Operation | Predicates |");
    let _ = writeln!(out, "| --- | --- | --- |");
    let mut ordered: Vec<&OperationIr> = operations.iter().collect();
    ordered.sort_by_key(|ir| (ir.http.precedence, ir.operation.clone()));
    for ir in ordered {
        let _ = writeln!(
            out,
            "| {} | [{}](#{}) | {} |",
            ir.http.precedence,
            ir.operation,
            anchor(&ir.operation),
            ir.http
                .predicates
                .iter()
                .map(|p| format!("`{}`", predicate(p)))
                .collect::<Vec<_>>()
                .join(" AND "),
        );
    }

    let _ = writeln!(out, "\n## Operation detail\n");
    for ir in &by_precedence {
        detail(&mut out, ir);
    }

    let _ = writeln!(out, "## Route-only operations\n");
    let _ = writeln!(
        out,
        "Protocol-known request selectors that produce an operation-specific refusal. They emit no\n\
         DTO, codec, operation spec or handler-registration surface.\n"
    );
    let _ = writeln!(out, "| Operation | Method and path | Selector | Reason |");
    let _ = writeln!(out, "| --- | --- | --- | --- |");
    for route in route_only {
        let selectors = route
            .http
            .predicates
            .iter()
            .map(|value| format!("`{}`", predicate(value)))
            .collect::<Vec<_>>()
            .join(" AND ");
        let reason = route_only_reasons
            .get(&route.operation)
            .map_or("route-only operation", String::as_str);
        let _ = writeln!(
            out,
            "| {} | `{} {}` | {} | {} |",
            route.operation,
            route.http.method.as_str(),
            route.http.path_shape,
            selectors,
            reason
        );
    }

    let _ = writeln!(out, "## Deferred operations\n");
    let _ = writeln!(
        out,
        "In the pinned model but deliberately not generated. Codegen fails on any operation that is\n\
         in none of the included, route-only or deferred lists, so these tables are exhaustive by construction.\n"
    );
    let _ = writeln!(out, "| Operation | Reason |");
    let _ = writeln!(out, "| --- | --- |");
    for (op, reason) in deferred {
        let _ = writeln!(out, "| {op} | {reason} |");
    }
    out
}

fn detail(out: &mut String, ir: &OperationIr) {
    let _ = writeln!(out, "### {}\n", ir.operation);
    let _ = writeln!(
        out,
        "`{} {}` &rarr; {} · target {} · precedence {} · auth {} (`{}`, presigned {}) · spec `spec/operations/{}.toml`\n",
        ir.http.method.as_str(),
        ir.http.path_shape,
        ir.http.success_status,
        ir.http.target.as_str(),
        ir.http.precedence,
        ir.auth.requirement.as_str(),
        ir.auth.action,
        if ir.auth.presigned_allowed { "allowed" } else { "refused" },
        ir.operation,
    );

    let _ = writeln!(out, "**Route predicates**\n");
    for p in &ir.http.predicates {
        let _ = writeln!(out, "- `{}`", predicate(p));
    }

    let (present, equals, absent) = query_classes(ir);
    let _ = writeln!(out, "\n**Query keys**\n");
    let _ = writeln!(out, "- routed on, present: {}", code_list(&present));
    let _ = writeln!(out, "- routed on, exact value: {}", code_list(&equals));
    let _ = writeln!(out, "- routed on, absent: {}", code_list(&absent));
    let _ = writeln!(out, "- read as parameters: {}", code_list(&query_parameters(ir)));

    let _ = writeln!(out, "\n**Headers**\n");
    let _ = writeln!(out, "- request: {}", code_list(&headers_of(&ir.input)));
    let _ = writeln!(out, "- response: {}", code_list(&headers_of(&ir.output)));
    let _ = writeln!(out, "- required: {}", code_list(&required_headers(ir)));

    let _ = writeln!(out, "\n**Body**\n");
    let _ = writeln!(
        out,
        "- request: {} ({}{})",
        ir.payload.request.kind.as_str(),
        ir.payload.request.buffering.as_str(),
        cap(ir.payload.request.max_bytes)
    );
    let _ = writeln!(
        out,
        "- response: {} ({}{})",
        ir.payload.response.kind.as_str(),
        ir.payload.response.buffering.as_str(),
        cap(ir.payload.response.max_bytes)
    );
    if let Some(root) = &ir.xml.response_root {
        let _ = writeln!(
            out,
            "- response root: `<{root}>`{}, xmlns {}",
            if ir.xml.unwrapped_output {
                " (unwrapped: the member is the root)"
            } else {
                ""
            },
            ir.xml.xmlns.as_str()
        );
    }
    if !ir.xml.element_order.is_empty() {
        let _ = writeln!(out, "- element order: {}", code_list(&ir.xml.element_order));
    }
    if !ir.xml.url_encoded_fields.is_empty() {
        let _ = writeln!(
            out,
            "- percent-encoded under `encoding-type=url`: {}",
            code_list(&ir.xml.url_encoded_fields)
        );
    }

    let _ = writeln!(out, "\n**Error codes**\n");
    let _ = writeln!(out, "{}", code_list(&ir.errors.codes));
    if let Some(code) = &ir.errors.not_configured {
        let _ = writeln!(out, "\nUnconfigured subresource returns `{code}`.");
    }
    if ir.errors.allows_error_after_200 {
        let _ = writeln!(out, "\nAn `Error` body can follow an already-flushed `200`.");
    }

    if !ir.checksum.request_algorithms.is_empty() || ir.checksum.http_checksum_required {
        let _ = writeln!(out, "\n**Checksums**\n");
        let _ = writeln!(out, "- required before the handler runs: {}", ir.checksum.http_checksum_required);
        let _ = writeln!(
            out,
            "- request algorithms: {}",
            code_list(
                &ir.checksum
                    .request_algorithms
                    .iter()
                    .map(|a| a.as_str().to_owned())
                    .collect::<Vec<_>>()
            )
        );
    }

    let quirks = ir.referenced_quirk_ids();
    if !quirks.is_empty() {
        let _ = writeln!(out, "\n**Quirks**\n");
        for id in &quirks {
            if let Some(q) = ir.quirks.iter().find(|q| q.id == *id) {
                let _ = writeln!(out, "- `{}` ({} on `{}`) — {}", q.id, q.kind, q.target, q.summary);
            }
        }
        let _ = writeln!(out, "\nRun `cargo xtask why <quirk-id>` for the evidence behind any of these.");
    }

    if !ir.shapes.is_empty() {
        let _ = writeln!(out, "\n**Body shapes**\n");
        for (name, shape) in &ir.shapes {
            let members = shape
                .fields
                .iter()
                .map(|f| format!("`{}: {}`", f.name, type_name(&f.ty)))
                .collect::<Vec<_>>()
                .join(", ");
            if members.is_empty() {
                let _ = writeln!(out, "- `{name}` ({})", shape.kind.as_str());
            } else {
                let _ = writeln!(out, "- `{name}` ({}) — {members}", shape.kind.as_str());
            }
        }
    }
    let _ = writeln!(out);
}

fn cap(max: Option<u64>) -> String {
    match max {
        Some(n) => format!(", at most {n} bytes"),
        None => String::new(),
    }
}

fn invert<F>(operations: &[OperationIr], keys: F) -> BTreeMap<String, Vec<String>>
where
    F: Fn(&OperationIr) -> Vec<String>,
{
    let mut index: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for ir in operations {
        for key in keys(ir) {
            index.entry(key).or_default().push(ir.operation.clone());
        }
    }
    for ops in index.values_mut() {
        ops.sort();
        ops.dedup();
    }
    index
}

/// The query-key reverse index, with the absent-only rows marked.
///
/// A key an operation routes on by its *absence* belongs in the index — an agent holding a failing
/// `PUT /b?acl` needs to find the row — but listing it the same way as a key that selects the
/// operation inverts the fact. So the two are distinguished here rather than flattened by
/// [`invert`], which the other two indexes still use because a header or an error code has no
/// negative form.
fn invert_query_keys(operations: &[OperationIr]) -> BTreeMap<String, Vec<(String, bool)>> {
    let mut index: BTreeMap<String, Vec<(String, bool)>> = BTreeMap::new();
    for ir in operations {
        let (present, equals, absent) = query_classes(ir);
        for key in ir.query_keys() {
            // Absent only when nothing else in the operation reads the key: a key that is both a
            // predicate and a parameter is not an absence.
            let absent_only = absent.contains(&key)
                && !present.contains(&key)
                && !equals.iter().any(|spelling| spelling.starts_with(&format!("{key}=")))
                && !query_parameters(ir).contains(&key);
            index.entry(key).or_default().push((ir.operation.clone(), absent_only));
        }
    }
    for ops in index.values_mut() {
        ops.sort();
        ops.dedup();
    }
    index
}

/// The headers with protocol weight: routed on, a prefix family, or carrying a required field.
///
/// Shared with `operations_json`, which reports the same set: two derivations of "key header"
/// would be two answers to the same question, and the reverse index would disagree with the table
/// beside it.
pub(super) fn key_headers(ir: &OperationIr) -> Vec<String> {
    let mut names: Vec<String> = Vec::new();
    for p in &ir.http.predicates {
        match p {
            Predicate::HeaderPresent { header, .. } | Predicate::HeaderPrefix { header, .. } => names.push(header.clone()),
            _ => {}
        }
    }
    for f in ir.input.iter().chain(ir.output.iter()) {
        let interesting = f.binding == Binding::PrefixHeaders || (f.binding == Binding::Header && f.required);
        if interesting && let Some(name) = &f.wire_name {
            names.push(name.clone());
        }
    }
    names.sort();
    names.dedup();
    names
}

fn headers_of(fields: &[Field]) -> Vec<String> {
    let mut names: Vec<String> = fields
        .iter()
        .filter(|f| matches!(f.binding, Binding::Header | Binding::PrefixHeaders))
        .filter_map(|f| f.wire_name.clone())
        .collect();
    names.sort();
    names.dedup();
    names
}

fn required_headers(ir: &OperationIr) -> Vec<String> {
    let mut names: Vec<String> = ir
        .input
        .iter()
        .filter(|f| f.binding == Binding::Header && f.required)
        .filter_map(|f| f.wire_name.clone())
        .collect();
    names.sort();
    names.dedup();
    names
}

fn query_classes(ir: &OperationIr) -> (Vec<String>, Vec<String>, Vec<String>) {
    let mut present = Vec::new();
    let mut equals = Vec::new();
    let mut absent = Vec::new();
    for p in &ir.http.predicates {
        match p {
            Predicate::QueryPresent(k) => present.push(k.clone()),
            Predicate::QueryEquals(k, v) => equals.push(format!("{k}={v}")),
            Predicate::QueryAbsent(k) => absent.push(k.clone()),
            _ => {}
        }
    }
    (present, equals, absent)
}

fn query_parameters(ir: &OperationIr) -> Vec<String> {
    let mut keys: Vec<String> = ir
        .input
        .iter()
        .filter(|f| f.binding == Binding::Query)
        .filter_map(|f| f.wire_name.clone())
        .collect();
    keys.sort();
    keys.dedup();
    keys
}

fn code_list(items: &[String]) -> String {
    if items.is_empty() {
        return "—".to_owned();
    }
    items.iter().map(|i| format!("`{i}`")).collect::<Vec<_>>().join(", ")
}

fn links(ops: &[String]) -> String {
    ops.iter()
        .map(|o| format!("[{o}](#{})", anchor(o)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The same links, with the absent-only rows of the query index marked.
fn links_with_notes(ops: &[(String, bool)]) -> String {
    ops.iter()
        .map(|(operation, absent_only)| {
            let link = format!("[{operation}](#{})", anchor(operation));
            if *absent_only { format!("{link} (absent)") } else { link }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn anchor(operation: &str) -> String {
    operation.to_lowercase()
}
