// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Generated inputs for byte-range parsing and resolution.
//!
//! Responsible for: rendering typed range values consumed in the types crate.
//! NOT responsible for: range behavior or mutation selection. Upstream: typed overlay contract rules. Downstream:
//! `rustfs-gateway-types::scalar::range`.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use rustfs_gateway_model::{
    ContractRule, ContractValue, ExplicitEndOverflowPolicyValue, InvalidRangePolicyValue, MultiRangePolicyValue,
    MutationDimension, OpenEndedRangePolicyValue, OversizeSuffixPolicyValue, RangeStartBoundValue, SuffixRangePolicyValue,
};

use super::dto::LICENSE;

/// Renders the byte-range contract module included by the types crate.
pub fn render(rules: &BTreeMap<String, ContractRule>) -> Result<String, String> {
    let mut out = String::from(LICENSE);
    out.push_str("\n// Generated byte-range protocol-contract inputs.\n\n");
    render_enum(
        &mut out,
        "MULTI_RANGE_POLICY",
        "Multiple-range policy.",
        match unique(rules, MutationDimension::MultiRangePolicy)? {
            ContractValue::MultiRangePolicy(MultiRangePolicyValue::ServeWhole) => "MultiRangePolicy::ServeWhole",
            ContractValue::MultiRangePolicy(MultiRangePolicyValue::Reject) => "MultiRangePolicy::Reject",
            _ => return Err(wrong_type(MutationDimension::MultiRangePolicy)),
        },
        "MultiRangePolicy",
    );
    render_enum(
        &mut out,
        "EXPLICIT_END_OVERFLOW_POLICY",
        "Explicit range-end overflow policy.",
        match unique(rules, MutationDimension::ExplicitEndOverflowPolicy)? {
            ContractValue::ExplicitEndOverflowPolicy(ExplicitEndOverflowPolicyValue::Clamp) => "ExplicitEndOverflowPolicy::Clamp",
            ContractValue::ExplicitEndOverflowPolicy(ExplicitEndOverflowPolicyValue::Unsatisfiable) => {
                "ExplicitEndOverflowPolicy::Unsatisfiable"
            }
            _ => return Err(wrong_type(MutationDimension::ExplicitEndOverflowPolicy)),
        },
        "ExplicitEndOverflowPolicy",
    );
    render_enum(
        &mut out,
        "SUFFIX_RANGE_POLICY",
        "Suffix-range support policy.",
        match unique(rules, MutationDimension::SuffixRangePolicy)? {
            ContractValue::SuffixRangePolicy(SuffixRangePolicyValue::Supported) => "SuffixRangePolicy::Supported",
            ContractValue::SuffixRangePolicy(SuffixRangePolicyValue::Ignore) => "SuffixRangePolicy::Ignore",
            _ => return Err(wrong_type(MutationDimension::SuffixRangePolicy)),
        },
        "SuffixRangePolicy",
    );
    render_enum(
        &mut out,
        "OVERSIZE_SUFFIX_POLICY",
        "Oversized suffix-range policy.",
        match unique(rules, MutationDimension::OversizeSuffixPolicy)? {
            ContractValue::OversizeSuffixPolicy(OversizeSuffixPolicyValue::ClampToWholePartial) => {
                "OversizeSuffixPolicy::ClampToWholePartial"
            }
            ContractValue::OversizeSuffixPolicy(OversizeSuffixPolicyValue::Unsatisfiable) => {
                "OversizeSuffixPolicy::Unsatisfiable"
            }
            _ => return Err(wrong_type(MutationDimension::OversizeSuffixPolicy)),
        },
        "OversizeSuffixPolicy",
    );
    render_enum(
        &mut out,
        "INVALID_RANGE_POLICY",
        "Invalid range policy.",
        match unique(rules, MutationDimension::InvalidRangePolicy)? {
            ContractValue::InvalidRangePolicy(InvalidRangePolicyValue::ServeWhole) => "InvalidRangePolicy::ServeWhole",
            ContractValue::InvalidRangePolicy(InvalidRangePolicyValue::Reject) => "InvalidRangePolicy::Reject",
            _ => return Err(wrong_type(MutationDimension::InvalidRangePolicy)),
        },
        "InvalidRangePolicy",
    );
    render_enum(
        &mut out,
        "RANGE_START_BOUND",
        "Range-start boundary policy.",
        match unique(rules, MutationDimension::RangeStartBound)? {
            ContractValue::RangeStartBound(RangeStartBoundValue::AtOrBeyondUnsatisfiable) => {
                "RangeStartBoundPolicy::AtOrBeyondUnsatisfiable"
            }
            ContractValue::RangeStartBound(RangeStartBoundValue::PastEndOnly) => "RangeStartBoundPolicy::PastEndOnly",
            _ => return Err(wrong_type(MutationDimension::RangeStartBound)),
        },
        "RangeStartBoundPolicy",
    );
    render_enum(
        &mut out,
        "OPEN_ENDED_RANGE_POLICY",
        "Open-ended range policy.",
        match unique(rules, MutationDimension::OpenEndedRangePolicy)? {
            ContractValue::OpenEndedRangePolicy(OpenEndedRangePolicyValue::ThroughLast) => "OpenEndedRangePolicy::ThroughLast",
            ContractValue::OpenEndedRangePolicy(OpenEndedRangePolicyValue::EmptyAtLast) => "OpenEndedRangePolicy::EmptyAtLast",
            _ => return Err(wrong_type(MutationDimension::OpenEndedRangePolicy)),
        },
        "OpenEndedRangePolicy",
    );
    Ok(out)
}

fn render_enum(out: &mut String, name: &str, docs: &str, value: &str, ty: &str) {
    writeln!(out, "/// {docs}\nconst {name}: {ty} = {value};").expect("writing to String cannot fail");
}

fn unique(rules: &BTreeMap<String, ContractRule>, dimension: MutationDimension) -> Result<&ContractValue, String> {
    let mut matches = rules.values().filter(|rule| rule.mutation_dimension == dimension);
    let value = matches
        .next()
        .ok_or_else(|| format!("missing `{}` contract rule", dimension.as_str()))?;
    if matches.next().is_some() {
        return Err(format!("multiple `{}` contract rules", dimension.as_str()));
    }
    Ok(&value.current)
}

fn wrong_type(dimension: MutationDimension) -> String {
    format!("`{}` contract carries the wrong typed value", dimension.as_str())
}
