// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The Rust data artefacts consumed by runtime and proc-macro crates.
//!
//! Responsible for: `routes.rs` (the ordered first-match route table) and `error_codes.rs` (the
//! error code to operation index) under `generated/`, plus the proc-macro operation-name table.
//! NOT responsible for: defining the types they mention. The route and error files are `include!`
//! fodder for the crate that owns `RouteRow`, `RoutePredicate` and `ErrorCodeRow` (P4); a generated
//! file that minted its own public type names would put names into the tree that `grep` cannot
//! trace back to a hand-written declaration.
//! Upstream: [`rustfs_gateway_model::ir`]. Downstream: P4's route table.
//!
//! No AWS prose is copied into either file: the only English in them is written here.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use rustfs_gateway_model::ir::*;

const LICENSE: &str = "\
// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
";

/// Renders the operation-name table consumed by `#[rustfs_gateway::handlers]`.
pub fn macro_operation_names(operations: &[OperationIr]) -> String {
    let mut names: Vec<&str> = operations.iter().map(|operation| operation.operation.as_str()).collect();
    names.sort_unstable();

    let mut out = String::from(LICENSE);
    let _ = writeln!(
        out,
        "\n// @generated by `cargo xtask codegen`. Do not edit.\n\
         //\n\
         //! The AWS operation names accepted by `#[rustfs_gateway::handlers]`.\n\
         //!\n\
         //! Responsible for: [`OPERATION_NAMES`] and [`SNAKE_ALIASES`].\n\
         //! NOT responsible for: method-name conversion or diagnostics (`crate::mapping`).\n\
         //! Upstream: the lowered operation IR. Downstream: `crate::mapping`.\n"
    );
    let _ = writeln!(out, "pub(crate) static OPERATION_NAMES: &[&str] = &[");
    for name in names {
        let _ = writeln!(out, "    \"{name}\",");
    }
    let _ = writeln!(out, "];");
    let _ = writeln!(
        out,
        "\n/// Method aliases for operation names whose mechanical snake-case form is a Rust keyword.\n\
         pub(crate) static SNAKE_ALIASES: &[(&str, &str)] = &[];"
    );
    out
}

/// Renders the ordered route table.
pub fn routes(operations: &[OperationIr]) -> String {
    let mut out = String::from(LICENSE);
    let _ = writeln!(
        out,
        "\n// @generated by `cargo xtask codegen`. Do not edit.\n\
         //\n\
         // Ordered first-match route table. Lower precedence is tried first. Data only: the\n\
         // including crate defines `RouteRow` and `RoutePredicate`.\n"
    );
    let mut ordered: Vec<&OperationIr> = operations.iter().collect();
    ordered.sort_by_key(|ir| (ir.http.precedence, ir.operation.clone()));

    let _ = writeln!(out, "pub static ROUTES: &[RouteRow] = &[");
    for ir in ordered {
        let _ = writeln!(out, "    RouteRow {{");
        let _ = writeln!(out, "        operation: \"{}\",", ir.operation);
        let _ = writeln!(out, "        precedence: {},", ir.http.precedence);
        let _ = writeln!(out, "        method: \"{}\",", ir.http.method.as_str());
        let _ = writeln!(out, "        target: \"{}\",", ir.http.target.as_str());
        let _ = writeln!(out, "        path_shape: \"{}\",", ir.http.path_shape);
        let _ = writeln!(out, "        success_status: {},", ir.http.success_status);
        let _ = writeln!(out, "        predicates: &[");
        for p in &ir.http.predicates {
            let _ = writeln!(out, "            {},", predicate(p));
        }
        let _ = writeln!(out, "        ],");
        let _ = writeln!(out, "    }},");
    }
    let _ = writeln!(out, "];");
    out
}

fn predicate(p: &Predicate) -> String {
    match p {
        Predicate::Method(m) => format!("RoutePredicate::Method(\"{}\")", m.as_str()),
        Predicate::Target(t) => format!("RoutePredicate::Target(\"{}\")", t.as_str()),
        Predicate::QueryPresent(k) => format!("RoutePredicate::QueryPresent(\"{k}\")"),
        Predicate::QueryEquals(k, v) => format!("RoutePredicate::QueryEquals(\"{k}\", \"{v}\")"),
        Predicate::QueryAbsent(k) => format!("RoutePredicate::QueryAbsent(\"{k}\")"),
        Predicate::HeaderPresent { header, negated } => {
            format!("RoutePredicate::HeaderPresent(\"{header}\", {negated})")
        }
        Predicate::HeaderPrefix { header, prefix } => format!("RoutePredicate::HeaderPrefix(\"{header}\", \"{prefix}\")"),
        Predicate::PathLiteral(path) => format!("RoutePredicate::PathLiteral(\"{path}\")"),
    }
}

/// Renders the error code index.
///
/// The code to HTTP status mapping deliberately does **not** live here: it is owned by
/// `rustfs-gateway-types::ErrorCode`, and a second copy generated from the IR would be exactly the
/// "one rule in two places" failure the whole spec pipeline exists to prevent. What the IR knows
/// and the status table cannot express is which operations produce a code, and which code an
/// operation returns for an unconfigured subresource.
pub fn error_codes(operations: &[OperationIr]) -> String {
    let mut index: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for ir in operations {
        for code in &ir.errors.codes {
            index.entry(code.as_str()).or_default().push(ir.operation.as_str());
        }
    }
    for ops in index.values_mut() {
        ops.sort_unstable();
        ops.dedup();
    }

    let mut out = String::from(LICENSE);
    let _ = writeln!(
        out,
        "\n// @generated by `cargo xtask codegen`. Do not edit.\n\
         //\n\
         // Which operations can produce which error code, and the per-operation code for an\n\
         // unconfigured bucket subresource. The code to HTTP status mapping is NOT here: it is\n\
         // owned by `rustfs-gateway-types::ErrorCode`, and a generated second copy would be able to\n\
         // disagree with it. Data only: the including crate defines the row types.\n"
    );
    let _ = writeln!(out, "pub static ERROR_CODE_OPERATIONS: &[(&str, &[&str])] = &[");
    for (code, ops) in &index {
        let list = ops.iter().map(|o| format!("\"{o}\"")).collect::<Vec<_>>().join(", ");
        let _ = writeln!(out, "    (\"{code}\", &[{list}]),");
    }
    let _ = writeln!(out, "];\n");

    let not_configured: Vec<String> = operations
        .iter()
        .filter_map(|ir| {
            ir.errors
                .not_configured
                .as_ref()
                .map(|code| format!("    (\"{}\", \"{code}\"),", ir.operation))
        })
        .collect();
    let _ = writeln!(out, "{}", table("NOT_CONFIGURED_CODES: &[(&str, &str)]", &not_configured));

    let after_200: Vec<String> = operations
        .iter()
        .filter(|ir| ir.errors.allows_error_after_200)
        .map(|ir| format!("    \"{}\",", ir.operation))
        .collect();
    let _ = write!(out, "{}", table("ERROR_AFTER_200: &[&str]", &after_200));
    out
}

/// Renders a static slice, collapsing the empty case to `&[];` so a generated file never carries
/// a two-line spelling of "nothing".
fn table(declaration: &str, rows: &[String]) -> String {
    if rows.is_empty() {
        return format!("pub static {declaration} = &[];\n");
    }
    format!("pub static {declaration} = &[\n{}\n];\n", rows.join("\n"))
}
