// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! The text of the generated seam: member matching, `Option`/container wrapping, and the files.
//!
//! Responsible for: pairing each gateway member with its s3s member (same name, the checksum
//! fan-out, runtime members, [`super::overrides::MEMBERS`]), wrapping the pair's conversion for
//! the two sides' optionality, and laying out the operation, shape and facade files.
//! NOT responsible for: the type pairing itself ([`super::expr`]).
//! Upstream: [`super`]. Downstream: `generated/dto/seam/**`.

use std::fmt::Write as _;

use rustfs_gateway_model::ir::{Binding, Field, OperationIr, Shape, ShapeKind, Type};

use super::expr::{Ctx, gateway_shape};
use super::facts::S3sType;
use super::overrides::{self, Rule};
use crate::emit::dto::naming;
use crate::emit::dto::registry::Registry;

pub(super) const HEADER: &str = "\
// Copyright 2026 RustFS Team
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by `cargo xtask codegen` (crates/codegen/src/emit/seam). Do not edit.
";

const IMPORTS: &str = "\
#[allow(unused_imports)] // Not every conversion needs a leaf function.
use crate::compat::s3s_0_17_0::leaf;
use crate::compat::s3s_0_17_0::s3s;
use crate::compat::ConversionError;
";

/// The s3s checksum members one gateway `ChecksumSpec` fans out to, with the algorithm each holds.
const CHECKSUM_FAN_OUT: [(&str, &str); 10] = [
    ("checksum_crc32", "Crc32"),
    ("checksum_crc32c", "Crc32c"),
    ("checksum_crc64nvme", "Crc64Nvme"),
    ("checksum_md5", "Md5"),
    ("checksum_sha1", "Sha1"),
    ("checksum_sha256", "Sha256"),
    ("checksum_sha512", "Sha512"),
    ("checksum_xxhash128", "XxHash128"),
    ("checksum_xxhash3", "XxHash3"),
    ("checksum_xxhash64", "XxHash64"),
];

fn member_rule(owner: &str, member: &str) -> Option<Rule> {
    overrides::MEMBERS
        .iter()
        .find(|(o, m, _)| *o == owner && *m == member)
        .map(|(_, _, rule)| *rule)
}

fn bare_name(field: &Field) -> String {
    naming::field_name(&field.name).trim_start_matches("r#").to_owned()
}

/// Which s3s member a gateway member lands in, or why none.
enum Target<'s> {
    Member(&'s str, &'s S3sType),
    ChecksumFanOut,
    GatewayOnly(&'static str),
    CarriedByHeaders,
    /// The adapter supplies the s3s member's value as a parameter.
    Supplied(&'s str, &'s S3sType),
    /// The gateway member is the same-named member of the s3s struct held in this s3s member.
    Nested(&'s str, &'s str, &'s S3sType, &'s str),
}

fn find<'s>(s3s: &'s [(String, S3sType)], wanted: &str) -> Option<(&'s str, &'s S3sType)> {
    // s3s spells a member whose snake name is a Rust keyword with a trailing underscore.
    let escaped = format!("{wanted}_");
    s3s.iter()
        .find(|(member, _)| *member == wanted)
        .or_else(|| s3s.iter().find(|(member, _)| *member == escaped))
        .map(|(member, ty)| (member.as_str(), ty))
}

fn target<'s>(ctx: &Ctx<'s>, owner: &str, field: &Field, s3s: &'s [(String, S3sType)]) -> Result<Target<'s>, String> {
    let name = bare_name(field);
    let wanted = match member_rule(owner, &name) {
        Some(Rule::GatewayOnly(reason)) => return Ok(Target::GatewayOnly(reason)),
        Some(Rule::CarriedByHeaders(_)) => return Ok(Target::CarriedByHeaders),
        Some(Rule::Supplied(_)) => {
            let (member, ty) = find(s3s, &name).ok_or_else(|| format!("{owner}.{name}: no s3s member to supply"))?;
            return Ok(Target::Supplied(member, ty));
        }
        Some(Rule::Nested(parent)) => {
            let (parent, parent_ty) = find(s3s, parent).ok_or_else(|| format!("{owner}.{name}: no s3s member `{parent}`"))?;
            let S3sType::Struct(nested) = parent_ty.unwrap_option().0 else {
                return Err(format!("{owner}.{name}: `{parent}` is not a struct member"));
            };
            let nested_fields = ctx
                .facts
                .structs
                .get(nested)
                .ok_or_else(|| format!("{owner}.{name}: `{nested}` is not an s3s struct"))?;
            let (member, ty) =
                find(nested_fields, &name).ok_or_else(|| format!("{owner}.{name}: `{nested}` has no member `{name}`"))?;
            return Ok(Target::Nested(parent, nested.as_str(), ty, member));
        }
        Some(Rule::Rename(to)) => to.to_owned(),
        Some(Rule::S3sOnly(_) | Rule::FromQuery(_) | Rule::FromBoolHeader(_) | Rule::AbsentAsEmpty(_)) | None => name.clone(),
    };
    if matches!(field.ty, Type::ChecksumSpec) {
        return Ok(Target::ChecksumFanOut);
    }
    let (member, ty) = find(s3s, &wanted).ok_or_else(|| format!("{owner}.{name}: the s3s struct has no member `{wanted}`"))?;
    if let Some(Rule::S3sOnly(_) | Rule::FromQuery(_) | Rule::FromBoolHeader(_)) = member_rule(owner, member) {
        return Err(format!(
            "{owner}.{member}: stale override, a gateway member now fills it; delete the legacy-only entry"
        ));
    }
    Ok(Target::Member(member, ty))
}

/// One struct-literal field, in shorthand when the value is the same-named local.
fn push_field(body: &mut String, name: &str, value: &str) {
    if name == value {
        let _ = writeln!(body, "        {name},");
    } else {
        let _ = writeln!(body, "        {name}: {value},");
    }
}

fn is_container(ty: &Type) -> bool {
    Registry::is_container(ty)
}

fn missing(field: &str, reason: &str) -> String {
    format!("return Err(ConversionError {{ field: \"{field}\", reason: \"{reason}\" }})")
}

/// Whether an empty value of this gateway member is absent on the legacy side: the legacy decoder
/// reads an optional header whose value is empty as no value at all, before parsing it, so a
/// textual header member the gateway holds as `Some("")` crosses as `None` (rustfs/gateway#1076).
fn empty_is_absent(field: &Field) -> bool {
    field.binding == Binding::Header
        && !field.required
        && matches!(field.ty, Type::String | Type::OpaqueString | Type::StringEnum(_) | Type::Range)
        && !crate::emit::dto::registry::is_secret_string_field(field)
}

/// The parameter a conversion takes when a legacy-only member is decoded from the raw request.
const WIRE_PARAMETER: (&str, &str) = ("wire", "&leaf::RequestWire<'_>");

/// The s3s struct literal for the gateway value `src` of a struct with `fields`.
pub(super) fn forward_struct(ctx: &Ctx<'_>, owner: &str, fields: &[Field], src: &str) -> Result<String, Vec<String>> {
    let Some(s3s) = ctx.facts.structs.get(owner) else {
        return Err(vec![format!("{owner}: not an s3s struct")]);
    };
    let mut errors = Vec::new();
    let mut prelude = String::new();
    let mut assigned: Vec<(String, String)> = Vec::new();
    let mut fan_out = false;
    for field in fields {
        let name = bare_name(field);
        let mut access = format!("{src}.{}", naming::field_name(&field.name));
        if empty_is_absent(field) {
            access = format!("{access}.filter(|x| !x.as_str().is_empty())");
        }
        match target(ctx, owner, field, s3s) {
            Err(error) => errors.push(error),
            Ok(Target::CarriedByHeaders) => {}
            Ok(Target::Nested(..)) => errors.push(format!("{owner}.{name}: a nested member is backward only")),
            Ok(Target::Supplied(member, ty)) => match ty {
                S3sType::Leaf(leaf) => {
                    ctx.supplied
                        .borrow_mut()
                        .push((member.to_owned(), format!("s3s::dto::{leaf}")));
                    assigned.push((member.to_owned(), member.to_owned()));
                }
                other => errors.push(format!("{owner}.{name}: only a required leaf can be supplied, not {other:?}")),
            },
            Ok(Target::GatewayOnly(reason)) => {
                let present = if is_container(&field.ty) {
                    format!("!{access}.is_empty()")
                } else if field.required {
                    errors.push(format!("{owner}.{name}: a required gateway member cannot be gateway-only"));
                    continue;
                } else {
                    format!("{access}.is_some()")
                };
                let _ = writeln!(prelude, "    if {present} {{\n        {};\n    }}", missing(&name, reason));
            }
            Ok(Target::ChecksumFanOut) => {
                if field.required {
                    errors.push(format!("{owner}.{name}: a required checksum spec has no fan-out"));
                    continue;
                }
                let _ = writeln!(prelude, "    let checksum_spec = {access};");
                fan_out = true;
            }
            Ok(Target::Member(member, ty)) => {
                let (core, optional) = ty.unwrap_option();
                // The SSE-C customer key is a secret type on the gateway side and a plain string in
                // the s3s input; that is the s3s contract, not this one's.
                let conv = if crate::emit::dto::registry::is_secret_string_field(field) && super::expr::is_string(core) {
                    Ok("x.expose_secret().to_owned()".to_owned())
                } else {
                    ctx.forward(&field.ty, core, "x", &name)
                };
                match conv {
                    Err(error) => {
                        errors.push(format!("{owner}.{name}: {error}"));
                        // Claimed, so the member is reported once, for the pair, not again as unfilled.
                        assigned.push((member.to_owned(), String::new()));
                    }
                    Ok(conv) => {
                        let value = wrap_forward(field, optional, &access, &conv, &name);
                        assigned.push((member.to_owned(), value));
                    }
                }
            }
        }
    }
    if fields.is_empty() {
        let _ = writeln!(prelude, "    let _ = {src};");
    }
    let mut body = String::new();
    for (member, ty) in s3s {
        if let Some((_, value)) = assigned.iter().find(|(m, _)| m == member) {
            push_field(&mut body, member, value);
            continue;
        }
        if fan_out && let Some((_, algorithm)) = CHECKSUM_FAN_OUT.iter().find(|(m, _)| m == member) {
            let _ = writeln!(
                body,
                "        {member}: leaf::checksum_value(checksum_spec.as_ref(), crate::ChecksumAlgorithm::{algorithm}),"
            );
            continue;
        }
        let runtime = matches!(ty.unwrap_option().0, S3sType::Opaque);
        if runtime || matches!(member_rule(owner, member), Some(Rule::S3sOnly(_))) {
            let _ = writeln!(body, "        {member}: Default::default(),");
            continue;
        }
        let decoded = match (member_rule(owner, member), ty) {
            (Some(Rule::FromQuery(parameter)), S3sType::Option(inner)) if matches!(inner.as_ref(), S3sType::Leaf(l) if l == "String") => {
                Some(format!("leaf::legacy_query(wire, \"{parameter}\")?"))
            }
            (Some(Rule::FromBoolHeader(header)), S3sType::Option(inner)) if matches!(inner.as_ref(), S3sType::Leaf(l) if l == "bool") => {
                Some(format!("leaf::legacy_bool_header(wire, \"{header}\")?"))
            }
            (Some(Rule::FromQuery(_) | Rule::FromBoolHeader(_)), other) => {
                errors.push(format!("{owner}.{member}: no legacy wire decoding for {other:?}"));
                continue;
            }
            _ => None,
        };
        if let Some(decoded) = decoded {
            let mut supplied = ctx.supplied.borrow_mut();
            if !supplied.iter().any(|(name, _)| name == WIRE_PARAMETER.0) {
                supplied.push((WIRE_PARAMETER.0.to_owned(), WIRE_PARAMETER.1.to_owned()));
            }
            push_field(&mut body, member, &decoded);
            continue;
        }
        errors.push(format!("{owner}.{member}: an s3s member no gateway member fills"));
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    Ok(format!("{prelude}    Ok(s3s::dto::{owner} {{\n{body}    }})\n"))
}

fn wrap_forward(field: &Field, s3s_optional: bool, access: &str, conv: &str, name: &str) -> String {
    let direct = conv == "x";
    let apply = |v: &str| {
        if direct {
            v.to_owned()
        } else if v == "x" {
            conv.to_owned()
        } else {
            format!("{{ let x = {v}; {conv} }}")
        }
    };
    if is_container(&field.ty) {
        return if s3s_optional {
            format!("if {access}.is_empty() {{ None }} else {{ Some({}) }}", apply(access))
        } else {
            apply(access)
        };
    }
    match (field.required, s3s_optional) {
        (true, true) => format!("Some({})", apply(access)),
        (true, false) => apply(access),
        (false, true) if direct => access.to_owned(),
        (false, true) => format!("{access}.map(|x| -> Result<_, ConversionError> {{ Ok({conv}) }}).transpose()?"),
        (false, false) => format!(
            "match {access} {{ Some(x) => {}, None => {} }}",
            apply("x"),
            missing(name, "the s3s shape requires this member")
        ),
    }
}

/// The gateway struct literal of type `gw_type` for the destructured s3s value.
pub(super) fn backward_struct(
    ctx: &Ctx<'_>,
    owner: &str,
    fields: &[Field],
    gw_type: &str,
    src: &str,
) -> Result<String, Vec<String>> {
    let Some(s3s) = ctx.facts.structs.get(owner) else {
        return Err(vec![format!("{owner}: not an s3s struct")]);
    };
    let mut errors = Vec::new();
    let mut used: Vec<&str> = Vec::new();
    // Nested parents: (s3s member, nested struct, nested members taken).
    let mut nested: Vec<(&str, &str, Vec<&str>)> = Vec::new();
    let mut body = String::new();
    for field in fields {
        let name = bare_name(field);
        let gw_name = naming::field_name(&field.name);
        match target(ctx, owner, field, s3s) {
            Err(error) => errors.push(error),
            Ok(Target::Supplied(..)) => errors.push(format!("{owner}.{name}: a supplied member is forward only")),
            Ok(Target::GatewayOnly(_) | Target::CarriedByHeaders) => {
                if field.required && !is_container(&field.ty) {
                    errors.push(format!("{owner}.{name}: a required gateway member cannot be gateway-only"));
                }
                let _ = writeln!(body, "        {gw_name}: Default::default(),");
            }
            Ok(Target::ChecksumFanOut) => {
                let present: Vec<&str> = CHECKSUM_FAN_OUT
                    .iter()
                    .filter(|(m, _)| s3s.iter().any(|(s, _)| s == m))
                    .map(|(m, _)| *m)
                    .collect();
                used.extend(present.iter().copied());
                let list = CHECKSUM_FAN_OUT
                    .iter()
                    .filter(|(m, _)| present.contains(m))
                    .map(|(m, a)| format!("(\"{m}\", crate::ChecksumAlgorithm::{a}, {m})"))
                    .collect::<Vec<_>>()
                    .join(", ");
                let wrap = if field.required { "?.unwrap_or_default()" } else { "?" };
                let _ = writeln!(body, "        {gw_name}: leaf::checksum_spec_from_s3s([{list}]){wrap},");
            }
            Ok(Target::Nested(parent, nested_struct, ty, member)) => {
                match nested.iter_mut().find(|(p, _, _)| *p == parent) {
                    Some((_, _, taken)) => taken.push(member),
                    None => {
                        used.push(parent);
                        nested.push((parent, nested_struct, vec![member]));
                    }
                }
                let (core, optional) = ty.unwrap_option();
                match ctx.backward(core, &field.ty, &field.name, "x", &name) {
                    Err(error) => errors.push(format!("{owner}.{name}: {error}")),
                    Ok(conv) => {
                        let source = format!("{parent}.{member}");
                        let value = wrap_backward(field, optional, &source, &conv, &name);
                        push_field(&mut body, &gw_name, &value);
                    }
                }
            }
            Ok(Target::Member(member, ty)) => {
                used.push(member);
                let (core, optional) = ty.unwrap_option();
                match ctx.backward(core, &field.ty, &field.name, "x", &name) {
                    Err(error) => errors.push(format!("{owner}.{name}: {error}")),
                    Ok(conv) if field.required && matches!(member_rule(owner, member), Some(Rule::AbsentAsEmpty(_))) => {
                        match absent_as_empty(field, optional, member, &conv, &name) {
                            Ok(value) => push_field(&mut body, &gw_name, &value),
                            Err(error) => errors.push(format!("{owner}.{name}: {error}")),
                        }
                    }
                    Ok(conv) => {
                        let value = wrap_backward(field, optional, member, &conv, &name);
                        push_field(&mut body, &gw_name, &value);
                    }
                }
            }
        }
    }
    let mut pattern = String::new();
    let mut refusals = String::new();
    for (member, ty) in s3s {
        if used.contains(&member.as_str()) {
            let _ = writeln!(pattern, "        {member},");
        } else if matches!(ty, S3sType::Option(inner) if matches!(inner.as_ref(), S3sType::Opaque)) {
            // A runtime value with no wire form, such as the deferred completion a legacy body may
            // hand the legacy writer to stream behind keep-alive whitespace: the gateway writes an
            // output once and cannot carry it, so a set one is refused by name rather than dropped
            // (rustfs/gateway#1076); an unset one crosses as nothing.
            let _ = writeln!(pattern, "        {member},");
            let _ = writeln!(
                refusals,
                "    if {member}.is_some() {{\n        {};\n    }}",
                missing(member, "a runtime value with no wire form, which the gateway output cannot carry")
            );
        } else if matches!(ty.unwrap_option().0, S3sType::Opaque) {
            // A cache the legacy type derives from the members beside it: nothing is lost with it.
            let _ = writeln!(pattern, "        {member}: _,");
        } else if matches!(member_rule(owner, member), Some(Rule::S3sOnly(_))) {
            // The gateway shape cannot hold it, so a value is refused by name rather than dropped
            // (rustfs/gateway#1076); an unset one crosses as nothing, as it would have.
            let present = match ty {
                S3sType::Option(_) => format!("{member}.is_some()"),
                S3sType::Vec(_) => format!("!{member}.is_empty()"),
                other => {
                    errors.push(format!(
                        "{owner}.{member}: a required legacy-only member {other:?} cannot be refused when set"
                    ));
                    continue;
                }
            };
            let _ = writeln!(pattern, "        {member},");
            let _ = writeln!(
                refusals,
                "    if {present} {{\n        {};\n    }}",
                missing(member, "a legacy member the gateway shape cannot hold, refused rather than dropped")
            );
        } else if matches!(member_rule(owner, member), Some(Rule::FromQuery(_) | Rule::FromBoolHeader(_))) {
            errors.push(format!("{owner}.{member}: a member decoded from the raw request is forward only"));
        } else {
            errors.push(format!("{owner}.{member}: an s3s member no gateway member takes"));
        }
    }
    let mut unnest = String::new();
    for (parent, nested_struct, taken) in &nested {
        let Some(nested_fields) = ctx.facts.structs.get(*nested_struct) else {
            continue;
        };
        for (member, ty) in nested_fields {
            let runtime = matches!(ty.unwrap_option().0, S3sType::Opaque);
            if !taken.contains(&member.as_str())
                && !runtime
                && !matches!(member_rule(nested_struct, member), Some(Rule::S3sOnly(_)))
            {
                errors.push(format!("{nested_struct}.{member}: a nested s3s member no gateway member takes"));
            }
        }
        let _ = writeln!(unnest, "    let {parent} = {parent}.unwrap_or_default();");
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    Ok(format!(
        "    let s3s::dto::{owner} {{\n{pattern}    }} = {src};\n{refusals}{unnest}    Ok({gw_type} {{\n{body}    }})\n"
    ))
}

/// [`Rule::AbsentAsEmpty`] on a required gateway member: an unset legacy string is the empty gateway
/// string, and a set empty one is refused by name, since the gateway would write it as unset. On an
/// optional gateway member the rule changes nothing, and the member converts as any other: an unset
/// legacy value is already the unset gateway value.
fn absent_as_empty(field: &Field, s3s_optional: bool, member: &str, conv: &str, name: &str) -> Result<String, String> {
    if !(s3s_optional && matches!(field.ty, Type::String) && conv == "x") {
        return Err("AbsentAsEmpty applies only to a gateway string whose legacy member is an optional string".to_owned());
    }
    Ok(format!(
        "match {member} {{ Some(x) if x.is_empty() => {}, Some(x) => x, None => String::new() }}",
        missing(name, "an empty legacy value the gateway would write as unset")
    ))
}

fn wrap_backward(field: &Field, s3s_optional: bool, member: &str, conv: &str, name: &str) -> String {
    let direct = conv == "x";
    let apply = |v: &str| {
        if direct {
            v.to_owned()
        } else if v == "x" {
            conv.to_owned()
        } else {
            format!("{{ let x = {v}; {conv} }}")
        }
    };
    if is_container(&field.ty) {
        return if s3s_optional && direct {
            format!("{member}.unwrap_or_default()")
        } else if s3s_optional {
            format!("match {member} {{ Some(x) => {}, None => Default::default() }}", apply("x"))
        } else {
            apply(member)
        };
    }
    match (field.required, s3s_optional) {
        (false, true) if direct => member.to_owned(),
        (false, true) => format!("{member}.map(|x| -> Result<_, ConversionError> {{ Ok({conv}) }}).transpose()?"),
        (false, false) => format!("Some({})", apply(member)),
        (true, false) => apply(member),
        (true, true) => format!(
            "match {member} {{ Some(x) => {}, None => {} }}",
            apply("x"),
            missing(name, "the gateway shape requires this member")
        ),
    }
}

/// The body of an operation's `answer_from_legacy`: every legacy output member a response header
/// the RustFS body set itself would replace on the legacy wire is cleared, so the gateway writes
/// that header as the body set it and no second value of it (rustfs/gateway#1076).
///
/// The legacy writer puts the output's headers on the response and then extends it with the
/// body's own, and extending a header map replaces every value of a name it already holds. The
/// gateway instead refuses a handler header its encoder already wrote (rustfs/gateway#1043), so a
/// member the body's header replaces must not reach the encoder.
pub(super) fn headers_body(ctx: &Ctx<'_>, owner: &str, fields: &[Field]) -> Result<String, Vec<String>> {
    let Some(s3s) = ctx.facts.structs.get(owner) else {
        return Err(vec![format!("{owner}: not an s3s struct")]);
    };
    let mut errors = Vec::new();
    let mut body = String::new();
    for field in fields {
        let Some(wire) = field.wire_name.as_deref() else { continue };
        let header = wire.to_ascii_lowercase();
        match field.binding {
            Binding::Header => {}
            Binding::PrefixHeaders if !matches!(field.ty, Type::ChecksumSpec) => {
                match target(ctx, owner, field, s3s) {
                    Ok(Target::Member(member, S3sType::Option(inner))) if matches!(inner.as_ref(), S3sType::Map(..)) => {
                        let _ = writeln!(
                            body,
                            "    if let Some(map) = output.{member}.as_mut() {{\n        map.retain(|key, _| !headers.contains_key(format!(\"{header}{{key}}\").as_str()));\n    }}"
                        );
                    }
                    Ok(_) => errors.push(format!(
                        "{owner}.{}: a prefixed header member that is not an optional map",
                        bare_name(field)
                    )),
                    Err(error) => errors.push(error),
                }
                continue;
            }
            Binding::PrefixHeaders => {}
            _ => continue,
        }
        match target(ctx, owner, field, s3s) {
            Ok(Target::ChecksumFanOut) => {
                for (member, _) in CHECKSUM_FAN_OUT {
                    if s3s.iter().any(|(present, _)| present == member) {
                        let suffix = member.trim_start_matches("checksum_");
                        let _ = writeln!(
                            body,
                            "    if headers.contains_key(\"x-amz-checksum-{suffix}\") {{ output.{member} = None; }}"
                        );
                    }
                }
            }
            Ok(Target::Member(member, ty)) => {
                if matches!(ty, S3sType::Option(_)) {
                    let _ = writeln!(body, "    if headers.contains_key(\"{header}\") {{ output.{member} = None; }}");
                } else {
                    let _ = writeln!(
                        body,
                        "    if headers.contains_key(\"{header}\") {{\n        {};\n    }}",
                        missing(member, "a response header the RustFS body set would replace this required member")
                    );
                }
            }
            Ok(Target::GatewayOnly(_) | Target::CarriedByHeaders | Target::Supplied(..) | Target::Nested(..)) => {}
            Err(error) => errors.push(error),
        }
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    Ok(body)
}

/// One operation module: its module name and text.
pub(super) fn operation(ctx: &Ctx<'_>, ir: &OperationIr) -> Result<(String, String), Vec<String>> {
    let op = &ir.operation;
    let module = naming::module_name(op);
    let gw = format!("crate::ops::{}", naming::module_ident(op));
    ctx.supplied.borrow_mut().clear();
    let forward = forward_struct(ctx, &format!("{op}Input"), &ir.input, "input");
    let params: String = ctx
        .supplied
        .borrow_mut()
        .drain(..)
        .map(|(name, ty)| format!(", {name}: {ty}"))
        .collect();
    let backward = backward_struct(ctx, &format!("{op}Output"), &ir.output, &format!("{gw}::Output"), "output");
    let headers = headers_body(ctx, &format!("{op}Output"), &ir.output);
    let (forward, backward, headers) = match (forward, backward, headers) {
        (Ok(f), Ok(b), Ok(h)) => (f, b, h),
        (f, b, h) => {
            let mut errors = f.err().unwrap_or_default();
            errors.extend(b.err().unwrap_or_default());
            errors.extend(h.err().unwrap_or_default());
            return Err(errors.into_iter().map(|e| format!("{op}: {e}")).collect());
        }
    };
    let mutable = if headers.is_empty() { "" } else { "mut " };
    let mut out = String::from(HEADER);
    let _ = write!(
        out,
        "\n//! The `{op}` seam: the gateway input as the s3s input, the s3s output as the gateway output.\n\n{IMPORTS}\n\
         /// Converts a decoded gateway `{op}` input into the s3s input the RustFS app body receives.\n\
         ///\n/// # Errors\n///\n/// [`ConversionError`] naming a member the s3s input cannot hold.\n\
         #[allow(clippy::too_many_lines, clippy::needless_question_mark, clippy::redundant_closure_call)]\n\
         pub fn input_to_s3s(input: {gw}::Input{params}) -> Result<s3s::dto::{op}Input, ConversionError> {{\n{forward}}}\n\n\
         /// Converts the s3s output a RustFS app body returned into the gateway `{op}` output.\n\
         ///\n/// # Errors\n///\n/// [`ConversionError`] naming a member the gateway output cannot hold.\n\
         #[allow(clippy::too_many_lines, clippy::needless_question_mark, clippy::redundant_closure_call)]\n\
         pub fn output_from_s3s(output: s3s::dto::{op}Output) -> Result<{gw}::Output, ConversionError> {{\n{backward}}}\n\n\
         /// Converts a RustFS app body's whole answer — its output and the response headers it set\n\
         /// beside it — into the gateway `{op}` output and the extra headers the gateway writes after\n\
         /// it (`Resp::with_extra_headers`). The legacy writer lets such a header replace the one an\n\
         /// output member writes, so a member whose header the body set is left to that header.\n\
         ///\n/// # Errors\n///\n/// [`ConversionError`] as [`output_from_s3s`], or naming a required member one of the\n\
         /// headers would replace.\n\
         #[allow(clippy::too_many_lines, clippy::needless_pass_by_value)]\n\
         pub fn answer_from_legacy({mutable}output: s3s::dto::{op}Output, headers: http::HeaderMap) -> Result<({gw}::Output, http::HeaderMap), ConversionError> {{\n{headers}    Ok((output_from_s3s(output)?, headers))\n}}\n"
    );
    Ok((module, out))
}

/// One direction of one nested shape's conversion.
pub(super) fn shape_fn(ctx: &Ctx<'_>, raw: &str, shape: &Shape, forward: bool) -> Result<String, Vec<String>> {
    let gw = gateway_shape(raw);
    let name = format!("{}_{}", naming::module_name(raw), if forward { "to_s3s" } else { "from_s3s" });
    ctx.supplied.borrow_mut().clear();
    let body = match (shape.kind, forward) {
        (ShapeKind::Structure, true) => forward_struct(ctx, raw, &shape.fields, "value")?,
        (ShapeKind::Structure, false) => backward_struct(ctx, raw, &shape.fields, &gw, "value")?,
        (ShapeKind::Union, forward) => union(ctx, raw, &shape.fields, forward)?,
    };
    if !ctx.supplied.borrow().is_empty() {
        return Err(vec![format!(
            "{raw}: a nested shape's conversion takes no parameter; supply or decode the member at the operation"
        )]);
    }
    let (from, to) = if forward {
        (gw.clone(), format!("s3s::dto::{raw}"))
    } else {
        (format!("s3s::dto::{raw}"), gw.clone())
    };
    Ok(format!(
        "/// Converts one `{raw}` {}.\n///\n/// # Errors\n///\n/// [`ConversionError`] naming a member the other side cannot hold.\n\
         #[allow(clippy::too_many_lines, clippy::needless_question_mark, clippy::redundant_closure_call)]\n\
         pub fn {name}(value: {from}) -> Result<{to}, ConversionError> {{\n{body}}}\n",
        if forward {
            "from the gateway shape to the s3s shape"
        } else {
            "from the s3s shape to the gateway shape"
        }
    ))
}

fn union(ctx: &Ctx<'_>, raw: &str, fields: &[Field], forward: bool) -> Result<String, Vec<String>> {
    let Some(variants) = ctx.facts.unions.get(raw) else {
        return Err(vec![format!("{raw}: not an s3s union")]);
    };
    let gw = gateway_shape(raw);
    let mut errors = Vec::new();
    let mut arms = String::new();
    for field in fields {
        let variant = naming::type_name(&field.name);
        let Some((s3s_variant, ty)) = variants.iter().find(|(v, _)| naming::type_name(v) == variant) else {
            errors.push(format!("{raw}::{variant}: the s3s union has no such variant"));
            continue;
        };
        let conv = if forward {
            ctx.forward(&field.ty, ty, "x", &variant)
        } else {
            ctx.backward(ty, &field.ty, &field.name, "x", &variant)
        };
        match conv {
            Err(error) => errors.push(format!("{raw}::{variant}: {error}")),
            Ok(conv) if forward => {
                let _ = writeln!(arms, "        {gw}::{variant}(x) => s3s::dto::{raw}::{s3s_variant}({conv}),");
            }
            Ok(conv) => {
                let _ = writeln!(arms, "        s3s::dto::{raw}::{s3s_variant}(x) => {gw}::{variant}({conv}),");
            }
        }
    }
    if !forward {
        let _ = writeln!(
            arms,
            "        _ => {},",
            missing(raw, "an s3s variant the gateway model does not declare")
        );
    }
    if !errors.is_empty() {
        return Err(errors);
    }
    Ok(format!("    Ok(match value {{\n{arms}    }})\n"))
}

/// The file holding every direction of one shape's conversion.
pub(super) fn shape_file(raw: &str, bodies: &[String]) -> String {
    format!("{HEADER}\n//! The `{raw}` shape conversions.\n\n{IMPORTS}\n{}", bodies.join("\n"))
}

/// A facade that mounts one module per name.
pub(super) fn facade(what: &str, modules: &[String]) -> String {
    let mut out = format!("{HEADER}\n//! Generated seam {what}, one module each.\n\n");
    for module in modules {
        let _ = writeln!(out, "pub mod {module};");
    }
    out
}

/// The seam's generated root.
pub(super) fn root() -> String {
    format!(
        "{HEADER}\n//! The generated half of the migration seam (rustfs/gateway#967): one module per covered\n\
         //! operation and one per nested shape it reaches, converting against\n\
         //! `crate::compat::s3s_0_17_0` (its `s3s` and `leaf`).\n\
         //!\n\
         //! `census` holds the member census of every pinned structure they reach (rustfs/gateway#1076).\n\
         \npub mod census;\npub mod ops;\npub mod shapes;\n"
    )
}
